<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <IsOrleansFrameworkPart>false</IsOrleansFrameworkPart>
    <OrleansBuildTimeCodeGen>false</OrleansBuildTimeCodeGen>
    <EnableOrleansContractsAnalyzer>false</EnableOrleansContractsAnalyzer>
    <GenAPITargetDirectory>$(SourceRoot)src\api\System.Distributed.DurableTasks\</GenAPITargetDirectory>
    <GenAPITargetPath>$(GenAPITargetDirectory)$(AssemblyName).cs</GenAPITargetPath>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Remove="Orleans.Metadata.FrameworkPartAttribute" />
  </ItemGroup>
</Project>
