<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <OrleansVersion>10.2.2</OrleansVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Sdk" Version="$(OrleansVersion)" />
    <PackageReference Include="Microsoft.Orleans.Server" Version="$(OrleansVersion)" />
  </ItemGroup>
</Project>
