<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);ORLEANSEXP003;ORLEANSEXP005</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Azure.Storage.Blobs" />
    <PackageReference Include="Aspire.StackExchange.Redis" />
    <PackageReference Include="Azure.Storage.Blobs" />
    <PackageReference Include="Microsoft.Orleans.Clustering.Redis" />
    <PackageReference Include="Microsoft.Orleans.DurableJobs.AzureStorage" />
    <PackageReference Include="Microsoft.Orleans.DurableTasks" />
    <PackageReference Include="Microsoft.Orleans.Journaling" />
    <PackageReference Include="Microsoft.Orleans.Journaling.AzureStorage" />
    <PackageReference Include="Microsoft.Orleans.Server" />
  </ItemGroup>

</Project>
