<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Microsoft.Orleans.Connections.Security</PackageId>
    <Title>Microsoft Orleans connection security</Title>
    <Description>Support for secure communication using TLS and authenticated silo and client connections in Microsoft Orleans.</Description>
    <PackageTags>$(PackageTags) TLS SSL authentication</PackageTags>
    <TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>
    <OrleansBuildTimeCodeGen>true</OrleansBuildTimeCodeGen>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Orleans.Runtime\Orleans.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Orleans.Connections.Security.Tests" />
  </ItemGroup>
</Project>
