<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)src\Orleans.Client\Orleans.Client.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GPSTracker.Common\GPSTracker.Common.csproj" />
  </ItemGroup>
</Project>
