<Project>
  <PropertyGroup>
    <_ParentDirectoryBuildPropsPath Condition="'$(_DirectoryBuildPropsFile)' != ''">$([System.IO.Path]::Combine('..', '$(_DirectoryBuildPropsFile)'))</_ParentDirectoryBuildPropsPath>
  </PropertyGroup>

  <Import Project="$(_ParentDirectoryBuildPropsPath)" Condition="Exists('$(_ParentDirectoryBuildPropsPath)')"/>

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <WarnOnPackingNonPackableProject>false</WarnOnPackingNonPackableProject>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);FS2003</NoWarn>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup>
    <TestTargetFrameworks Condition="'$(TestTargetFrameworks)' == ''">net8.0;net10.0</TestTargetFrameworks>
    <IsOrleansTestApplication Condition="$(MSBuildProjectName.EndsWith('Test')) or $(MSBuildProjectName.EndsWith('Tests')) or '$(MSBuildProjectName)' == 'Benchmarks'">true</IsOrleansTestApplication>
    <IsTestProject Condition="'$(IsOrleansTestApplication)' == 'true'">true</IsTestProject>
    <IsTestingPlatformApplication Condition="'$(IsOrleansTestApplication)' == 'true'">true</IsTestingPlatformApplication>
    <OutputType Condition="'$(IsOrleansTestApplication)' == 'true'">Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner Condition="'$(IsOrleansTestApplication)' == 'true'">true</UseMicrosoftTestingPlatformRunner>
    <TestingPlatformCommandLineArguments Condition="'$(IsOrleansTestApplication)' == 'true'">$(TestingPlatformCommandLineArguments) --ignore-exit-code 8</TestingPlatformCommandLineArguments>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsOrleansTestApplication)' == 'true'">
    <PackageReference Include="Microsoft.Testing.Extensions.CrashDump" />
    <PackageReference Include="Microsoft.Testing.Extensions.HangDump" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0' and '$(IsOrleansTestApplication)' == 'true'">
    <PackageReference Include="System.Collections.Immutable" VersionOverride="10.0.0" PrivateAssets="all" />
    <PackageReference Include="System.IO.Pipelines" VersionOverride="10.0.5" PrivateAssets="all" />
    <PackageReference Include="System.Text.Json" VersionOverride="10.0.5" PrivateAssets="all" />
  </ItemGroup>

</Project>
