<Project>
  <PropertyGroup>
    <_ParentDirectoryBuildPropsPath Condition="'$(_DirectoryBuildPropsFile)' != ''">$([System.IO.Path]::Combine('..', '$(_DirectoryBuildPropsFile)'))</_ParentDirectoryBuildPropsPath>
  </PropertyGroup>

  <Import Project="$(_ParentDirectoryBuildPropsPath)" Condition="Exists('$(_ParentDirectoryBuildPropsPath)')"/>

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <WarnOnPackingNonPackableProject>false</WarnOnPackingNonPackableProject>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);FS2003;1591;xUnit1051</NoWarn>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup>
    <TestTargetFrameworks Condition="'$(TestTargetFrameworks)' == ''">net8.0;net10.0</TestTargetFrameworks>
    <OutputType Condition="$(MSBuildProjectName.EndsWith('.Test')) or $(MSBuildProjectName.EndsWith('.Tests'))">Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MsBuildThisFileDirectory)xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="System.IO.Pipelines" VersionOverride="10.0.5" PrivateAssets="all" Condition="'$(TargetFramework)' == 'net8.0'" />
    <PackageReference Include="System.Text.Json" VersionOverride="10.0.5" PrivateAssets="all" Condition="'$(TargetFramework)' == 'net8.0'" />
  </ItemGroup>

</Project>
