<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RepositoryRoot>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\..\..\..\..\..\..\..\..\'))</RepositoryRoot>
  </PropertyGroup>

  <!-- <silo_packages> -->
  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Server" Version="10.2.2" />
    <PackageReference Include="Microsoft.Orleans.Clustering.Redis" Version="10.2.2" />
    <PackageReference Include="Microsoft.Orleans.Clustering.AzureStorage" Version="10.2.2" />
    <PackageReference Include="Microsoft.Orleans.Clustering.DynamoDB" Version="10.2.2" />
    <PackageReference Include="Microsoft.Orleans.Persistence.AzureStorage" Version="10.2.2" />
    <PackageReference Include="Microsoft.Orleans.Persistence.DynamoDB" Version="10.2.2" />
    <PackageReference Include="Microsoft.Orleans.Reminders.AzureStorage" Version="10.2.2" />
    <PackageReference Include="Microsoft.Orleans.Reminders.DynamoDB" Version="10.2.2" />
    <PackageReference Include="Aspire.Azure.Storage.Blobs" Version="13.4.6" />
    <PackageReference Include="Aspire.StackExchange.Redis" Version="13.4.6" />
  </ItemGroup>
  <!-- </silo_packages> -->

  <ItemGroup>
    <PackageReference Include="Aspire.Azure.Data.Tables" Version="13.4.6" />
    <PackageReference Include="Aspire.Microsoft.Azure.Cosmos" Version="13.4.6" />
    <PackageReference Include="Aspire.Microsoft.Data.SqlClient" Version="13.4.6" />
    <PackageReference Include="Microsoft.Orleans.Persistence.Redis" Version="10.2.2" />
    <PackageReference Include="Microsoft.Orleans.Clustering.Cosmos" Version="10.2.2" />
    <PackageReference Include="Microsoft.Orleans.Persistence.Cosmos" Version="10.2.2" />
    <PackageReference Include="Microsoft.Orleans.Reminders.Cosmos" Version="10.2.2" />
    <PackageReference Include="Microsoft.Orleans.Reminders.Redis" Version="10.2.2" />
    <PackageReference Include="Microsoft.Orleans.GrainDirectory.Redis" Version="10.2.2" />
    <PackageReference Include="Microsoft.Orleans.Streaming.EventHubs" Version="10.2.2" />
    <PackageReference Include="Microsoft.Orleans.Clustering.AdoNet" Version="10.2.2" />
    <PackageReference Include="Microsoft.Orleans.Persistence.AdoNet" Version="10.2.2" />
    <PackageReference Include="Microsoft.Orleans.Reminders.AdoNet" Version="10.2.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServiceDefaults\ServiceDefaults.csproj" />
    <ProjectReference Include="$(RepositoryRoot)src\AWS\Orleans.Streaming.Kinesis\Orleans.Streaming.Kinesis.csproj" />
    <ProjectReference Include="$(RepositoryRoot)src\AdoNet\Orleans.GrainDirectory.AdoNet\Orleans.GrainDirectory.AdoNet.csproj" />
    <ProjectReference Include="$(RepositoryRoot)src\AdoNet\Orleans.Streaming.AdoNet\Orleans.Streaming.AdoNet.csproj" />
  </ItemGroup>

</Project>
