//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Orleans.GrainDirectory
{
    public static partial class PostgreSqlHostingExtensions
    {
        public static Hosting.ISiloBuilder AddEntityFrameworkCorePostgreSqlGrainDirectory(this Hosting.ISiloBuilder builder, string name, System.Action<Microsoft.EntityFrameworkCore.DbContextOptionsBuilder> configureDatabase) { throw null; }

        public static Hosting.ISiloBuilder AddEntityFrameworkCorePostgreSqlGrainDirectory(this Hosting.ISiloBuilder builder, string name) { throw null; }

        public static Hosting.ISiloBuilder UseEntityFrameworkCorePostgreSqlGrainDirectoryAsDefault(this Hosting.ISiloBuilder builder, System.Action<Microsoft.EntityFrameworkCore.DbContextOptionsBuilder> configureDatabase) { throw null; }

        public static Hosting.ISiloBuilder UseEntityFrameworkCorePostgreSqlGrainDirectoryAsDefault(this Hosting.ISiloBuilder builder) { throw null; }
    }
}

namespace Orleans.GrainDirectory.EntityFrameworkCore.PostgreSQL.Data
{
    public partial class PostgreSqlGrainDirectoryDbContext : EntityFrameworkCore.Data.GuidGrainDirectoryDbContext<PostgreSqlGrainDirectoryDbContext>
    {
        public PostgreSqlGrainDirectoryDbContext(Microsoft.EntityFrameworkCore.DbContextOptions<PostgreSqlGrainDirectoryDbContext> options) : base(default!) { }
    }

    public partial class PostgreSqlGrainDirectoryDbContextFactory : Microsoft.EntityFrameworkCore.Design.IDesignTimeDbContextFactory<PostgreSqlGrainDirectoryDbContext>
    {
        public PostgreSqlGrainDirectoryDbContext CreateDbContext(string[] args) { throw null; }
    }
}

namespace Orleans.GrainDirectory.EntityFrameworkCore.PostgreSQL.Data.Migrations
{
    [Microsoft.EntityFrameworkCore.Infrastructure.DbContext(typeof(PostgreSqlGrainDirectoryDbContext))]
    [Microsoft.EntityFrameworkCore.Migrations.Migration("20260811155000_InitialGrainDirectorySchema")]
    public partial class InitialGrainDirectorySchema : Microsoft.EntityFrameworkCore.Migrations.Migration
    {
        protected override void BuildTargetModel(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder) { }

        protected override void Down(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder migrationBuilder) { }

        protected override void Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder migrationBuilder) { }
    }
}