trigger:
  branches:
    include:
    - '*'

pr: none

schedules:
- cron: '0 */2 * * *'
  displayName: Scheduled sync
  branches:
    include:
    - main

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool: 
      name: orleans-build-hosted-pool
      image: orleans-build-image
      os: windows
    stages:
    - stage: clone
      displayName: Mirror GitHub repo
      jobs:
      - job:
        steps:
        - checkout: self
          displayName: Clone GitHub repo
          fetchDepth: 0
          fetchTags: true
        - task: Powershell@2
          displayName: Set git config
          inputs:
            targetType: 'inline'
            script: |
              git config --global user.email "${env:GIT_USEREMAIL}"
              git config --global user.name "${env:GIT_USERNAME}"
        - task: PowerShell@2
          displayName: Push to remote repo
          inputs:
            targetType: 'inline'
            script: |
              foreach ($ref in ${env:REFS_MIRROR}.Split(' '))
              {
                git config --add remote.origin.fetch "$ref"
              }
              git fetch --all
              git remote add --mirror=fetch mirror https://${Env:SYSTEM_ACCESSTOKEN}@${env:REMOTE_REPOSITORY}
              git push --force --all --progress mirror
          env:
            SYSTEM_ACCESSTOKEN: $(System.AccessToken)