trigger: none
pr: none

schedules:
- cron: "0 0 * * *"
  displayName: Publish nightly packages
  branches:
    include:
    - main
  always: false

variables:
- template: templates/vars.yaml

jobs:
- template: templates/build.yaml
  parameters:
    build_configuration: Release
    version_prefix: '8.1.0'
    include_suffix: true
    version_suffix: nightly.$(Build.BuildNumber)
    codesign: true
    publish_nightly: true
    skip_test: true
