trigger: none
pr: none

schedules:
- cron: "0 0 * * *"
  displayName: Publish nightly packages
  branches:
    include:
    - main
  always: false

variables:
- template: templates/vars.yaml

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  ${{ if eq(variables['System.TeamProject'], 'GitHub - PR Builds') }}:
    template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  ${{ else }}:
    template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      policheck:
        enabled: true
      tsa:
        enabled: true
    settings:
      skipBuildTagsForGitHubPullRequests: true
    pool:
      name: $(pool_name)
      image: $(pool_image)
      os: windows
    stages:
    - stage: build_test
      displayName: Build and Tests
      jobs:
      - template: /.azure/pipelines/templates/build.yaml@self
        parameters:
          build_configuration: Release
          version_prefix: '9.2.0'
          include_suffix: true
          version_suffix: nightly.$(Build.BuildNumber)
          codesign: true
          publish_nightly: true
          publish_nuget: false
          skip_test: true
