trigger: none
pr: none

schedules:
- cron: "0 0 * * *"
  displayName: Publish nightly packages
  branches:
    include:
    - main
  always: false

parameters:
  - name: publish_nuget
    displayName: Publish to nuget.org
    type: boolean
    default: false
  - name: publish_nightly
    displayName: Publish to orleans-nightly
    type: boolean
    default: true
  - name: version_prefix
    displayName: Version prefix
    type: string
    default: 10.0.0
  - name: version_suffix
    displayName: Version suffix
    type: string
    default: nightly.$(Build.BuildNumber)
  - name: include_suffix
    displayName: Append version suffix
    type: boolean
    default: true

variables:
- template: templates/vars.yaml

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  ${{ if eq(variables['System.TeamProject'], 'GitHub - PR Builds') }}:
    template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  ${{ else }}:
    template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      policheck:
        enabled: true
      tsa:
        enabled: true
    settings:
      skipBuildTagsForGitHubPullRequests: true
    pool:
      name: $(pool_name)
      image: $(pool_image)
      os: windows
    stages:
    - stage: build_test
      displayName: Build and Tests
      jobs:
      - template: /.azure/pipelines/templates/build.yaml@self
        parameters:
          build_configuration: Release
          version_prefix: ${{ parameters.version_prefix }}
          include_suffix: ${{ parameters.include_suffix }}
          version_suffix: ${{ parameters.version_suffix }}
          codesign: true
          publish_nightly: ${{ parameters.publish_nightly }}
          publish_nuget: ${{ parameters.publish_nuget }}
          skip_test: true
