using System;
using System.Collections.Generic;
using System.Reflection;
using Orleans.Serialization.Configuration;

namespace Orleans
{
    /// <summary>
    /// Resolves configuration-driven provider registrations from a set of assemblies.
    /// </summary>
    /// <remarks>
    /// Registrations are read from generated provider metadata (types implementing
    /// <see cref="IProviderMetadataProvider"/> which are emitted by the Orleans code generator). Provider
    /// assemblies produced by an older code generator do not carry that metadata, so their registrations are
    /// read from <see cref="RegisterProviderAttribute"/> as a fallback. Only providers implementing
    /// <see cref="IProviderMetadataProvider"/> and marked as generated by <c>OrleansCodeGen</c> are activated;
    /// other <see cref="TypeManifestProviderAttribute"/> providers are never instantiated during discovery.
    /// </remarks>
    internal static class ProviderRegistrationResolver
    {
        /// <summary>
        /// Gets the providers registered for the specified <paramref name="target"/>, keyed by kind and name.
        /// </summary>
        /// <param name="assemblies">The assemblies to scan for provider registrations.</param>
        /// <param name="target">The registration target to filter on, for example <c>"Client"</c> or <c>"Silo"</c>.</param>
        public static Dictionary<(string Kind, string Name), Type> GetRegisteredProviders(IEnumerable<Assembly> assemblies, string target)
        {
            var result = new Dictionary<(string, string), Type>();
            var registeredProviders = new Dictionary<(string Target, string Kind, string Name), Type>();

            // Collect providers from generated metadata.
            foreach (var asm in assemblies)
            {
                var hasGeneratedProviderMetadata = false;
                var attrs = asm.GetCustomAttributes<TypeManifestProviderAttribute>();
                foreach (var attr in attrs)
                {
                    if (typeof(IProviderMetadataProvider).IsAssignableFrom(attr.ProviderType)
                        && attr.ProviderType.GetCustomAttribute<System.CodeDom.Compiler.GeneratedCodeAttribute>() is { Tool: "OrleansCodeGen" }
                        && Activator.CreateInstance(attr.ProviderType) is IProviderMetadataProvider provider)
                    {
                        provider.ConfigureProviders(registeredProviders);
                        hasGeneratedProviderMetadata = true;
                    }
                }

                // Provider assemblies built with an older generator do not include provider metadata.
                if (!hasGeneratedProviderMetadata && asm.IsDefined(typeof(RegisterProviderAttribute)))
                {
                    foreach (var attr in asm.GetCustomAttributes<RegisterProviderAttribute>())
                    {
                        registeredProviders[(attr.Target, attr.Kind, attr.Name)] = attr.Type;
                    }
                }
            }

            foreach (var kvp in registeredProviders)
            {
                if (string.Equals(kvp.Key.Target, target, StringComparison.Ordinal))
                {
                    result[(kvp.Key.Kind, kvp.Key.Name)] = kvp.Value;
                }
            }

            return result;
        }
    }
}
