<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RepositoryRoot>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\..\..\..\..\..\..\..\'))</RepositoryRoot>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(RepositoryRoot)src\Orleans.Client\Orleans.Client.csproj" />
    <ProjectReference Include="$(RepositoryRoot)src\Orleans.Server\Orleans.Server.csproj" />
  </ItemGroup>

</Project>
