<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Azure.Identity" Version="1.18.0" />
    <PackageVersion Include="Blazor.LocalStorage" Version="9.0.1" />
    <PackageVersion Include="Blazor.Serialization" Version="9.0.1" />
    <PackageVersion Include="Bogus" Version="35.6.5" />
    <PackageVersion Include="Microsoft.Orleans.Clustering.Cosmos" Version="10.2.2" />
    <PackageVersion Include="Microsoft.Orleans.Persistence.Cosmos" Version="10.2.2" />
    <PackageVersion Include="Microsoft.Orleans.Runtime" Version="10.2.2" />
    <PackageVersion Include="Microsoft.Orleans.Sdk" Version="10.2.2" />
    <PackageVersion Include="Microsoft.Orleans.Server" Version="10.2.2" />
    <PackageVersion Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageVersion Include="MudBlazor" Version="8.15.0" />
  </ItemGroup>
</Project>
