<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <OrleansBuildTimeCodeGen>true</OrleansBuildTimeCodeGen>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Extensions\**" />
    <EmbeddedResource Remove="Extensions\**" />
    <None Remove="Extensions\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configurators" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="RabbitMQ.Stream.Client" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)src\Orleans.Streaming\Orleans.Streaming.csproj" />
  </ItemGroup>

</Project>
