apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_ENDPOINT}
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 5s
