//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Orleans.Configuration
{
    public sealed partial class EntraSiloConnectionOptions
    {
        public System.Collections.Generic.ISet<string> AdditionalTrustedMetadataHosts { get { throw null; } }

        public bool AllowAnyApplicationInTenant { get { throw null; } set { } }

        public bool AllowDelegatedTokens { get { throw null; } set { } }

        public System.Collections.Generic.ISet<string> AllowedAlgorithms { get { throw null; } }

        public System.Collections.Generic.ISet<string> AllowedClientIds { get { throw null; } }

        public System.Collections.Generic.ISet<string> AllowedServicePrincipalObjectIds { get { throw null; } }

        public System.Uri? Authority { get { throw null; } set { } }

        public System.TimeSpan AutomaticMetadataRefreshInterval { get { throw null; } set { } }

        public System.TimeSpan ClockSkew { get { throw null; } set { } }

        [System.Obsolete("Use ResourceApplicationId with ClusterRole or ClusterClaimType instead. TokenScope is not a JWT audience.")]
        public string? ClusterAudienceFormat { get { throw null; } set { } }

        public string? ClusterClaimType { get { throw null; } set { } }

        public string? ClusterRole { get { throw null; } set { } }

        public string? ClusterRoleFormat { get { throw null; } set { } }

        public System.TimeSpan LastKnownGoodLifetime { get { throw null; } set { } }

        public System.TimeSpan MaximumMetadataRefreshBackoff { get { throw null; } set { } }

        public int MaximumMetadataRefreshQueueSize { get { throw null; } set { } }

        public int MaximumMetadataSize { get { throw null; } set { } }

        public System.TimeSpan MaximumTokenLifetime { get { throw null; } set { } }

        public int MaximumTokenSize { get { throw null; } set { } }

        public System.TimeSpan MetadataRefreshBackoff { get { throw null; } set { } }

        public double MetadataRefreshJitterRatio { get { throw null; } set { } }

        public System.TimeSpan MetadataRetrievalTimeout { get { throw null; } set { } }

        public System.TimeSpan MinimumRemainingTokenLifetime { get { throw null; } set { } }

        public System.Collections.Generic.ISet<string> RequiredRoles { get { throw null; } }

        public string? ResourceApplicationId { get { throw null; } set { } }

        public System.Collections.Generic.ISet<string> SupportedTokenVersions { get { throw null; } }

        public string? TokenScope { get { throw null; } set { } }

        public System.TimeSpan UnknownSigningKeyRefreshInterval { get { throw null; } set { } }

        public System.Collections.Generic.ISet<string> ValidAudiences { get { throw null; } }

        public System.Collections.Generic.ISet<string> ValidTenantIds { get { throw null; } }
    }
}

namespace Orleans.Hosting
{
    public static partial class EntraSiloConnectionAuthenticationExtensions
    {
        public static SiloConnectionAuthenticationBuilder UseEntra(this SiloConnectionAuthenticationBuilder builder, Azure.Core.TokenCredential credential, System.Action<Configuration.EntraSiloConnectionOptions> configureOptions) { throw null; }
    }
}