CREATE TABLE "ORLEANSSTATISTICSTABLE"
   (
    "ORLEANSSTATISTICSTABLEID" NUMBER(*,0),
    "DEPLOYMENTID" NVARCHAR2(150) NOT NULL ENABLE,
    "TIMESTAMP" TIMESTAMP (6) DEFAULT sys_extract_utc(systimestamp) NOT NULL ENABLE,
    "ID" NVARCHAR2(250) NOT NULL ENABLE,
    "HOSTNAME" NVARCHAR2(150) NOT NULL ENABLE,
    "NAME" NVARCHAR2(150) NOT NULL ENABLE,
    "ISVALUEDELTA" NUMBER(*,0) NOT NULL ENABLE,
    "STATVALUE" NVARCHAR2(1024),
    "STATISTIC" NVARCHAR2(512) NOT NULL ENABLE,
     CONSTRAINT "ORLEANSSTATISTICSTABLE_PK" PRIMARY KEY ("ORLEANSSTATISTICSTABLEID")
   );
/

CREATE SEQUENCE "ORLEANSSTATISTICSTABLE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;

CREATE OR REPLACE TRIGGER "ORLEANSSTATISTICSTABLE_TRG"
BEFORE INSERT ON ORLEANSSTATISTICSTABLE
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ORLEANSSTATISTICSTABLEID IS NULL THEN
      SELECT ORLEANSSTATISTICSTABLE_SEQ.NEXTVAL INTO :NEW.ORLEANSSTATISTICSTABLEID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ORLEANSSTATISTICSTABLE_TRG" ENABLE;

INSERT INTO OrleansQuery(QueryKey, QueryText)
VALUES
(
    'InsertOrleansStatisticsKey','
BEGIN
    INSERT INTO OrleansStatisticsTable
    (
        DeploymentId,
        Id,
        HostName,
        Name,
        IsValueDelta,
        StatValue,
        Statistic
    )
    SELECT :DeploymentId, :Id, :HostName, :Name, :IsValueDelta, :StatValue, :Statistic FROM DUAL;
END;
');
/

COMMIT;
