//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Orleans.Journaling
{
    public sealed partial class AzureBlobJournalStorageOptions
    {
        public const string DEFAULT_CONTAINER_NAME = "state";
        public const int DEFAULT_MAX_METADATA_ONLY_CONFLICT_RETRIES = 5;
        public static readonly System.TimeSpan DEFAULT_METADATA_ONLY_CONFLICT_INITIAL_BACKOFF;
        public static readonly System.TimeSpan DEFAULT_METADATA_ONLY_CONFLICT_MAX_BACKOFF;
        public Azure.Storage.Blobs.BlobServiceClient? BlobServiceClient { get { throw null; } set { } }

        public System.Func<System.IServiceProvider, AzureBlobJournalStorageOptions, IBlobContainerFactory> BuildContainerFactory { get { throw null; } set { } }

        public Azure.Storage.Blobs.BlobClientOptions? ClientOptions { get { throw null; } set { } }

        public string ContainerName { get { throw null; } set { } }

        public bool DeleteOldCheckpoints { get { throw null; } set { } }

        public System.Func<JournalId, string, string> GetCheckpointBlobName { get { throw null; } set { } }

        public System.Func<JournalId, string> GetWalBlobName { get { throw null; } set { } }

        public int MaxMetadataOnlyConflictRetries { get { throw null; } set { } }

        public System.TimeSpan MetadataOnlyConflictInitialBackoff { get { throw null; } set { } }

        public System.TimeSpan MetadataOnlyConflictMaxBackoff { get { throw null; } set { } }

        public void ConfigureBlobServiceClient(System.Func<System.Threading.CancellationToken, System.Threading.Tasks.Task<Azure.Storage.Blobs.BlobServiceClient>> createClientCallback) { }

        public void ConfigureBlobServiceClient(string connectionString) { }

        public void ConfigureBlobServiceClient(System.Uri serviceUri, Azure.AzureSasCredential azureSasCredential) { }

        public void ConfigureBlobServiceClient(System.Uri serviceUri, Azure.Core.TokenCredential tokenCredential) { }

        public void ConfigureBlobServiceClient(System.Uri serviceUri, Azure.Storage.StorageSharedKeyCredential sharedKeyCredential) { }

        public void ConfigureBlobServiceClient(System.Uri serviceUri) { }
    }

    public static partial class AzureBlobStorageHostingExtensions
    {
        public static Hosting.ISiloBuilder AddAzureBlobJournalStorage(this Hosting.ISiloBuilder builder, System.Action<AzureBlobJournalStorageOptions>? configure) { throw null; }

        public static Hosting.ISiloBuilder AddAzureBlobJournalStorage(this Hosting.ISiloBuilder builder) { throw null; }
    }

    public partial interface IBlobContainerFactory
    {
        Azure.Storage.Blobs.BlobContainerClient GetBlobContainerClient(JournalId journalId);
        System.Threading.Tasks.Task InitializeAsync(Azure.Storage.Blobs.BlobServiceClient client, System.Threading.CancellationToken cancellationToken);
    }
}