<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>
    <IsPackable Condition="'$(PackUnpublishedSampleDependencies)' != 'true'">false</IsPackable>
    <IsOrleansFrameworkPart>false</IsOrleansFrameworkPart>
    <OrleansBuildTimeCodeGen>false</OrleansBuildTimeCodeGen>
    <EnableOrleansContractsAnalyzer>false</EnableOrleansContractsAnalyzer>
    <GenAPITargetDirectory>$(SourceRoot)src\api\Orleans.DurableTasks.Abstractions\</GenAPITargetDirectory>
    <GenAPITargetPath>$(GenAPITargetDirectory)$(AssemblyName).cs</GenAPITargetPath>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Remove="Orleans.Metadata.FrameworkPartAttribute" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
