//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Orleans.DurableJobs
{
    [GenerateSerializer]
    [Alias("Orleans.DurableJobs.DurableJob")]
    public sealed partial class DurableJob
    {
        [Id(2)]
        public System.DateTimeOffset DueTime { get { throw null; } init { } }

        [Id(0)]
        public required string Id { get { throw null; } init { } }

        [Id(5)]
        public System.Collections.Generic.IReadOnlyDictionary<string, string>? Metadata { get { throw null; } init { } }

        [Id(1)]
        public required string Name { get { throw null; } init { } }

        [Id(4)]
        public required string ShardId { get { throw null; } init { } }

        [Id(3)]
        public Runtime.GrainId TargetGrainId { get { throw null; } init { } }
    }

    [GenerateSerializer]
    public sealed partial class DurableJobRunResult
    {
        internal DurableJobRunResult() { }

        public static DurableJobRunResult Completed { get { throw null; } }

        [Id(2)]
        public System.Exception? Exception { get { throw null; } }

        [System.Diagnostics.CodeAnalysis.MemberNotNullWhen(true, "Exception")]
        public bool IsFailed { get { throw null; } }

        [System.Diagnostics.CodeAnalysis.MemberNotNullWhen(true, "PollAfterDelay")]
        public bool IsPending { get { throw null; } }

        [Id(1)]
        public System.TimeSpan? PollAfterDelay { get { throw null; } }

        [Id(0)]
        public DurableJobRunStatus Status { get { throw null; } }

        public static DurableJobRunResult Failed(System.Exception exception) { throw null; }

        public static DurableJobRunResult PollAfter(System.TimeSpan delay) { throw null; }
    }

    public enum DurableJobRunStatus
    {
        Completed = 0,
        PollAfter = 1,
        Failed = 2
    }

    public partial interface IDurableJobHandler
    {
        System.Threading.Tasks.Task ExecuteJobAsync(IJobRunContext context, System.Threading.CancellationToken cancellationToken);
    }

    public partial interface IJobRunContext
    {
        int DequeueCount { get; }

        DurableJob Job { get; }

        string RunId { get; }
    }

    public partial interface IJobShard : System.IAsyncDisposable
    {
        System.DateTimeOffset EndTime { get; }

        string Id { get; }

        bool IsAddingCompleted { get; }

        System.Collections.Generic.IDictionary<string, string>? Metadata { get; }

        System.DateTimeOffset StartTime { get; }

        System.Collections.Generic.IAsyncEnumerable<IJobRunContext> ConsumeDurableJobsAsync();
        System.Threading.Tasks.ValueTask<int> GetJobCountAsync();
        System.Threading.Tasks.Task MarkAsCompleteAsync(System.Threading.CancellationToken cancellationToken);
        System.Threading.Tasks.Task<bool> RemoveJobAsync(string jobId, System.Threading.CancellationToken cancellationToken);
        System.Threading.Tasks.Task RetryJobLaterAsync(IJobRunContext jobContext, System.DateTimeOffset newDueTime, System.Threading.CancellationToken cancellationToken);
        System.Threading.Tasks.Task<DurableJob?> TryScheduleJobAsync(ScheduleJobRequest request, System.Threading.CancellationToken cancellationToken);
    }

    public partial interface ILocalDurableJobManager
    {
        System.Threading.Tasks.Task<DurableJob> ScheduleJobAsync(ScheduleJobRequest request, System.Threading.CancellationToken cancellationToken);
        System.Threading.Tasks.Task<bool> TryCancelDurableJobAsync(DurableJob job, System.Threading.CancellationToken cancellationToken);
    }

    public abstract partial class JobShard : IJobShard, System.IAsyncDisposable
    {
        protected JobShard(string id, System.DateTimeOffset startTime, System.DateTimeOffset endTime) { }

        public System.DateTimeOffset EndTime { get { throw null; } protected set { } }

        public string Id { get { throw null; } protected set { } }

        public bool IsAddingCompleted { get { throw null; } protected set { } }

        public System.Collections.Generic.IDictionary<string, string>? Metadata { get { throw null; } protected set { } }

        public System.DateTimeOffset StartTime { get { throw null; } protected set { } }

        public System.Collections.Generic.IAsyncEnumerable<IJobRunContext> ConsumeDurableJobsAsync() { throw null; }

        public virtual System.Threading.Tasks.ValueTask DisposeAsync() { throw null; }

        protected void EnqueueJob(DurableJob job, int dequeueCount) { }

        public System.Threading.Tasks.ValueTask<int> GetJobCountAsync() { throw null; }

        public System.Threading.Tasks.Task MarkAsCompleteAsync(System.Threading.CancellationToken cancellationToken) { throw null; }

        protected abstract System.Threading.Tasks.Task PersistAddJobAsync(string jobId, string jobName, System.DateTimeOffset dueTime, Runtime.GrainId target, System.Collections.Generic.IReadOnlyDictionary<string, string>? metadata, System.Threading.CancellationToken cancellationToken);
        protected abstract System.Threading.Tasks.Task PersistRemoveJobAsync(string jobId, System.Threading.CancellationToken cancellationToken);
        protected abstract System.Threading.Tasks.Task PersistRetryJobAsync(string jobId, System.DateTimeOffset newDueTime, System.Threading.CancellationToken cancellationToken);
        public System.Threading.Tasks.Task<bool> RemoveJobAsync(string jobId, System.Threading.CancellationToken cancellationToken) { throw null; }

        public System.Threading.Tasks.Task RetryJobLaterAsync(IJobRunContext jobContext, System.DateTimeOffset newDueTime, System.Threading.CancellationToken cancellationToken) { throw null; }

        public System.Threading.Tasks.Task<DurableJob?> TryScheduleJobAsync(ScheduleJobRequest request, System.Threading.CancellationToken cancellationToken) { throw null; }
    }

    public abstract partial class JobShardManager
    {
        protected JobShardManager(Runtime.SiloAddress siloAddress) { }

        protected Runtime.SiloAddress SiloAddress { get { throw null; } }

        public abstract System.Threading.Tasks.Task<System.Collections.Generic.List<IJobShard>> AssignJobShardsAsync(System.DateTimeOffset maxDueTime, System.Threading.CancellationToken cancellationToken);
        public abstract System.Threading.Tasks.Task<IJobShard> CreateShardAsync(System.DateTimeOffset minDueTime, System.DateTimeOffset maxDueTime, System.Collections.Generic.IDictionary<string, string> metadata, System.Threading.CancellationToken cancellationToken);
        public abstract System.Threading.Tasks.Task UnregisterShardAsync(IJobShard shard, System.Threading.CancellationToken cancellationToken);
    }

    public readonly partial struct ScheduleJobRequest
    {
        private readonly object _dummy;
        private readonly int _dummyPrimitive;
        public required System.DateTimeOffset DueTime { get { throw null; } init { } }

        public required string JobName { get { throw null; } init { } }

        public System.Collections.Generic.IReadOnlyDictionary<string, string>? Metadata { get { throw null; } init { } }

        public required Runtime.GrainId Target { get { throw null; } init { } }
    }
}

namespace Orleans.Hosting
{
    public static partial class DurableJobsExtensions
    {
        public static void AddDurableJobs(this Microsoft.Extensions.DependencyInjection.IServiceCollection services) { }

        public static ISiloBuilder AddDurableJobs(this ISiloBuilder builder) { throw null; }

        public static ISiloBuilder UseInMemoryDurableJobs(this ISiloBuilder builder) { throw null; }
    }

    public sealed partial class DurableJobsOptions
    {
        public bool ConcurrencySlowStartEnabled { get { throw null; } set { } }

        public int MaxAdoptedCount { get { throw null; } set { } }

        public int MaxConcurrentJobsPerSilo { get { throw null; } set { } }

        public System.TimeSpan OverloadBackoffDelay { get { throw null; } set { } }

        public System.TimeSpan ShardActivationBufferPeriod { get { throw null; } set { } }

        public System.TimeSpan ShardDuration { get { throw null; } set { } }

        public System.Func<DurableJobs.IJobRunContext, System.Exception, System.DateTimeOffset?> ShouldRetry { get { throw null; } set { } }

        public int SlowStartInitialConcurrency { get { throw null; } set { } }

        public System.TimeSpan SlowStartInterval { get { throw null; } set { } }
    }

    public sealed partial class DurableJobsOptionsValidator : IConfigurationValidator
    {
        public DurableJobsOptionsValidator(Microsoft.Extensions.Logging.ILogger<DurableJobsOptionsValidator> logger, Microsoft.Extensions.Options.IOptions<DurableJobsOptions> options) { }

        public void ValidateConfiguration() { }
    }
}

namespace OrleansCodeGen.Orleans.DurableJobs
{
    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_DurableJob : global::Orleans.Serialization.Codecs.IFieldCodec<global::Orleans.DurableJobs.DurableJob>, global::Orleans.Serialization.Codecs.IFieldCodec
    {
        public Codec_DurableJob(global::Orleans.Serialization.Activators.IActivator<global::Orleans.DurableJobs.DurableJob> _activator, global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public void Deserialize<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.DurableJobs.DurableJob instance) { }

        public global::Orleans.DurableJobs.DurableJob ReadValue<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, global::Orleans.DurableJobs.DurableJob instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, global::Orleans.DurableJobs.DurableJob value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_DurableJobRunResult : global::Orleans.Serialization.Codecs.IFieldCodec<global::Orleans.DurableJobs.DurableJobRunResult>, global::Orleans.Serialization.Codecs.IFieldCodec
    {
        public Codec_DurableJobRunResult(global::Orleans.Serialization.Activators.IActivator<global::Orleans.DurableJobs.DurableJobRunResult> _activator, global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public void Deserialize<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.DurableJobs.DurableJobRunResult instance) { }

        public global::Orleans.DurableJobs.DurableJobRunResult ReadValue<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, global::Orleans.DurableJobs.DurableJobRunResult instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, global::Orleans.DurableJobs.DurableJobRunResult value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_DurableJob : global::Orleans.Serialization.Cloning.IDeepCopier<global::Orleans.DurableJobs.DurableJob>, global::Orleans.Serialization.Cloning.IDeepCopier
    {
        public Copier_DurableJob(global::Orleans.Serialization.Activators.IActivator<global::Orleans.DurableJobs.DurableJob> _activator, global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public global::Orleans.DurableJobs.DurableJob DeepCopy(global::Orleans.DurableJobs.DurableJob original, global::Orleans.Serialization.Cloning.CopyContext context) { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_DurableJobRunResult : global::Orleans.Serialization.Cloning.IDeepCopier<global::Orleans.DurableJobs.DurableJobRunResult>, global::Orleans.Serialization.Cloning.IDeepCopier
    {
        public Copier_DurableJobRunResult(global::Orleans.Serialization.Activators.IActivator<global::Orleans.DurableJobs.DurableJobRunResult> _activator) { }

        public global::Orleans.DurableJobs.DurableJobRunResult DeepCopy(global::Orleans.DurableJobs.DurableJobRunResult original, global::Orleans.Serialization.Cloning.CopyContext context) { throw null; }
    }
}