//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Orleans.DurableJobs
{
    [GenerateSerializer]
    [Alias("Orleans.DurableJobs.DurableJob")]
    public sealed partial class DurableJob
    {
        [Id(2)]
        public System.DateTimeOffset DueTime { get { throw null; } init { } }

        [Id(0)]
        public required string Id { get { throw null; } init { } }

        [Id(5)]
        public System.Collections.Generic.IReadOnlyDictionary<string, string>? Metadata { get { throw null; } init { } }

        [Id(1)]
        public required string Name { get { throw null; } init { } }

        [Id(4)]
        public required string ShardId { get { throw null; } init { } }

        [Id(3)]
        public Runtime.GrainId TargetGrainId { get { throw null; } init { } }
    }

    [GenerateSerializer]
    public sealed partial class DurableJobRunResult
    {
        internal DurableJobRunResult() { }

        public static DurableJobRunResult Completed { get { throw null; } }

        [Id(2)]
        public System.Exception? Exception { get { throw null; } }

        [System.Diagnostics.CodeAnalysis.MemberNotNullWhen(true, "Exception")]
        public bool IsFailed { get { throw null; } }

        [System.Diagnostics.CodeAnalysis.MemberNotNullWhen(true, "PollAfterDelay")]
        public bool IsPending { get { throw null; } }

        [Id(1)]
        public System.TimeSpan? PollAfterDelay { get { throw null; } }

        [Id(0)]
        public DurableJobRunStatus Status { get { throw null; } }

        public static DurableJobRunResult Failed(System.Exception exception) { throw null; }

        public static DurableJobRunResult PollAfter(System.TimeSpan delay) { throw null; }
    }

    public enum DurableJobRunStatus
    {
        Completed = 0,
        PollAfter = 1,
        Failed = 2
    }

    public partial interface IDurableJobHandler
    {
        System.Threading.Tasks.Task ExecuteJobAsync(IJobRunContext context, System.Threading.CancellationToken cancellationToken);
    }

    public partial interface IJobRunContext
    {
        int DequeueCount { get; }

        DurableJob Job { get; }

        string RunId { get; }
    }

    public partial interface ILocalDurableJobManager
    {
        System.Threading.Tasks.Task<DurableJob> ScheduleJobAsync(ScheduleJobRequest request, System.Threading.CancellationToken cancellationToken);
        System.Threading.Tasks.Task<bool> TryCancelDurableJobAsync(DurableJob job, System.Threading.CancellationToken cancellationToken);
    }

    public readonly partial struct ScheduleJobRequest
    {
        private readonly object _dummy;
        private readonly int _dummyPrimitive;
        public required System.DateTimeOffset DueTime { get { throw null; } init { } }

        public required string JobName { get { throw null; } init { } }

        public System.Collections.Generic.IReadOnlyDictionary<string, string>? Metadata { get { throw null; } init { } }

        public required Runtime.GrainId Target { get { throw null; } init { } }
    }
}

namespace Orleans.Hosting
{
    public static partial class DurableJobsExtensions
    {
        public static void AddDurableJobs(this Microsoft.Extensions.DependencyInjection.IServiceCollection services) { }

        public static ISiloBuilder AddDurableJobs(this ISiloBuilder builder) { throw null; }

        public static ISiloBuilder UseInMemoryDurableJobs(this ISiloBuilder builder) { throw null; }
    }

    public sealed partial class DurableJobsOptions
    {
        public bool ConcurrencySlowStartEnabled { get { throw null; } set { } }

        public int MaxAdoptedCount { get { throw null; } set { } }

        public int MaxConcurrentJobsPerSilo { get { throw null; } set { } }

        public System.TimeSpan OverloadBackoffDelay { get { throw null; } set { } }

        public System.TimeSpan ShardActivationBufferPeriod { get { throw null; } set { } }

        public int ShardClaimInitialBudget { get { throw null; } set { } }

        public int ShardClaimMaxBudget { get { throw null; } set { } }

        public System.TimeSpan ShardClaimRampUpDuration { get { throw null; } set { } }

        public System.TimeSpan ShardDuration { get { throw null; } set { } }

        public System.Func<DurableJobs.IJobRunContext, System.Exception, System.DateTimeOffset?> ShouldRetry { get { throw null; } set { } }

        public int SlowStartInitialConcurrency { get { throw null; } set { } }

        public System.TimeSpan SlowStartInterval { get { throw null; } set { } }
    }

    public sealed partial class DurableJobsOptionsValidator : IConfigurationValidator
    {
        public DurableJobsOptionsValidator(Microsoft.Extensions.Logging.ILogger<DurableJobsOptionsValidator> logger, Microsoft.Extensions.Options.IOptions<DurableJobsOptions> options) { }

        public void ValidateConfiguration() { }
    }
}

namespace OrleansCodeGen.Orleans.DurableJobs
{
    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_DurableJob : global::Orleans.Serialization.Codecs.IFieldCodec<global::Orleans.DurableJobs.DurableJob>, global::Orleans.Serialization.Codecs.IFieldCodec
    {
        public Codec_DurableJob(global::Orleans.Serialization.Activators.IActivator<global::Orleans.DurableJobs.DurableJob> _activator, global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public void Deserialize<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.DurableJobs.DurableJob instance) { }

        public global::Orleans.DurableJobs.DurableJob ReadValue<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, global::Orleans.DurableJobs.DurableJob instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, global::Orleans.DurableJobs.DurableJob value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_DurableJobRunResult : global::Orleans.Serialization.Codecs.IFieldCodec<global::Orleans.DurableJobs.DurableJobRunResult>, global::Orleans.Serialization.Codecs.IFieldCodec
    {
        public Codec_DurableJobRunResult(global::Orleans.Serialization.Activators.IActivator<global::Orleans.DurableJobs.DurableJobRunResult> _activator, global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public void Deserialize<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.DurableJobs.DurableJobRunResult instance) { }

        public global::Orleans.DurableJobs.DurableJobRunResult ReadValue<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, global::Orleans.DurableJobs.DurableJobRunResult instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, global::Orleans.DurableJobs.DurableJobRunResult value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_Invokable_ILocalDurableJobManager_GrainReference_60887CAF : global::Orleans.Serialization.Codecs.IFieldCodec<Invokable_ILocalDurableJobManager_GrainReference_60887CAF>, global::Orleans.Serialization.Codecs.IFieldCodec
    {
        public Codec_Invokable_ILocalDurableJobManager_GrainReference_60887CAF(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public void Deserialize<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, Invokable_ILocalDurableJobManager_GrainReference_60887CAF instance) { }

        public Invokable_ILocalDurableJobManager_GrainReference_60887CAF ReadValue<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, Invokable_ILocalDurableJobManager_GrainReference_60887CAF instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, Invokable_ILocalDurableJobManager_GrainReference_60887CAF value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_Invokable_ILocalDurableJobManager_GrainReference_9A773386 : global::Orleans.Serialization.Codecs.IFieldCodec<Invokable_ILocalDurableJobManager_GrainReference_9A773386>, global::Orleans.Serialization.Codecs.IFieldCodec
    {
        public Codec_Invokable_ILocalDurableJobManager_GrainReference_9A773386(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public void Deserialize<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, Invokable_ILocalDurableJobManager_GrainReference_9A773386 instance) { }

        public Invokable_ILocalDurableJobManager_GrainReference_9A773386 ReadValue<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, Invokable_ILocalDurableJobManager_GrainReference_9A773386 instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, Invokable_ILocalDurableJobManager_GrainReference_9A773386 value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_DurableJob : global::Orleans.Serialization.Cloning.IDeepCopier<global::Orleans.DurableJobs.DurableJob>, global::Orleans.Serialization.Cloning.IDeepCopier
    {
        public Copier_DurableJob(global::Orleans.Serialization.Activators.IActivator<global::Orleans.DurableJobs.DurableJob> _activator, global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public global::Orleans.DurableJobs.DurableJob DeepCopy(global::Orleans.DurableJobs.DurableJob original, global::Orleans.Serialization.Cloning.CopyContext context) { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_DurableJobRunResult : global::Orleans.Serialization.Cloning.IDeepCopier<global::Orleans.DurableJobs.DurableJobRunResult>, global::Orleans.Serialization.Cloning.IDeepCopier
    {
        public Copier_DurableJobRunResult(global::Orleans.Serialization.Activators.IActivator<global::Orleans.DurableJobs.DurableJobRunResult> _activator) { }

        public global::Orleans.DurableJobs.DurableJobRunResult DeepCopy(global::Orleans.DurableJobs.DurableJobRunResult original, global::Orleans.Serialization.Cloning.CopyContext context) { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_Invokable_ILocalDurableJobManager_GrainReference_60887CAF : global::Orleans.Serialization.Cloning.IDeepCopier<Invokable_ILocalDurableJobManager_GrainReference_60887CAF>, global::Orleans.Serialization.Cloning.IDeepCopier
    {
        public Copier_Invokable_ILocalDurableJobManager_GrainReference_60887CAF(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public Invokable_ILocalDurableJobManager_GrainReference_60887CAF DeepCopy(Invokable_ILocalDurableJobManager_GrainReference_60887CAF original, global::Orleans.Serialization.Cloning.CopyContext context) { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_Invokable_ILocalDurableJobManager_GrainReference_9A773386 : global::Orleans.Serialization.Cloning.IDeepCopier<Invokable_ILocalDurableJobManager_GrainReference_9A773386>, global::Orleans.Serialization.Cloning.IDeepCopier
    {
        public Copier_Invokable_ILocalDurableJobManager_GrainReference_9A773386(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public Invokable_ILocalDurableJobManager_GrainReference_9A773386 DeepCopy(Invokable_ILocalDurableJobManager_GrainReference_9A773386 original, global::Orleans.Serialization.Cloning.CopyContext context) { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::Orleans.CompoundTypeAlias(new[] { "inv", typeof(global::Orleans.Runtime.GrainReference), typeof(global::Orleans.DurableJobs.ILocalDurableJobManager), "60887CAF" })]
    public sealed partial class Invokable_ILocalDurableJobManager_GrainReference_60887CAF : global::Orleans.Runtime.TaskRequest<bool>
    {
        public global::Orleans.DurableJobs.DurableJob arg0;
        public System.Threading.CancellationToken arg1;
        public override bool IsCancellable { get { throw null; } }

        public override void Dispose() { }

        public override string GetActivityName() { throw null; }

        public override object GetArgument(int index) { throw null; }

        public override int GetArgumentCount() { throw null; }

        public override System.Threading.CancellationToken GetCancellationToken() { throw null; }

        public override string GetInterfaceName() { throw null; }

        public override System.Type GetInterfaceType() { throw null; }

        public override System.Reflection.MethodInfo GetMethod() { throw null; }

        public override string GetMethodName() { throw null; }

        public override object GetTarget() { throw null; }

        protected override System.Threading.Tasks.Task<bool> InvokeInner() { throw null; }

        public override void SetArgument(int index, object value) { }

        public override void SetTarget(global::Orleans.Serialization.Invocation.ITargetHolder holder) { }

        public override bool TryCancel() { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::Orleans.CompoundTypeAlias(new[] { "inv", typeof(global::Orleans.Runtime.GrainReference), typeof(global::Orleans.DurableJobs.ILocalDurableJobManager), "9A773386" })]
    public sealed partial class Invokable_ILocalDurableJobManager_GrainReference_9A773386 : global::Orleans.Runtime.TaskRequest<global::Orleans.DurableJobs.DurableJob>
    {
        public global::Orleans.DurableJobs.ScheduleJobRequest arg0;
        public System.Threading.CancellationToken arg1;
        public override bool IsCancellable { get { throw null; } }

        public override void Dispose() { }

        public override string GetActivityName() { throw null; }

        public override object GetArgument(int index) { throw null; }

        public override int GetArgumentCount() { throw null; }

        public override System.Threading.CancellationToken GetCancellationToken() { throw null; }

        public override string GetInterfaceName() { throw null; }

        public override System.Type GetInterfaceType() { throw null; }

        public override System.Reflection.MethodInfo GetMethod() { throw null; }

        public override string GetMethodName() { throw null; }

        public override object GetTarget() { throw null; }

        protected override System.Threading.Tasks.Task<global::Orleans.DurableJobs.DurableJob> InvokeInner() { throw null; }

        public override void SetArgument(int index, object value) { }

        public override void SetTarget(global::Orleans.Serialization.Invocation.ITargetHolder holder) { }

        public override bool TryCancel() { throw null; }
    }
}