<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <SourceRoot>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\..\..\..\..\..\..\..\..\'))</SourceRoot>
    <OrleansBuildTimeCodeGen>true</OrleansBuildTimeCodeGen>
    <OrleansHotReload>true</OrleansHotReload>
    <IsOrleansFrameworkPart>false</IsOrleansFrameworkPart>
    <IsAotCompatible>true</IsAotCompatible>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)src\Orleans.Serialization\Orleans.Serialization.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
  </ItemGroup>
</Project>
