//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Orleans.AdvancedReminders.AdoNet
{
    public partial class AdoNetReminderTableOptions
    {
        [Redact]
        public string ConnectionString { get { throw null; } set { } }

        public string Invariant { get { throw null; } set { } }
    }

    public partial class AdoNetReminderTableOptionsValidator : IConfigurationValidator
    {
        public AdoNetReminderTableOptionsValidator(Microsoft.Extensions.Options.IOptions<AdoNetReminderTableOptions> options) { }

        public void ValidateConfiguration() { }
    }
}

namespace Orleans.Hosting
{
    public static partial class SiloBuilderReminderExtensions
    {
        public static Microsoft.Extensions.DependencyInjection.IServiceCollection UseAdoNetAdvancedReminderService(this Microsoft.Extensions.DependencyInjection.IServiceCollection services, System.Action<Microsoft.Extensions.Options.OptionsBuilder<AdvancedReminders.AdoNet.AdoNetReminderTableOptions>> configureOptions) { throw null; }

        public static ISiloBuilder UseAdoNetAdvancedReminderService(this ISiloBuilder builder, System.Action<Microsoft.Extensions.Options.OptionsBuilder<AdvancedReminders.AdoNet.AdoNetReminderTableOptions>> configureOptions) { throw null; }

        public static ISiloBuilder UseAdoNetAdvancedReminderService(this ISiloBuilder builder, System.Action<AdvancedReminders.AdoNet.AdoNetReminderTableOptions> configureOptions) { throw null; }
    }
}