// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orleans.Persistence.EntityFrameworkCore.MySql.Data;

#nullable disable

namespace Orleans.Persistence.EntityFrameworkCore.MySql.Data.Migrations
{
    [DbContext(typeof(MySqlGrainStateDbContext))]
    [Migration("20260811210104_InitialPersistenceSchema")]
    partial class InitialPersistenceSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Orleans.Persistence.EntityFrameworkCore.Data.GrainStateRecord<System.Guid>", b =>
                {
                    b.Property<string>("ServiceId")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("GrainType")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("StateType")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("GrainId")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<byte[]>("Data")
                        .HasColumnType("longblob");

                    b.Property<Guid>("ETag")
                        .IsConcurrencyToken()
                        .HasColumnType("char(36)");

                    b.HasKey("ServiceId", "GrainType", "StateType", "GrainId");

                    b.ToTable("GrainState");
                });
#pragma warning restore 612, 618
        }
    }
}
