<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Aspire.Azure.Storage.Blobs" Version="13.2.4" />
    <PackageVersion Include="Aspire.Hosting.AppHost" Version="13.2.4" />
    <PackageVersion Include="Aspire.Hosting.Azure.Storage" Version="13.2.4" />
    <PackageVersion Include="Aspire.Hosting.Orleans" Version="13.2.4" />
    <PackageVersion Include="Aspire.Hosting.Redis" Version="13.2.4" />
    <PackageVersion Include="Aspire.StackExchange.Redis" Version="13.2.4" />
    <PackageVersion Include="Azure.Storage.Blobs" Version="12.27.0" />
    <PackageVersion Include="MessagePack" Version="3.1.7" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageVersion Include="Microsoft.Orleans.Clustering.Redis" Version="10.2.2" />
    <PackageVersion Include="Microsoft.Orleans.DurableJobs.AzureStorage" Version="10.2.2-alpha.1" />
    <PackageVersion Include="Microsoft.Orleans.DurableTasks" Version="10.2.2-alpha.1" />
    <PackageVersion Include="Microsoft.Orleans.Journaling" Version="10.2.2-rc.2.alpha.1" />
    <PackageVersion Include="Microsoft.Orleans.Journaling.AzureStorage" Version="10.2.2-rc.2.alpha.1" />
    <PackageVersion Include="Microsoft.Orleans.Server" Version="10.2.2" />
    <PackageVersion Include="Microsoft.Orleans.TestingHost" Version="10.2.2" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>
