<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OrleansBuildTimeCodeGen>true</OrleansBuildTimeCodeGen>
    <TargetFrameworks>$(TestTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>

  <ItemGroup>
    <!-- due to Verify.XunitV3 requiring newer versions of these libraries -->
    <PackageReference Include="System.IO.Hashing" />
    <PackageReference Include="System.CodeDom" />
    <PackageReference Include="Verify.XunitV3" />
    <Compile Remove="snapshots\**\*" />
    <None Include="snapshots\**\*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Orleans.CodeGenerator\Orleans.CodeGenerator.csproj" />
    <ProjectReference Include="..\..\src\Orleans.Sdk\Orleans.Sdk.csproj" />
    <ProjectReference Include="..\..\src\Orleans.Runtime\Orleans.Runtime.csproj" />
    <ProjectReference Include="..\..\src\Orleans.Serialization.FSharp\Orleans.Serialization.FSharp.csproj" />
    <ProjectReference Include="..\Orleans.Runtime.Tests\Orleans.Runtime.Tests.csproj" />
  </ItemGroup>



</Project>
