<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OrleansBuildTimeCodeGen>true</OrleansBuildTimeCodeGen>
    <TargetFrameworks>$(TestTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
    <PackageReference Include="Microsoft.Testing.Platform.MSBuild" />
  </ItemGroup>

  <ItemGroup>
    <!-- due to Verify.XunitV3 requiring newer versions of these libraries -->
    <Compile Include="..\Orleans.NativeAotSmoke\Contexts.Contracts.cs" Link="Contexts.Contracts.cs" />
    <Compile Include="..\Orleans.NativeAotSmoke\Factories.Contracts.cs" Link="Factories.Contracts.cs" />
    <Compile Include="..\Orleans.NativeAotSmoke\Factories.Review.cs" Link="Factories.Review.cs" />
    <PackageReference Include="System.IO.Hashing" />
    <PackageReference Include="System.CodeDom" />
    <PackageReference Include="Verify.XunitV3" />
    <Compile Remove="snapshots\**\*" />
    <None Include="snapshots\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Orleans.NativeAotSmoke\FieldsPayloads.cs" Link="FieldAccess\Payloads.cs" />
    <Compile Include="..\Orleans.NativeAotSmoke\FieldsChecks.cs" Link="FieldAccess\FieldAccessChecks.cs" />
    <ProjectReference Include="..\..\src\Orleans.CodeGenerator\Orleans.CodeGenerator.csproj" />
    <ProjectReference Include="..\..\src\Orleans.Sdk\Orleans.Sdk.csproj" />
    <ProjectReference Include="..\..\src\Orleans.Runtime\Orleans.Runtime.csproj" />
    <ProjectReference Include="..\..\src\Orleans.Serialization.FSharp\Orleans.Serialization.FSharp.csproj" />
    <ProjectReference Include="..\Orleans.Runtime.Tests\Orleans.Runtime.Tests.csproj" />
    <ProjectReference Include="..\..\docs\site\src\content\docs\host\configuration-guide\snippets\serializer-contexts\SerializerContexts.csproj"
                      Condition="'$(TargetFramework)' == 'net10.0'" />
  </ItemGroup>



</Project>
