<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <OrleansVersion>__ORLEANS_VERSION__</OrleansVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Orleans.Client" Version="$(OrleansVersion)" />
    <PackageVersion Include="Microsoft.Orleans.Sdk" Version="$(OrleansVersion)" />
    <PackageVersion Include="Microsoft.Orleans.Server" Version="$(OrleansVersion)" />
  </ItemGroup>
</Project>
