// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Orleans.Clustering.EntityFrameworkCore.PostgreSQL.Data;

#nullable disable

namespace Orleans.Clustering.EntityFrameworkCore.PostgreSQL.Data.Migrations
{
    [DbContext(typeof(PostgreSqlClusterDbContext))]
    [Migration("20260811154956_InitialClusteringSchema")]
    partial class InitialClusteringSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Orleans.Clustering.EntityFrameworkCore.Data.ClusterRecord<System.Guid>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<Guid>("ETag")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Clusters");
                });

            modelBuilder.Entity("Orleans.Clustering.EntityFrameworkCore.Data.SiloRecord<System.Guid>", b =>
                {
                    b.Property<string>("ClusterId")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<int>("Generation")
                        .HasColumnType("integer");

                    b.Property<Guid>("ETag")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset>("IAmAliveTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("ProxyPort")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SuspectingSilos")
                        .HasColumnType("text");

                    b.Property<string>("SuspectingTimes")
                        .HasColumnType("text");

                    b.HasKey("ClusterId", "Address", "Port", "Generation");

                    b.HasIndex("ClusterId");

                    b.HasIndex("ClusterId", "Status");

                    b.HasIndex("ClusterId", "Status", "IAmAliveTime");

                    b.ToTable("Silos");
                });

            modelBuilder.Entity("Orleans.Clustering.EntityFrameworkCore.Data.SiloRecord<System.Guid>", b =>
                {
                    b.HasOne("Orleans.Clustering.EntityFrameworkCore.Data.ClusterRecord<System.Guid>", "Cluster")
                        .WithMany("Silos")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("Orleans.Clustering.EntityFrameworkCore.Data.ClusterRecord<System.Guid>", b =>
                {
                    b.Navigation("Silos");
                });
#pragma warning restore 612, 618
        }
    }
}
