## Service definition ##
application:
  schemaVersion: 1.0.0-preview1
  name: VotingApp
  properties:
    services:
      - name: VotingData
        properties:
          description: VotingData description.
          osType: Windows
          codePackages:
            - name: VotingData
              image: votingdata:dev
              endpoints:
                - name: SiloPort
                  port: 30001
                - name: GatewayPort
                  port: 30002
              environmentVariables:
                - name: CLUSTERING_CONNECTION_STRING
                  value: "Replace this with an Azure Storage Connection String"
                - name: PERSISTENCE_CONNECTION_STRING
                  value: "Replace this with an Azure Storage Connection String"
              resources:
                requests:
                  cpu: 0.5
                  memoryInGB: 1
          replicaCount: 1
          networkRefs:
            - name: VotingAppNetwork