<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)src\Orleans.Server\Orleans.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChatRoom.Common\ChatRoom.Common.csproj" />
  </ItemGroup>

</Project>
