// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1024:Compare symbols correctly", Justification = "<Pending>", Scope = "member", Target = "~F:Orleans.CodeGenerator.Analysis.CompilationAnalyzer.AssembliesExcludedFromCodeGeneration")]
[assembly: SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1024:Compare symbols correctly", Justification = "<Pending>", Scope = "member", Target = "~F:Orleans.CodeGenerator.Analysis.CompilationAnalyzer.AssembliesExcludedFromMetadataGeneration")]
[assembly: SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1024:Compare symbols correctly", Justification = "<Pending>", Scope = "member", Target = "~F:Orleans.CodeGenerator.Analysis.CompilationAnalyzer.assembliesWithForcedSerializability")]
[assembly: SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1024:Compare symbols correctly", Justification = "<Pending>", Scope = "member", Target = "~F:Orleans.CodeGenerator.Analysis.CompilationAnalyzer.dependencyTypes")]
[assembly: SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1024:Compare symbols correctly", Justification = "<Pending>", Scope = "member", Target = "~F:Orleans.CodeGenerator.Analysis.CompilationAnalyzer.fieldOfSerializableType")]
[assembly: SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1024:Compare symbols correctly", Justification = "<Pending>", Scope = "member", Target = "~F:Orleans.CodeGenerator.Analysis.CompilationAnalyzer.grainClassesToProcess")]
[assembly: SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1024:Compare symbols correctly", Justification = "<Pending>", Scope = "member", Target = "~F:Orleans.CodeGenerator.Analysis.CompilationAnalyzer.grainInterfacesToProcess")]
[assembly: SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1024:Compare symbols correctly", Justification = "<Pending>", Scope = "member", Target = "~F:Orleans.CodeGenerator.Analysis.CompilationAnalyzer.knownBaseTypes")]
[assembly: SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1024:Compare symbols correctly", Justification = "<Pending>", Scope = "member", Target = "~F:Orleans.CodeGenerator.Analysis.CompilationAnalyzer.ReferencedAssemblies")]
[assembly: SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1024:Compare symbols correctly", Justification = "<Pending>", Scope = "member", Target = "~F:Orleans.CodeGenerator.Analysis.CompilationAnalyzer.serializationTypesToProcess")]
[assembly: SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1024:Compare symbols correctly", Justification = "<Pending>", Scope = "member", Target = "~M:Orleans.CodeGenerator.Analysis.CompilationAnalyzer.ExpandType(Microsoft.CodeAnalysis.ITypeSymbol)~System.Collections.Generic.IEnumerable{Microsoft.CodeAnalysis.ITypeSymbol}")]
[assembly: SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1024:Compare symbols correctly", Justification = "<Pending>", Scope = "member", Target = "~M:Orleans.CodeGenerator.Analysis.CompilationAnalyzer.GetSerializationTypesToProcess~System.Collections.Generic.IEnumerable{Microsoft.CodeAnalysis.INamedTypeSymbol}")]
[assembly: SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1024:Compare symbols correctly", Justification = "<Pending>", Scope = "member", Target = "~M:Orleans.CodeGenerator.CodeGenerator.GenerateSyntax(Orleans.CodeGenerator.Model.AggregatedModel,System.Threading.CancellationToken)~Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax")]
[assembly: SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1024:Compare symbols correctly", Justification = "<Pending>", Scope = "member", Target = "~M:Orleans.CodeGenerator.Generators.GrainMethodInvokerGenerator.GenerateGenericInvokerFields(Orleans.CodeGenerator.WellKnownTypes,System.Collections.Generic.List{Orleans.CodeGenerator.Model.GrainMethodDescription})~System.Collections.Generic.Dictionary{Microsoft.CodeAnalysis.IMethodSymbol,Orleans.CodeGenerator.Generators.GrainMethodInvokerGenerator.GenericInvokerField}")]
[assembly: SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1024:Compare symbols correctly", Justification = "<Pending>", Scope = "member", Target = "~P:Orleans.CodeGenerator.Analysis.CompilationAnalyzer.CodeGenerationRequiredTypes")]
[assembly: SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1024:Compare symbols correctly", Justification = "<Pending>", Scope = "member", Target = "~P:Orleans.CodeGenerator.Analysis.CompilationAnalyzer.KnownAssemblies")]
[assembly: SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1024:Compare symbols correctly", Justification = "<Pending>", Scope = "member", Target = "~P:Orleans.CodeGenerator.Analysis.CompilationAnalyzer.KnownTypes")]
[assembly: SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1024:Compare symbols correctly", Justification = "<Pending>", Scope = "member", Target = "~F:Orleans.CodeGenerator.Generators.SerializerGenerator.ShallowCopyableTypes")]
