using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Orleans.CodeGenerator.Diagnostics;
using Orleans.CodeGenerator.SyntaxGeneration;

namespace Orleans.CodeGenerator;

internal static class SerializerContextGenerator
{
    private static readonly DiagnosticDescriptor InvalidContext = new(
        DiagnosticRuleId.InvalidSerializerContext, "Invalid serializer context",
        "Serializer context '{0}' must be a non-generic, top-level partial class directly derived from Orleans.Serialization.SerializerContext",
        "Usage", DiagnosticSeverity.Error, isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor UnsupportedType = new(
        DiagnosticRuleId.UnsupportedSerializerContextType, "Unsupported serializer context dependency",
        "Serializer context '{0}' cannot register '{1}': {2}",
        "Usage", DiagnosticSeverity.Error, isEnabledByDefault: true);

    internal static ImmutableArray<SourceOutputResult> Generate(
        GeneratorAttributeSyntaxContext context, SourceGeneratorOptions options, CancellationToken cancellationToken)
    {
        var symbol = (INamedTypeSymbol)context.TargetSymbol;
        var location = symbol.Locations.FirstOrDefault();
        if (symbol.IsFileLocal || symbol.IsGenericType || symbol.ContainingType is not null
            || symbol.BaseType?.ToDisplayString() != "Orleans.Serialization.SerializerContext"
            || symbol.IsAbstract || symbol.IsStatic
            || symbol.DeclaringSyntaxReferences.Any(reference =>
                reference.GetSyntax(cancellationToken) is not ClassDeclarationSyntax declaration
                || !declaration.Modifiers.Any(SyntaxKind.PartialKeyword)))
        {
            return [SourceOutputResult.FromDiagnostic(Diagnostic.Create(InvalidContext, location, symbol.Name))];
        }

        var roots = new List<ITypeSymbol>();
        foreach (var attribute in symbol.GetAttributes().Where(attribute =>
            attribute.AttributeClass?.ToDisplayString() == "Orleans.GenerateSerializerContextAttribute"))
        {
            if (attribute.ConstructorArguments.FirstOrDefault().Value is ITypeSymbol type)
            {
                roots.Add(type);
            }
            else
            {
                return Error(symbol, location, "<null>", "specify a closed root type");
            }
        }

        var compilation = context.SemanticModel.Compilation;
        var services = new GeneratorServices(compilation, SourceGeneratorOptionsParser.CreateCodeGeneratorOptions(options));
        if (!SerializerFactoryGenerator.TryCreate(services, roots, cancellationToken, out var graph, out var failure))
        {
            return Error(symbol, location, failure.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), failure.Reason);
        }

        var result = new StringBuilder();
        result.AppendLine("// <auto-generated/>");
        result.AppendLine("#nullable enable");
        if (!symbol.ContainingNamespace.IsGlobalNamespace)
            result.Append("namespace ").Append(symbol.ContainingNamespace.ToDisplayString()).AppendLine(";");
        result.Append("partial class ").Append(symbol.Name.EscapeIdentifier()).AppendLine(" {");
        result.AppendLine("protected override void ConfigureInner(global::Orleans.Serialization.Configuration.TypeManifestOptions options) {");
        result.Append(graph.ConfigurationStatements);
        result.AppendLine("} }");
        var source = SyntaxFactory.ParseCompilationUnit(result.ToString()).NormalizeWhitespace().ToFullString();
        return [SourceOutputResult.FromSource(new GeneratedSourceEntry(
            $"{compilation.AssemblyName}.orleans.context.{symbol.ToDisplayString()}.g.cs", source))];
    }

    private static ImmutableArray<SourceOutputResult> Error(INamedTypeSymbol context, Location? location, string type, string reason)
        => [SourceOutputResult.FromDiagnostic(Diagnostic.Create(UnsupportedType, location, context.Name, type, reason))];
}
