<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>52a3faed-883d-4abe-ac8f-ee35bbe2f40a</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>

	<ItemGroup>
		<Protobuf Include="Protos\externalscaler.proto" GrpcServices="Server" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="$(SourceRoot)src\Azure\Orleans.Clustering.AzureStorage\Orleans.Clustering.AzureStorage.csproj" />
		<ProjectReference Include="$(SourceRoot)src\Orleans.Server\Orleans.Server.csproj" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
		<PackageReference Include="Grpc.AspNetCore" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
	</ItemGroup>

</Project>
