//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Orleans.Hosting
{
    public static partial class FirestoreReminderServiceExtensions
    {
        public static Microsoft.Extensions.DependencyInjection.IServiceCollection UseFirestoreReminderService(this Microsoft.Extensions.DependencyInjection.IServiceCollection services, System.Action<Microsoft.Extensions.Options.OptionsBuilder<Reminders.Firestore.FirestoreOptions>> configureOptions) { throw null; }

        public static Microsoft.Extensions.DependencyInjection.IServiceCollection UseFirestoreReminderService(this Microsoft.Extensions.DependencyInjection.IServiceCollection services, System.Action<Reminders.Firestore.FirestoreOptions> configure) { throw null; }

        public static ISiloBuilder UseFirestoreReminderService(this ISiloBuilder builder, System.Action<Microsoft.Extensions.Options.OptionsBuilder<Reminders.Firestore.FirestoreOptions>> configureOptions) { throw null; }

        public static ISiloBuilder UseFirestoreReminderService(this ISiloBuilder builder, System.Action<Reminders.Firestore.FirestoreOptions> configure) { throw null; }
    }
}

namespace Orleans.Reminders.Firestore
{
    public partial class FirestoreOptions
    {
        public string? EmulatorHost { get { throw null; } set { } }

        public string ProjectId { get { throw null; } set { } }

        public string RootCollectionName { get { throw null; } set { } }
    }
}