<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <OrleansVersion>__ORLEANS_VERSION__</OrleansVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.Orleans.Server" Version="$(OrleansVersion)" />
  </ItemGroup>
</Project>
