//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrleansManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrleansManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum age of an activation. Activations that are older than the age limit will be collected. .
        /// </summary>
        internal static string AgeLimitParameter {
            get {
                return ResourceManager.GetString("AgeLimitParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling GetDetailedGrainReport({0}, {1}).
        /// </summary>
        internal static string CallingGetDetailedGrainReport {
            get {
                return ResourceManager.GetString("CallingGetDetailedGrainReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forcing Activation Collection.
        /// </summary>
        internal static string ForcingActivationCollection {
            get {
                return ResourceManager.GetString("ForcingActivationCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forcing Garbage Collection.
        /// </summary>
        internal static string ForcingGarbageCollection {
            get {
                return ResourceManager.GetString("ForcingGarbageCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Grain Id is {0}.
        /// </summary>
        internal static string FullGrainId {
            get {
                return ResourceManager.GetString("FullGrainId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway Error.
        /// </summary>
        internal static string GatewayError {
            get {
                return ResourceManager.GetString("GatewayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No gateway was found..
        /// </summary>
        internal static string GatewayNotFound {
            get {
                return ResourceManager.GetString("GatewayNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Error.
        /// </summary>
        internal static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting management grain.
        /// </summary>
        internal static string GettingManagementGrain {
            get {
                return ResourceManager.GetString("GettingManagementGrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting statistics from management grain.
        /// </summary>
        internal static string GettingStatistics {
            get {
                return ResourceManager.GetString("GettingStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either GrainIdGuid or GrainId must be set..
        /// </summary>
        internal static string GrainIdRequired {
            get {
                return ResourceManager.GetString("GrainIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grain-Id Unknown.
        /// </summary>
        internal static string GrainIdUnknown {
            get {
                return ResourceManager.GetString("GrainIdUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup of grain {1} in silo {0}.
        /// </summary>
        internal static string GrainInSiloLookup {
            get {
                return ResourceManager.GetString("GrainInSiloLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing silo addresses.
        /// </summary>
        internal static string ParsingSiloAddresses {
            get {
                return ResourceManager.GetString("ParsingSiloAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The addresses of the silos..
        /// </summary>
        internal static string SiloAddressesParameter {
            get {
                return ResourceManager.GetString("SiloAddressesParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either InterfaceTypeCode or ImplementationClassName must be set..
        /// </summary>
        internal static string TypeCodeRequired {
            get {
                return ResourceManager.GetString("TypeCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Code Unknown.
        /// </summary>
        internal static string TypeCodeUnknown {
            get {
                return ResourceManager.GetString("TypeCodeUnknown", resourceCulture);
            }
        }
    }
}
