<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(TestTargetFrameworks)</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Orleans.Persistence.TestKit\Orleans.Persistence.TestKit.csproj" PrivateAssets="all" />
    <ProjectReference Include="..\..\src\Orleans.Persistence.Memory\Orleans.Persistence.Memory.csproj" />
    <ProjectReference Include="..\TestInfrastructure\TestExtensions\TestExtensions.csproj" />
  </ItemGroup>

</Project>
