using Orleans.TestingHost;

namespace Tester
{
    public static class Program 
    {
        public static async Task<int> Main(string[] args)
        {
            if (args.Length == 0 || !int.TryParse(args[0], out _))
            {
                return global::Orleans.Runtime.Tests.AutoGenerated.XunitAutoGeneratedEntryPoint.Main(args);
            }

            await StandaloneSiloHost.Main(args);
            return 0;
        }
    }
}
