//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Orleans.Journaling
{
    public abstract partial class DurableGrain : Grain, IGrainBase
    {
        protected IStateMachineManager StateMachineManager { get { throw null; } }

        protected TStateMachine GetOrCreateStateMachine<TStateMachine>(string name)
            where TStateMachine : class, IDurableStateMachine { throw null; }

        protected TStateMachine GetOrCreateStateMachine<TState, TStateMachine>(string name, System.Func<TState, TStateMachine> createStateMachine, TState state)
            where TStateMachine : class, IDurableStateMachine { throw null; }

        protected System.Threading.Tasks.ValueTask WriteStateAsync(System.Threading.CancellationToken cancellationToken = default) { throw null; }
    }

    [GenerateSerializer]
    [Immutable]
    public readonly partial struct DurableTaskCompletionSourceState<T>
    {
        private readonly T? _Value_k__BackingField;
        private readonly object _dummy;
        private readonly int _dummyPrimitive;
        [Id(2)]
        public System.Exception? Exception { get { throw null; } init { } }

        [Id(0)]
        public DurableTaskCompletionSourceStatus Status { get { throw null; } init { } }

        [Id(1)]
        public T? Value { get { throw null; } init { } }
    }

    [GenerateSerializer]
    public enum DurableTaskCompletionSourceStatus : byte
    {
        Pending = 0,
        Completed = 1,
        Faulted = 2,
        Canceled = 3
    }

    public static partial class HostingExtensions
    {
        public static Hosting.ISiloBuilder AddStateMachineStorage(this Hosting.ISiloBuilder builder) { throw null; }
    }

    public partial interface IDurableDictionaryCodecProvider
    {
        IDurableDictionaryCodec<TKey, TValue> GetCodec<TKey, TValue>();
    }

    public partial interface IDurableDictionaryCodec<TKey, TValue>
    {
        void Apply(System.Buffers.ReadOnlySequence<byte> input, IDurableDictionaryLogEntryConsumer<TKey, TValue> consumer);
        void WriteClear(System.Buffers.IBufferWriter<byte> output);
        void WriteRemove(TKey key, System.Buffers.IBufferWriter<byte> output);
        void WriteSet(TKey key, TValue value, System.Buffers.IBufferWriter<byte> output);
        void WriteSnapshot(System.Collections.Generic.IReadOnlyCollection<System.Collections.Generic.KeyValuePair<TKey, TValue>> items, System.Buffers.IBufferWriter<byte> output);
    }

    public partial interface IDurableDictionaryLogEntryConsumer<TKey, TValue>
    {
        void ApplyClear();
        void ApplyRemove(TKey key);
        void ApplySet(TKey key, TValue value);
        void ApplySnapshotItem(TKey key, TValue value);
        void ApplySnapshotStart(int count);
    }

    public partial interface IDurableDictionary<K, V> : System.Collections.Generic.IDictionary<K, V>, System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<K, V>>, System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<K, V>>, System.Collections.IEnumerable
    {
    }

    public partial interface IDurableListCodecProvider
    {
        IDurableListCodec<T> GetCodec<T>();
    }

    public partial interface IDurableListCodec<T>
    {
        void Apply(System.Buffers.ReadOnlySequence<byte> input, IDurableListLogEntryConsumer<T> consumer);
        void WriteAdd(T item, System.Buffers.IBufferWriter<byte> output);
        void WriteClear(System.Buffers.IBufferWriter<byte> output);
        void WriteInsert(int index, T item, System.Buffers.IBufferWriter<byte> output);
        void WriteRemoveAt(int index, System.Buffers.IBufferWriter<byte> output);
        void WriteSet(int index, T item, System.Buffers.IBufferWriter<byte> output);
        void WriteSnapshot(System.Collections.Generic.IReadOnlyCollection<T> items, System.Buffers.IBufferWriter<byte> output);
    }

    public partial interface IDurableListLogEntryConsumer<T>
    {
        void ApplyAdd(T item);
        void ApplyClear();
        void ApplyInsert(int index, T item);
        void ApplyRemoveAt(int index);
        void ApplySet(int index, T item);
        void ApplySnapshotItem(T item);
        void ApplySnapshotStart(int count);
    }

    public partial interface IDurableList<T> : System.Collections.Generic.IList<T>, System.Collections.Generic.ICollection<T>, System.Collections.Generic.IEnumerable<T>, System.Collections.IEnumerable
    {
        void AddRange(System.Collections.Generic.IEnumerable<T> collection);
        System.Collections.ObjectModel.ReadOnlyCollection<T> AsReadOnly();
    }

    public partial interface IDurableNothing
    {
    }

    public partial interface IDurableQueueCodecProvider
    {
        IDurableQueueCodec<T> GetCodec<T>();
    }

    public partial interface IDurableQueueCodec<T>
    {
        void Apply(System.Buffers.ReadOnlySequence<byte> input, IDurableQueueLogEntryConsumer<T> consumer);
        void WriteClear(System.Buffers.IBufferWriter<byte> output);
        void WriteDequeue(System.Buffers.IBufferWriter<byte> output);
        void WriteEnqueue(T item, System.Buffers.IBufferWriter<byte> output);
        void WriteSnapshot(System.Collections.Generic.IReadOnlyCollection<T> items, System.Buffers.IBufferWriter<byte> output);
    }

    public partial interface IDurableQueueLogEntryConsumer<T>
    {
        void ApplyClear();
        void ApplyDequeue();
        void ApplyEnqueue(T item);
        void ApplySnapshotItem(T item);
        void ApplySnapshotStart(int count);
    }

    public partial interface IDurableQueue<T> : System.Collections.Generic.IEnumerable<T>, System.Collections.IEnumerable, System.Collections.Generic.IReadOnlyCollection<T>
    {
        void Clear();
        bool Contains(T item);
        void CopyTo(T[] array, int arrayIndex);
        T Dequeue();
        void Enqueue(T item);
        T Peek();
        bool TryDequeue(out T item);
        bool TryPeek(out T item);
    }

    public partial interface IDurableSetCodecProvider
    {
        IDurableSetCodec<T> GetCodec<T>();
    }

    public partial interface IDurableSetCodec<T>
    {
        void Apply(System.Buffers.ReadOnlySequence<byte> input, IDurableSetLogEntryConsumer<T> consumer);
        void WriteAdd(T item, System.Buffers.IBufferWriter<byte> output);
        void WriteClear(System.Buffers.IBufferWriter<byte> output);
        void WriteRemove(T item, System.Buffers.IBufferWriter<byte> output);
        void WriteSnapshot(System.Collections.Generic.IReadOnlyCollection<T> items, System.Buffers.IBufferWriter<byte> output);
    }

    public partial interface IDurableSetLogEntryConsumer<T>
    {
        void ApplyAdd(T item);
        void ApplyClear();
        void ApplyRemove(T item);
        void ApplySnapshotItem(T item);
        void ApplySnapshotStart(int count);
    }

    public partial interface IDurableSet<T> : System.Collections.Generic.ISet<T>, System.Collections.Generic.ICollection<T>, System.Collections.Generic.IEnumerable<T>, System.Collections.IEnumerable, System.Collections.Generic.IReadOnlyCollection<T>, System.Collections.Generic.IReadOnlySet<T>
    {
        int Count { get; }

        bool Add(T item);
        bool Contains(T item);
        bool IsProperSubsetOf(System.Collections.Generic.IEnumerable<T> other);
        bool IsProperSupersetOf(System.Collections.Generic.IEnumerable<T> other);
        bool IsSubsetOf(System.Collections.Generic.IEnumerable<T> other);
        bool IsSupersetOf(System.Collections.Generic.IEnumerable<T> other);
        bool Overlaps(System.Collections.Generic.IEnumerable<T> other);
        bool SetEquals(System.Collections.Generic.IEnumerable<T> other);
    }

    public partial interface IDurableStateCodecProvider
    {
        IDurableStateCodec<T> GetCodec<T>();
    }

    public partial interface IDurableStateCodec<T>
    {
        void Apply(System.Buffers.ReadOnlySequence<byte> input, IDurableStateLogEntryConsumer<T> consumer);
        void WriteClear(System.Buffers.IBufferWriter<byte> output);
        void WriteSet(T state, ulong version, System.Buffers.IBufferWriter<byte> output);
    }

    public partial interface IDurableStateLogEntryConsumer<T>
    {
        void ApplyClear();
        void ApplySet(T state, ulong version);
    }

    public partial interface IDurableStateMachine
    {
        void AppendEntries(StateMachineLogWriter writer);
        void AppendSnapshot(StateMachineLogWriter writer);
        void Apply(System.Buffers.ReadOnlySequence<byte> entry);
        IDurableStateMachine DeepCopy();
        void OnRecoveryCompleted();
        void OnWriteCompleted();
        void Reset(IStateMachineLogWriter storage);
    }

    public partial interface IDurableTaskCompletionSourceCodecProvider
    {
        IDurableTaskCompletionSourceCodec<T> GetCodec<T>();
    }

    public partial interface IDurableTaskCompletionSourceCodec<T>
    {
        void Apply(System.Buffers.ReadOnlySequence<byte> input, IDurableTaskCompletionSourceLogEntryConsumer<T> consumer);
        void WriteCanceled(System.Buffers.IBufferWriter<byte> output);
        void WriteCompleted(T value, System.Buffers.IBufferWriter<byte> output);
        void WriteFaulted(System.Exception exception, System.Buffers.IBufferWriter<byte> output);
        void WritePending(System.Buffers.IBufferWriter<byte> output);
    }

    public partial interface IDurableTaskCompletionSourceLogEntryConsumer<T>
    {
        void ApplyCanceled();
        void ApplyCompleted(T value);
        void ApplyFaulted(System.Exception exception);
        void ApplyPending();
    }

    public partial interface IDurableTaskCompletionSource<T>
    {
        DurableTaskCompletionSourceState<T> State { get; }

        System.Threading.Tasks.Task<T> Task { get; }

        bool TrySetCanceled();
        bool TrySetException(System.Exception exception);
        bool TrySetResult(T value);
    }

    public partial interface IDurableValueCodecProvider
    {
        IDurableValueCodec<T> GetCodec<T>();
    }

    public partial interface IDurableValueCodec<T>
    {
        void Apply(System.Buffers.ReadOnlySequence<byte> input, IDurableValueLogEntryConsumer<T> consumer);
        void WriteSet(T value, System.Buffers.IBufferWriter<byte> output);
    }

    public partial interface IDurableValueLogEntryConsumer<T>
    {
        void ApplySet(T value);
    }

    public partial interface IDurableValue<T>
    {
        T? Value { get; set; }
    }

    public partial interface ILogDataCodec<T>
    {
        T Read(System.Buffers.ReadOnlySequence<byte> input, out long bytesConsumed);
        void Write(T value, System.Buffers.IBufferWriter<byte> output);
    }

    public partial interface IStateMachineLogDataConsumer
    {
        void OnLogData(Serialization.Buffers.ArcBuffer data);
    }

    public partial interface IStateMachineLogEntryConsumer
    {
        void OnEntry(StateMachineId streamId, System.Buffers.ReadOnlySequence<byte> payload);
    }

    public partial interface IStateMachineLogExtentWriter : System.IDisposable
    {
        long Length { get; }

        StateMachineLogWriter CreateLogWriter(StateMachineId streamId);
        Serialization.Buffers.ArcBuffer GetCommittedBuffer();
        void Reset();
    }

    public partial interface IStateMachineLogFormat
    {
        IStateMachineLogExtentWriter CreateWriter();
        void Read(Serialization.Buffers.ArcBuffer input, IStateMachineLogEntryConsumer consumer);
    }

    public partial interface IStateMachineLogWriter
    {
        StateMachineLogEntry BeginEntry();
    }

    public partial interface IStateMachineManager
    {
        System.Threading.Tasks.ValueTask DeleteStateAsync(System.Threading.CancellationToken cancellationToken);
        System.Threading.Tasks.ValueTask InitializeAsync(System.Threading.CancellationToken cancellationToken);
        void RegisterStateMachine(string name, IDurableStateMachine stateMachine);
        bool TryGetStateMachine(string name, out IDurableStateMachine? stateMachine);
        System.Threading.Tasks.ValueTask WriteStateAsync(System.Threading.CancellationToken cancellationToken);
    }

    public partial interface IStateMachineStorage
    {
        bool IsCompactionRequested { get; }

        string LogFormatKey { get; }

        System.Threading.Tasks.ValueTask AppendAsync(Serialization.Buffers.ArcBuffer value, System.Threading.CancellationToken cancellationToken);
        System.Threading.Tasks.ValueTask DeleteAsync(System.Threading.CancellationToken cancellationToken);
        System.Threading.Tasks.ValueTask ReadAsync(IStateMachineLogDataConsumer consumer, System.Threading.CancellationToken cancellationToken);
        System.Threading.Tasks.ValueTask ReplaceAsync(Serialization.Buffers.ArcBuffer value, System.Threading.CancellationToken cancellationToken);
    }

    public partial interface IStateMachineStorageProvider
    {
        IStateMachineStorage Create(Runtime.IGrainContext grainContext);
    }

    public ref partial struct LogEntryReader
    {
        private object _dummy;
        private int _dummyPrimitive;
        public LogEntryReader(System.Buffers.ReadOnlySequence<byte> input) { }

        public long Consumed { get { throw null; } }

        public bool End { get { throw null; } }

        public System.Buffers.ReadOnlySequence<byte> Remaining { get { throw null; } }

        public byte ReadByte() { throw null; }

        public System.Buffers.ReadOnlySequence<byte> ReadBytes(int length) { throw null; }

        public uint ReadVarUInt32() { throw null; }

        public ulong ReadVarUInt64() { throw null; }
    }

    public sealed partial class LogEntryWriter : System.Buffers.IBufferWriter<byte>
    {
        internal LogEntryWriter() { }

        public void Advance(int count) { }

        public System.Memory<byte> GetMemory(int sizeHint = 0) { throw null; }

        public System.Span<byte> GetSpan(int sizeHint = 0) { throw null; }

        public void Write(System.Buffers.ReadOnlySequence<byte> value) { }

        public void Write(System.ReadOnlySpan<byte> value) { }

        public void WriteVarUInt32(uint value) { }

        public void WriteVarUInt64(ulong value) { }
    }

    public readonly partial struct StateMachineId : System.IEquatable<StateMachineId>
    {
        private readonly int _dummyPrimitive;
        public StateMachineId(ulong Value) { }

        public ulong Value { get { throw null; } init { } }

        [System.Runtime.CompilerServices.CompilerGenerated]
        public readonly void Deconstruct(out ulong Value) { throw null; }

        [System.Runtime.CompilerServices.CompilerGenerated]
        public readonly bool Equals(StateMachineId other) { throw null; }

        [System.Runtime.CompilerServices.CompilerGenerated]
        public override readonly bool Equals(object obj) { throw null; }

        [System.Runtime.CompilerServices.CompilerGenerated]
        public override readonly int GetHashCode() { throw null; }

        [System.Runtime.CompilerServices.CompilerGenerated]
        public static bool operator ==(StateMachineId left, StateMachineId right) { throw null; }

        [System.Runtime.CompilerServices.CompilerGenerated]
        public static bool operator !=(StateMachineId left, StateMachineId right) { throw null; }

        [System.Runtime.CompilerServices.CompilerGenerated]
        public override readonly string ToString() { throw null; }
    }

    public ref partial struct StateMachineLogEntry
    {
        private object _dummy;
        private int _dummyPrimitive;
        public LogEntryWriter Writer { get { throw null; } }

        public void Commit() { }

        public void Dispose() { }
    }

    public abstract partial class StateMachineLogExtentWriterBase : IStateMachineLogExtentWriter, System.IDisposable
    {
        protected StateMachineId ActiveStreamId { get { throw null; } }

        protected bool IsEntryActive { get { throw null; } }

        public abstract long Length { get; }

        protected abstract void AbortEntry(StateMachineId streamId, int entryStart);
        protected abstract void AdvancePayload(int count);
        protected abstract void CommitEntry(StateMachineId streamId, int entryStart);
        public StateMachineLogWriter CreateLogWriter(StateMachineId streamId) { throw null; }

        public abstract void Dispose();
        public abstract Serialization.Buffers.ArcBuffer GetCommittedBuffer();
        protected abstract int GetEntryStart(StateMachineId streamId);
        protected abstract System.Memory<byte> GetPayloadMemory(int sizeHint);
        protected abstract System.Span<byte> GetPayloadSpan(int sizeHint);
        protected virtual void OnBeginEntry(StateMachineId streamId) { }

        public abstract void Reset();
        protected abstract void WritePayload(System.Buffers.ReadOnlySequence<byte> value);
        protected abstract void WritePayload(System.ReadOnlySpan<byte> value);
    }

    public static partial class StateMachineLogFormatKeys
    {
        public const string Json = "json";
        public const string MessagePack = "messagepack";
        public const string OrleansBinary = "orleans-binary";
        public const string Protobuf = "protobuf";
    }

    public readonly partial struct StateMachineLogWriter
    {
        private readonly object _dummy;
        private readonly int _dummyPrimitive;
        public readonly StateMachineLogEntry BeginEntry() { throw null; }
    }

    public sealed partial class StateMachineManagerOptions
    {
        public static readonly System.TimeSpan DEFAULT_RETIREMENT_GRACE_PERIOD;
        public System.TimeSpan RetirementGracePeriod { get { throw null; } set { } }
    }

    public sealed partial class VolatileStateMachineStorage : IStateMachineStorage
    {
        public VolatileStateMachineStorage() { }

        public VolatileStateMachineStorage(string logFormatKey) { }

        public bool IsCompactionRequested { get { throw null; } }

        public string LogFormatKey { get { throw null; } }

        public System.Threading.Tasks.ValueTask AppendAsync(Serialization.Buffers.ArcBuffer segment, System.Threading.CancellationToken cancellationToken) { throw null; }

        public System.Threading.Tasks.ValueTask DeleteAsync(System.Threading.CancellationToken cancellationToken) { throw null; }

        public System.Threading.Tasks.ValueTask ReadAsync(IStateMachineLogDataConsumer consumer, System.Threading.CancellationToken cancellationToken) { throw null; }

        public System.Threading.Tasks.ValueTask ReplaceAsync(Serialization.Buffers.ArcBuffer snapshot, System.Threading.CancellationToken cancellationToken) { throw null; }
    }

    public sealed partial class VolatileStateMachineStorageProvider : IStateMachineStorageProvider
    {
        public VolatileStateMachineStorageProvider() { }

        public VolatileStateMachineStorageProvider(string logFormatKey, System.Func<Runtime.GrainType, string>? logFormatKeySelector) { }

        public VolatileStateMachineStorageProvider(string logFormatKey) { }

        public IStateMachineStorage Create(Runtime.IGrainContext grainContext) { throw null; }
    }
}

namespace OrleansCodeGen.Orleans.Journaling
{
    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_DurableTaskCompletionSourceState<T> : global::Orleans.Serialization.Codecs.IFieldCodec<global::Orleans.Journaling.DurableTaskCompletionSourceState<T>>, global::Orleans.Serialization.Codecs.IFieldCodec, global::Orleans.Serialization.Serializers.IValueSerializer<global::Orleans.Journaling.DurableTaskCompletionSourceState<T>>, global::Orleans.Serialization.Serializers.IValueSerializer
    {
        public Codec_DurableTaskCompletionSourceState(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public void Deserialize<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, scoped ref global::Orleans.Journaling.DurableTaskCompletionSourceState<T> instance) { }

        public global::Orleans.Journaling.DurableTaskCompletionSourceState<T> ReadValue<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, scoped ref global::Orleans.Journaling.DurableTaskCompletionSourceState<T> instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, global::Orleans.Journaling.DurableTaskCompletionSourceState<T> value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_DurableTaskCompletionSourceStatus : global::Orleans.Serialization.Codecs.IFieldCodec<global::Orleans.Journaling.DurableTaskCompletionSourceStatus>, global::Orleans.Serialization.Codecs.IFieldCodec
    {
        public global::Orleans.Journaling.DurableTaskCompletionSourceStatus ReadValue<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.Serialization.WireProtocol.Field field) { throw null; }

        public void WriteField<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, global::Orleans.Journaling.DurableTaskCompletionSourceStatus value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_DurableTaskCompletionSourceState<T> : global::Orleans.Serialization.Cloning.ShallowCopier<global::Orleans.Journaling.DurableTaskCompletionSourceState<T>>
    {
    }
}
