apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: orleans-api
  name: orleans-api
spec:
  replicas: 1
  selector:
    matchLabels:
      run: orleans-api
  strategy: {}
  template:
    metadata:
      labels:
        run: orleans-api
    spec:
      containers:
      - image: orleans-api-image # image name updated by Makefile
        name: orleans-api
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: orleans-api
  name: orleans-api
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 80
  selector:
    run: orleans-api
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: orleans-silo
  name: orleans-silo
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 2
  selector:
    matchLabels:
      run: orleans-silo
  template:
    metadata:
      labels:
        run: orleans-silo
    spec:
      hostNetwork: true
      containers:
      - image: orleans-silo-image # image name updated by Makefile
        name: orleans-silo
        imagePullPolicy: Always