<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="logo.br" />
    <EmbeddedResource Include="logo.br" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Client" />
    <PackageReference Include="Spectre.Console" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChatRoom.Common\ChatRoom.Common.csproj" />
  </ItemGroup>

</Project>
