<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Azure.Identity" Version="1.18.0" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Orleans.Connections.Security" Version="10.2.2" />
    <PackageVersion Include="Microsoft.Orleans.Connections.Security.Entra" Version="10.2.2" />
    <PackageVersion Include="Microsoft.Orleans.Server" Version="10.2.2" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.16.0" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.16.0" />
  </ItemGroup>
</Project>
