<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Microsoft.Orleans.DurableTasks</PackageId>
    <TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <WarningLevel>3</WarningLevel>
    <AnalysisLevel>preview</AnalysisLevel>
    <OrleansBuildTimeCodeGen>true</OrleansBuildTimeCodeGen>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <NoWarn>$(NoWarn);ORLEANSEXP005</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Orleans.DurableTasks.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Orleans.Core.Abstractions\Orleans.Core.Abstractions.csproj" />
    <ProjectReference Include="..\Orleans.DurableMessaging\Orleans.DurableMessaging.csproj" />
    <ProjectReference Include="..\Orleans.Serialization\Orleans.Serialization.csproj" />
    <ProjectReference Include="..\Orleans.Server\Orleans.Server.csproj" />
    <ProjectReference Include="..\System.Distributed.DurableTasks\System.Distributed.DurableTasks.csproj" />
  </ItemGroup>

</Project>
