//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Orleans.Persistence
{
    public static partial class EFGrainStorageHostingExtensions
    {
        public static Microsoft.Extensions.DependencyInjection.IServiceCollection AddEntityFrameworkCoreGrainStorage<TDbContext, TETag>(this Microsoft.Extensions.DependencyInjection.IServiceCollection services, string name, System.Action<Microsoft.EntityFrameworkCore.DbContextOptionsBuilder> configureDatabase)
            where TDbContext : EntityFrameworkCore.Data.GrainStateDbContext<TDbContext, TETag> { throw null; }

        public static Microsoft.Extensions.DependencyInjection.IServiceCollection AddEntityFrameworkCoreGrainStorage<TDbContext, TETag>(this Microsoft.Extensions.DependencyInjection.IServiceCollection services, string name)
            where TDbContext : EntityFrameworkCore.Data.GrainStateDbContext<TDbContext, TETag> { throw null; }

        public static Microsoft.Extensions.DependencyInjection.IServiceCollection AddEntityFrameworkCoreGrainStorageAsDefault<TDbContext, TETag>(this Microsoft.Extensions.DependencyInjection.IServiceCollection services, System.Action<Microsoft.EntityFrameworkCore.DbContextOptionsBuilder> configureDatabase)
            where TDbContext : EntityFrameworkCore.Data.GrainStateDbContext<TDbContext, TETag> { throw null; }

        public static Microsoft.Extensions.DependencyInjection.IServiceCollection AddEntityFrameworkCoreGrainStorageAsDefault<TDbContext, TETag>(this Microsoft.Extensions.DependencyInjection.IServiceCollection services)
            where TDbContext : EntityFrameworkCore.Data.GrainStateDbContext<TDbContext, TETag> { throw null; }

        public static Hosting.ISiloBuilder AddEntityFrameworkCoreGrainStorageAsDefault<TDbContext, TETag>(this Hosting.ISiloBuilder builder, System.Action<Microsoft.EntityFrameworkCore.DbContextOptionsBuilder> configureDatabase)
            where TDbContext : EntityFrameworkCore.Data.GrainStateDbContext<TDbContext, TETag> { throw null; }

        public static Hosting.ISiloBuilder AddEntityFrameworkCoreGrainStorageAsDefault<TDbContext, TETag>(this Hosting.ISiloBuilder builder)
            where TDbContext : EntityFrameworkCore.Data.GrainStateDbContext<TDbContext, TETag> { throw null; }
    }
}

namespace Orleans.Persistence.EntityFrameworkCore
{
    public sealed partial class GuidGrainStorageETagConverter : IEFGrainStorageETagConverter<System.Guid>
    {
        public string FromDbETag(System.Guid etag) { throw null; }

        public System.Guid ToDbETag(string etag) { throw null; }
    }

    public partial interface IEFGrainStorageETagConverter<TETag>
    {
        string FromDbETag(TETag etag);
        TETag ToDbETag(string etag);
    }
}

namespace Orleans.Persistence.EntityFrameworkCore.Data
{
    public partial class GrainStateDbContext<TDbContext, TETag> : Microsoft.EntityFrameworkCore.DbContext where TDbContext : Microsoft.EntityFrameworkCore.DbContext
    {
        public GrainStateDbContext(Microsoft.EntityFrameworkCore.DbContextOptions<TDbContext> options) { }

        public Microsoft.EntityFrameworkCore.DbSet<GrainStateRecord<TETag>> GrainState { get { throw null; } set { } }

        protected override void OnModelCreating(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder) { }
    }

    public partial class GrainStateRecord<TETag>
    {
        public string? Data { get { throw null; } set { } }

        public TETag ETag { get { throw null; } set { } }

        public string GrainId { get { throw null; } set { } }

        public string GrainType { get { throw null; } set { } }

        public string ServiceId { get { throw null; } set { } }

        public string StateType { get { throw null; } set { } }
    }

    public abstract partial class GuidGrainStateDbContext<TDbContext> : GrainStateDbContext<TDbContext, System.Guid> where TDbContext : Microsoft.EntityFrameworkCore.DbContext
    {
        protected GuidGrainStateDbContext(Microsoft.EntityFrameworkCore.DbContextOptions<TDbContext> options) : base(default!) { }

        protected override void OnModelCreating(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder) { }

        public override int SaveChanges(bool acceptAllChangesOnSuccess) { throw null; }

        public override System.Threading.Tasks.Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, System.Threading.CancellationToken cancellationToken = default) { throw null; }
    }
}