using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Orleans.BroadcastChannel")]
[assembly: InternalsVisibleTo("Orleans.CodeGeneration")]
[assembly: InternalsVisibleTo("Orleans.CodeGeneration.Build")]
[assembly: InternalsVisibleTo("Orleans.Runtime")]
[assembly: InternalsVisibleTo("Orleans.DurableJobs")]
[assembly: InternalsVisibleTo("Orleans.Streaming")]
[assembly: InternalsVisibleTo("Orleans.TestingHost")]

[assembly: InternalsVisibleTo("Orleans.AWS.Tests")]
[assembly: InternalsVisibleTo("Orleans.DefaultCluster.Tests")]
[assembly: InternalsVisibleTo("GoogleUtils.Tests")]
[assembly: InternalsVisibleTo("LoadTestGrains")]
[assembly: InternalsVisibleTo("Orleans.Core.Tests")]
[assembly: InternalsVisibleTo("Orleans.Streaming.EventHubs.Tests")]
[assembly: InternalsVisibleTo("Benchmarks")]
[assembly: InternalsVisibleTo("Orleans.Runtime.Tests")]
[assembly: InternalsVisibleTo("Orleans.Streaming.Tests")]
[assembly: InternalsVisibleTo("Orleans.DurableJobs.Tests")]
[assembly: InternalsVisibleTo("Orleans.Azure.Tests")]
[assembly: InternalsVisibleTo("Orleans.Cosmos.Tests")]
[assembly: InternalsVisibleTo("Orleans.AdoNet.Tests")]
[assembly: InternalsVisibleTo("Orleans.Redis.Tests")]
[assembly: InternalsVisibleTo("Orleans.Clustering.ZooKeeper.Tests")]
[assembly: InternalsVisibleTo("Orleans.Runtime.Internal.Tests")]
[assembly: InternalsVisibleTo("Orleans.Placement.Tests")]
[assembly: InternalsVisibleTo("Orleans.GrainDirectory.Tests")]
[assembly: InternalsVisibleTo("TestExtensions")]
[assembly: InternalsVisibleTo("TestInternalGrains")]
[assembly: InternalsVisibleTo("CodeGenerator.Tests")]

[assembly: InternalsVisibleTo("Orleans.Reminders")]

// Mocking libraries
[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")]
