//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Orleans.Clustering.Firestore
{
    public partial class FirestoreOptions
    {
        public string? EmulatorHost { get { throw null; } set { } }

        public string ProjectId { get { throw null; } set { } }

        public string RootCollectionName { get { throw null; } set { } }
    }
}

namespace Orleans.Hosting
{
    public static partial class FirestoreClusteringExtensions
    {
        public static IClientBuilder UseFirestoreClustering(this IClientBuilder builder, System.Action<Microsoft.Extensions.Options.OptionsBuilder<Clustering.Firestore.FirestoreOptions>> configureOptions) { throw null; }

        public static IClientBuilder UseFirestoreClustering(this IClientBuilder builder, System.Action<Clustering.Firestore.FirestoreOptions>? configureOptions) { throw null; }

        public static ISiloBuilder UseFirestoreClustering(this ISiloBuilder builder, System.Action<Microsoft.Extensions.Options.OptionsBuilder<Clustering.Firestore.FirestoreOptions>> configureOptions) { throw null; }

        public static ISiloBuilder UseFirestoreClustering(this ISiloBuilder builder, System.Action<Clustering.Firestore.FirestoreOptions>? configureOptions) { throw null; }
    }
}