<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.targets', '$(MSBuildThisFileDirectory)../'))" />

  <ItemGroup Condition="'$(OrleansSamplePackageVersion)' != ''">
    <PackageReference Update="Microsoft.Orleans.*" VersionOverride="$(OrleansSamplePackageVersion)" />
  </ItemGroup>
</Project>
