// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orleans.Reminders.EntityFrameworkCore.SqlServer.Data;

#nullable disable

namespace Orleans.Reminders.EntityFrameworkCore.SqlServer.Data.Migrations
{
    [DbContext(typeof(SqlServerReminderDbContext))]
    partial class SqlServerReminderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Orleans.Reminders.EntityFrameworkCore.Data.ReminderRecord<byte[]>", b =>
                {
                    b.Property<string>("ServiceId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("GrainId")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<byte[]>("ETag")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("GrainHash")
                        .HasColumnType("bigint");

                    b.Property<long>("Period")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ServiceId", "GrainId", "Name")
                        .HasName("PK_Reminders");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("ServiceId", "GrainId", "Name"), false);

                    b.HasIndex("ServiceId", "GrainHash")
                        .HasDatabaseName("IDX_Reminders_ServiceId_GrainHash");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ServiceId", "GrainHash"), false);

                    b.HasIndex("ServiceId", "GrainId")
                        .HasDatabaseName("IDX_Reminders_ServiceId_GrainId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ServiceId", "GrainId"), false);

                    b.ToTable("Reminders");
                });
#pragma warning restore 612, 618
        }
    }
}
