storage:
  tsdb:
    out_of_order_time_window: 30m

otlp:
  translation_strategy: UnderscoreEscapingWithSuffixes
  keep_identifying_resource_attributes: true
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace
    - service.version
    - deployment.environment.name
