name: Setup test environment
description: Install the .NET SDK and pull request coverage tooling.

runs:
  using: composite
  steps:
  - name: Setup .NET
    uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5
    with:
      global-json-file: global.json
  - name: Setup code coverage
    if: github.event_name == 'pull_request'
    uses: ./.github/actions/setup-coverage
