//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Orleans.Reminders
{
    public static partial class MySqlHostingExtensions
    {
        public static Microsoft.Extensions.DependencyInjection.IServiceCollection UseEntityFrameworkCoreMySqlReminderService(this Microsoft.Extensions.DependencyInjection.IServiceCollection services, System.Action<Microsoft.EntityFrameworkCore.DbContextOptionsBuilder> configureDatabase) { throw null; }

        public static Microsoft.Extensions.DependencyInjection.IServiceCollection UseEntityFrameworkCoreMySqlReminderService(this Microsoft.Extensions.DependencyInjection.IServiceCollection services) { throw null; }

        public static Hosting.ISiloBuilder UseEntityFrameworkCoreMySqlReminderService(this Hosting.ISiloBuilder builder, System.Action<Microsoft.EntityFrameworkCore.DbContextOptionsBuilder> configureDatabase) { throw null; }

        public static Hosting.ISiloBuilder UseEntityFrameworkCoreMySqlReminderService(this Hosting.ISiloBuilder builder) { throw null; }
    }
}

namespace Orleans.Reminders.EntityFrameworkCore.MySql.Data
{
    public partial class MySqlReminderDbContext : EntityFrameworkCore.Data.GuidReminderDbContext<MySqlReminderDbContext>
    {
        public MySqlReminderDbContext(Microsoft.EntityFrameworkCore.DbContextOptions<MySqlReminderDbContext> options) : base(default!) { }

        protected override void OnModelCreating(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder) { }
    }

    public partial class MySqlReminderDbContextFactory : Microsoft.EntityFrameworkCore.Design.IDesignTimeDbContextFactory<MySqlReminderDbContext>
    {
        public MySqlReminderDbContext CreateDbContext(string[] args) { throw null; }
    }
}

namespace Orleans.Reminders.EntityFrameworkCore.MySql.Data.Migrations
{
    [Microsoft.EntityFrameworkCore.Infrastructure.DbContext(typeof(MySqlReminderDbContext))]
    [Microsoft.EntityFrameworkCore.Migrations.Migration("20260811210118_InitialRemindersSchema")]
    public partial class InitialRemindersSchema : Microsoft.EntityFrameworkCore.Migrations.Migration
    {
        protected override void BuildTargetModel(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder) { }

        protected override void Down(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder migrationBuilder) { }

        protected override void Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder migrationBuilder) { }
    }
}