<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <TargetFrameworks>$(TestTargetFrameworks)</TargetFrameworks>
    <Nullable>enable</Nullable>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <OrleansBuildTimeCodeGen>true</OrleansBuildTimeCodeGen>
    <ImplicitUsings>disable</ImplicitUsings>
    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsCheck" />
    <PackageReference Include="xunit.v3.extensibility.core" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Tools" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Verify.XunitV3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)src\Orleans.Serialization.TestKit\Orleans.Serialization.TestKit.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Orleans.Serialization.FSharp\Orleans.Serialization.FSharp.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Orleans.Serialization\Orleans.Serialization.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Orleans.Streaming\Orleans.Streaming.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Orleans.Serialization.SystemTextJson\Orleans.Serialization.SystemTextJson.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Orleans.Serialization.NewtonsoftJson\Orleans.Serialization.NewtonsoftJson.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Orleans.Serialization.MessagePack\Orleans.Serialization.MessagePack.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Serializers\Orleans.Serialization.Protobuf\Orleans.Serialization.Protobuf.csproj" />
    <ProjectReference Include="..\Misc\TestSerializerExternalModels\TestSerializerExternalModels.csproj" />
    <ProjectReference Include="$(SourceRoot)test\Orleans.Runtime.Tests\Orleans.Runtime.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="protobuf-model.proto" GrpcServices="None" />
  </ItemGroup>

</Project>
