//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Orleans.Journaling.Protobuf
{
    public sealed partial class ProtobufDictionaryEntryCodec<TKey, TValue> : IDurableDictionaryCodec<TKey, TValue>
    {
        public ProtobufDictionaryEntryCodec(ProtobufValueConverter<TKey> keyConverter, ProtobufValueConverter<TValue> valueConverter) { }

        public void Apply(System.Buffers.ReadOnlySequence<byte> input, IDurableDictionaryLogEntryConsumer<TKey, TValue> consumer) { }

        public void WriteClear(System.Buffers.IBufferWriter<byte> output) { }

        public void WriteRemove(TKey key, System.Buffers.IBufferWriter<byte> output) { }

        public void WriteSet(TKey key, TValue value, System.Buffers.IBufferWriter<byte> output) { }

        public void WriteSnapshot(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<TKey, TValue>> items, int count, System.Buffers.IBufferWriter<byte> output) { }
    }

    public static partial class ProtobufJournalingExtensions
    {
        public static Hosting.ISiloBuilder UseProtobufCodec(this Hosting.ISiloBuilder builder, System.Action<ProtobufJournalingOptions> configure) { throw null; }

        public static Hosting.ISiloBuilder UseProtobufCodec(this Hosting.ISiloBuilder builder) { throw null; }
    }

    public sealed partial class ProtobufJournalingOptions
    {
        public ProtobufJournalingOptions AddMessageParser<T>(Google.Protobuf.MessageParser<T> parser)
            where T : Google.Protobuf.IMessage<T> { throw null; }
    }

    public sealed partial class ProtobufListEntryCodec<T> : IDurableListCodec<T>
    {
        public ProtobufListEntryCodec(ProtobufValueConverter<T> converter) { }

        public void Apply(System.Buffers.ReadOnlySequence<byte> input, IDurableListLogEntryConsumer<T> consumer) { }

        public void WriteAdd(T item, System.Buffers.IBufferWriter<byte> output) { }

        public void WriteClear(System.Buffers.IBufferWriter<byte> output) { }

        public void WriteInsert(int index, T item, System.Buffers.IBufferWriter<byte> output) { }

        public void WriteRemoveAt(int index, System.Buffers.IBufferWriter<byte> output) { }

        public void WriteSet(int index, T item, System.Buffers.IBufferWriter<byte> output) { }

        public void WriteSnapshot(System.Collections.Generic.IEnumerable<T> items, int count, System.Buffers.IBufferWriter<byte> output) { }
    }

    public sealed partial class ProtobufQueueEntryCodec<T> : IDurableQueueCodec<T>
    {
        public ProtobufQueueEntryCodec(ProtobufValueConverter<T> converter) { }

        public void Apply(System.Buffers.ReadOnlySequence<byte> input, IDurableQueueLogEntryConsumer<T> consumer) { }

        public void WriteClear(System.Buffers.IBufferWriter<byte> output) { }

        public void WriteDequeue(System.Buffers.IBufferWriter<byte> output) { }

        public void WriteEnqueue(T item, System.Buffers.IBufferWriter<byte> output) { }

        public void WriteSnapshot(System.Collections.Generic.IEnumerable<T> items, int count, System.Buffers.IBufferWriter<byte> output) { }
    }

    public sealed partial class ProtobufSetEntryCodec<T> : IDurableSetCodec<T>
    {
        public ProtobufSetEntryCodec(ProtobufValueConverter<T> converter) { }

        public void Apply(System.Buffers.ReadOnlySequence<byte> input, IDurableSetLogEntryConsumer<T> consumer) { }

        public void WriteAdd(T item, System.Buffers.IBufferWriter<byte> output) { }

        public void WriteClear(System.Buffers.IBufferWriter<byte> output) { }

        public void WriteRemove(T item, System.Buffers.IBufferWriter<byte> output) { }

        public void WriteSnapshot(System.Collections.Generic.IEnumerable<T> items, int count, System.Buffers.IBufferWriter<byte> output) { }
    }

    public sealed partial class ProtobufStateEntryCodec<T> : IDurableStateCodec<T>
    {
        public ProtobufStateEntryCodec(ProtobufValueConverter<T> converter) { }

        public void Apply(System.Buffers.ReadOnlySequence<byte> input, IDurableStateLogEntryConsumer<T> consumer) { }

        public void WriteClear(System.Buffers.IBufferWriter<byte> output) { }

        public void WriteSet(T state, ulong version, System.Buffers.IBufferWriter<byte> output) { }
    }

    public sealed partial class ProtobufTcsEntryCodec<T> : IDurableTaskCompletionSourceCodec<T>
    {
        public ProtobufTcsEntryCodec(ProtobufValueConverter<T> converter) { }

        public void Apply(System.Buffers.ReadOnlySequence<byte> input, IDurableTaskCompletionSourceLogEntryConsumer<T> consumer) { }

        public void WriteCanceled(System.Buffers.IBufferWriter<byte> output) { }

        public void WriteCompleted(T value, System.Buffers.IBufferWriter<byte> output) { }

        public void WriteFaulted(System.Exception exception, System.Buffers.IBufferWriter<byte> output) { }

        public void WritePending(System.Buffers.IBufferWriter<byte> output) { }
    }

    public sealed partial class ProtobufValueConverter<T>
    {
        public ProtobufValueConverter() { }

        public ProtobufValueConverter(ILogDataCodec<T> fallbackCodec) { }

        public static bool IsNativeType { get { throw null; } }

        public T FromBytes(System.Buffers.ReadOnlySequence<byte> bytes) { throw null; }

        public byte[] ToBytes(T value) { throw null; }
    }

    public sealed partial class ProtobufValueEntryCodec<T> : IDurableValueCodec<T>
    {
        public ProtobufValueEntryCodec(ProtobufValueConverter<T> converter) { }

        public void Apply(System.Buffers.ReadOnlySequence<byte> input, IDurableValueLogEntryConsumer<T> consumer) { }

        public void WriteSet(T value, System.Buffers.IBufferWriter<byte> output) { }
    }
}