//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Orleans.Journaling.Protobuf
{
    public sealed partial class ProtobufDictionaryOperationCodec<TKey, TValue> : IDurableDictionaryOperationCodec<TKey, TValue>
    {
        public ProtobufDictionaryOperationCodec(ProtobufValueConverter<TKey> keyConverter, ProtobufValueConverter<TValue> valueConverter) { }

        public void Apply(System.Buffers.ReadOnlySequence<byte> input, IDurableDictionaryOperationHandler<TKey, TValue> consumer) { }

        public void WriteClear(System.Buffers.IBufferWriter<byte> output) { }

        public void WriteRemove(TKey key, System.Buffers.IBufferWriter<byte> output) { }

        public void WriteSet(TKey key, TValue value, System.Buffers.IBufferWriter<byte> output) { }

        public void WriteSnapshot(System.Collections.Generic.IReadOnlyCollection<System.Collections.Generic.KeyValuePair<TKey, TValue>> items, System.Buffers.IBufferWriter<byte> output) { }
    }

    public static partial class ProtobufJournalingExtensions
    {
        public static Hosting.ISiloBuilder UseProtobufCodec(this Hosting.ISiloBuilder builder, System.Action<ProtobufJournalingOptions> configure) { throw null; }

        public static Hosting.ISiloBuilder UseProtobufCodec(this Hosting.ISiloBuilder builder) { throw null; }
    }

    public sealed partial class ProtobufJournalingOptions
    {
        public ProtobufJournalingOptions AddMessageParser<T>(Google.Protobuf.MessageParser<T> parser)
            where T : Google.Protobuf.IMessage<T> { throw null; }
    }

    public sealed partial class ProtobufListOperationCodec<T> : IDurableListOperationCodec<T>
    {
        public ProtobufListOperationCodec(ProtobufValueConverter<T> converter) { }

        public void Apply(System.Buffers.ReadOnlySequence<byte> input, IDurableListOperationHandler<T> consumer) { }

        public void WriteAdd(T item, System.Buffers.IBufferWriter<byte> output) { }

        public void WriteClear(System.Buffers.IBufferWriter<byte> output) { }

        public void WriteInsert(int index, T item, System.Buffers.IBufferWriter<byte> output) { }

        public void WriteRemoveAt(int index, System.Buffers.IBufferWriter<byte> output) { }

        public void WriteSet(int index, T item, System.Buffers.IBufferWriter<byte> output) { }

        public void WriteSnapshot(System.Collections.Generic.IReadOnlyCollection<T> items, System.Buffers.IBufferWriter<byte> output) { }
    }

    public sealed partial class ProtobufQueueOperationCodec<T> : IDurableQueueOperationCodec<T>
    {
        public ProtobufQueueOperationCodec(ProtobufValueConverter<T> converter) { }

        public void Apply(System.Buffers.ReadOnlySequence<byte> input, IDurableQueueOperationHandler<T> consumer) { }

        public void WriteClear(System.Buffers.IBufferWriter<byte> output) { }

        public void WriteDequeue(System.Buffers.IBufferWriter<byte> output) { }

        public void WriteEnqueue(T item, System.Buffers.IBufferWriter<byte> output) { }

        public void WriteSnapshot(System.Collections.Generic.IReadOnlyCollection<T> items, System.Buffers.IBufferWriter<byte> output) { }
    }

    public sealed partial class ProtobufSetOperationCodec<T> : IDurableSetOperationCodec<T>
    {
        public ProtobufSetOperationCodec(ProtobufValueConverter<T> converter) { }

        public void Apply(System.Buffers.ReadOnlySequence<byte> input, IDurableSetOperationHandler<T> consumer) { }

        public void WriteAdd(T item, System.Buffers.IBufferWriter<byte> output) { }

        public void WriteClear(System.Buffers.IBufferWriter<byte> output) { }

        public void WriteRemove(T item, System.Buffers.IBufferWriter<byte> output) { }

        public void WriteSnapshot(System.Collections.Generic.IReadOnlyCollection<T> items, System.Buffers.IBufferWriter<byte> output) { }
    }

    public sealed partial class ProtobufStateOperationCodec<T> : IDurableStateOperationCodec<T>
    {
        public ProtobufStateOperationCodec(ProtobufValueConverter<T> converter) { }

        public void Apply(System.Buffers.ReadOnlySequence<byte> input, IDurableStateOperationHandler<T> consumer) { }

        public void WriteClear(System.Buffers.IBufferWriter<byte> output) { }

        public void WriteSet(T state, ulong version, System.Buffers.IBufferWriter<byte> output) { }
    }

    public sealed partial class ProtobufTcsOperationCodec<T> : IDurableTaskCompletionSourceOperationCodec<T>
    {
        public ProtobufTcsOperationCodec(ProtobufValueConverter<T> converter) { }

        public void Apply(System.Buffers.ReadOnlySequence<byte> input, IDurableTaskCompletionSourceOperationHandler<T> consumer) { }

        public void WriteCanceled(System.Buffers.IBufferWriter<byte> output) { }

        public void WriteCompleted(T value, System.Buffers.IBufferWriter<byte> output) { }

        public void WriteFaulted(System.Exception exception, System.Buffers.IBufferWriter<byte> output) { }

        public void WritePending(System.Buffers.IBufferWriter<byte> output) { }
    }

    public sealed partial class ProtobufValueConverter<T>
    {
        public ProtobufValueConverter() { }

        public ProtobufValueConverter(ILogValueCodec<T> fallbackCodec) { }

        public static bool IsNativeType { get { throw null; } }

        public T FromBytes(System.Buffers.ReadOnlySequence<byte> bytes) { throw null; }

        public byte[] ToBytes(T value) { throw null; }
    }

    public sealed partial class ProtobufValueOperationCodec<T> : IDurableValueOperationCodec<T>
    {
        public ProtobufValueOperationCodec(ProtobufValueConverter<T> converter) { }

        public void Apply(System.Buffers.ReadOnlySequence<byte> input, IDurableValueOperationHandler<T> consumer) { }

        public void WriteSet(T value, System.Buffers.IBufferWriter<byte> output) { }
    }
}