<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(TestTargetFrameworks)</TargetFrameworks>
    <OrleansBuildTimeCodeGen>true</OrleansBuildTimeCodeGen>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);ORLEANSEXP005</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" />
    <PackageReference Include="Verify.XunitV3" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Accordant" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)src\Redis\Orleans.Clustering.Redis\Orleans.Clustering.Redis.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Redis\Orleans.Reminders.Redis\Orleans.Reminders.Redis.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Redis\Orleans.Persistence.Redis\Orleans.Persistence.Redis.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Redis\Orleans.GrainDirectory.Redis\Orleans.GrainDirectory.Redis.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Redis\Orleans.Streaming.Redis\Orleans.Streaming.Redis.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Orleans.Persistence.TestKit\Orleans.Persistence.TestKit.csproj" PrivateAssets="all" />
    <ProjectReference Include="$(SourceRoot)src\Orleans.Reminders.TestKit\Orleans.Reminders.TestKit.csproj" PrivateAssets="all" />
    <ProjectReference Include="$(SourceRoot)test\Orleans.Runtime.Internal.Tests\Orleans.Runtime.Internal.Tests.csproj" />
    <ProjectReference Include="$(SourceRoot)test\Orleans.Streaming.Tests\Orleans.Streaming.Tests.csproj" />
    <ProjectReference Include="$(SourceRoot)src\Redis\Orleans.Journaling.Redis\Orleans.Journaling.Redis.csproj" />
  </ItemGroup>

</Project>
