//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Orleans.Serialization
{
    [Alias("memorypack")]
    public partial class MemoryPackCodec : Serializers.IGeneralizedCodec, Codecs.IFieldCodec, Cloning.IGeneralizedCopier, Cloning.IDeepCopier, ITypeFilter
    {
        public const string WellKnownAlias = "memorypack";
        public MemoryPackCodec(System.Collections.Generic.IEnumerable<Serializers.ICodecSelector> serializableTypeSelectors, System.Collections.Generic.IEnumerable<Serializers.ICopierSelector> copyableTypeSelectors, Microsoft.Extensions.Options.IOptions<MemoryPackCodecOptions> options) { }

        object Cloning.IDeepCopier.DeepCopy(object input, Cloning.CopyContext context) { throw null; }

        bool Cloning.IGeneralizedCopier.IsSupportedType(System.Type type) { throw null; }

        object Codecs.IFieldCodec.ReadValue<TInput>(ref Buffers.Reader<TInput> reader, WireProtocol.Field field) { throw null; }

        void Codecs.IFieldCodec.WriteField<TBufferWriter>(ref Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, object value) { }

        bool? ITypeFilter.IsTypeAllowed(System.Type type) { throw null; }

        bool Serializers.IGeneralizedCodec.IsSupportedType(System.Type type) { throw null; }
    }

    public partial class MemoryPackCodecOptions
    {
        public System.Func<System.Type, bool?> IsCopyableType { get { throw null; } set { } }

        public System.Func<System.Type, bool?> IsSerializableType { get { throw null; } set { } }

        public MemoryPack.MemoryPackSerializerOptions SerializerOptions { get { throw null; } set { } }
    }

    public static partial class SerializationHostingExtensions
    {
        public static ISerializerBuilder AddMemoryPackSerializer(this ISerializerBuilder serializerBuilder, System.Func<System.Type, bool> isSerializable = null, System.Func<System.Type, bool> isCopyable = null, MemoryPack.MemoryPackSerializerOptions memoryPackSerializerOptions = null) { throw null; }

        public static ISerializerBuilder AddMemoryPackSerializer(this ISerializerBuilder serializerBuilder, System.Func<System.Type, bool> isSerializable, System.Func<System.Type, bool> isCopyable, System.Action<Microsoft.Extensions.Options.OptionsBuilder<MemoryPackCodecOptions>> configureOptions = null) { throw null; }
    }
}