//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Orleans.Persistence.TestKit
{
    public abstract partial class GrainStorageTestFixture : Xunit.IAsyncLifetime
    {
        protected TestingHost.InProcessTestCluster Cluster { get { throw null; } }

        public IGrainFactory GrainFactory { get { throw null; } }

        public Storage.IGrainStorage Storage { get { throw null; } }

        protected abstract string StorageProviderName { get; }

        protected virtual void CheckPreconditionsOrThrow() { }

        protected abstract void ConfigureSilo(Hosting.ISiloBuilder siloBuilder);
        protected virtual void ConfigureTestCluster(TestingHost.InProcessTestClusterBuilder builder) { }

        public virtual System.Threading.Tasks.Task DisposeAsync() { throw null; }

        public void EnsurePreconditionsMet() { }

        public virtual System.Threading.Tasks.Task InitializeAsync() { throw null; }
    }

    public abstract partial class GrainStorageTestRunner
    {
        protected GrainStorageTestRunner(Storage.IGrainStorage storage) { }

        protected Storage.IGrainStorage Storage { get { throw null; } }

        protected (Runtime.GrainId GrainId, GrainState<TestState1> GrainState) GetTestReferenceAndState(long grainId, string? version) { throw null; }

        protected (Runtime.GrainId GrainId, GrainState<TestState1> GrainState) GetTestReferenceAndState(string grainId, string? version) { throw null; }

        public virtual System.Threading.Tasks.Task PersistenceStorage_ClearBeforeWrite() { throw null; }

        public virtual System.Threading.Tasks.Task PersistenceStorage_ClearInconsistentFailsWithInconsistentStateException() { throw null; }

        public virtual System.Threading.Tasks.Task PersistenceStorage_ClearStateDoesNotNullifyState() { throw null; }

        public virtual System.Threading.Tasks.Task PersistenceStorage_ClearUpdatesETag() { throw null; }

        public virtual System.Threading.Tasks.Task PersistenceStorage_ETagChangesOnWrite() { throw null; }

        public virtual System.Threading.Tasks.Task PersistenceStorage_MultipleClearOperations() { throw null; }

        public virtual System.Threading.Tasks.Task PersistenceStorage_ReadAfterClear() { throw null; }

        public virtual System.Threading.Tasks.Task PersistenceStorage_ReadNonExistentState() { throw null; }

        public virtual System.Threading.Tasks.Task PersistenceStorage_ReadNonExistentStateHasNonNullState() { throw null; }

        public virtual System.Threading.Tasks.Task PersistenceStorage_StateNamesUseIndependentRecords() { throw null; }

        public virtual System.Threading.Tasks.Task PersistenceStorage_WriteClearRead() { throw null; }

        public virtual System.Threading.Tasks.Task PersistenceStorage_WriteClearWrite() { throw null; }

        public virtual System.Threading.Tasks.Task PersistenceStorage_WriteDuplicateFailsWithInconsistentStateException() { throw null; }

        public virtual System.Threading.Tasks.Task PersistenceStorage_WriteInconsistentFailsWithInconsistentStateException() { throw null; }

        public virtual System.Threading.Tasks.Task PersistenceStorage_WriteRead_IntegerKey() { throw null; }

        public virtual System.Threading.Tasks.Task PersistenceStorage_WriteRead_StringKey() { throw null; }

        public virtual System.Threading.Tasks.Task PersistenceStorage_WriteReadClearReadCycle() { throw null; }

        public virtual System.Threading.Tasks.Task PersistenceStorage_WriteReadIdCyrillic() { throw null; }

        public virtual System.Threading.Tasks.Task PersistenceStorage_WriteReadWriteReadStatesInParallel() { throw null; }

        public virtual System.Threading.Tasks.Task PersistenceStorage_WriteWithSameValuesUpdatesETag() { throw null; }

        protected System.Threading.Tasks.Task RunPersistenceStorage_WriteReadWriteReadStatesInParallel(string prefix, int countOfGrains) { throw null; }

        protected System.Threading.Tasks.Task Store_WriteClearRead<T>(string grainTypeName, Runtime.GrainId grainId, GrainState<T> grainState)
            where T : new() { throw null; }

        protected System.Threading.Tasks.Task Store_WriteRead<T>(string grainTypeName, Runtime.GrainId grainId, GrainState<T> grainState)
            where T : new() { throw null; }
    }

    [GenerateSerializer]
    public partial class TestState1 : System.IEquatable<TestState1>
    {
        [Id(0)]
        public string? A { get { throw null; } set { } }

        [Id(1)]
        public int B { get { throw null; } set { } }

        [Id(2)]
        public long C { get { throw null; } set { } }

        public bool Equals(TestState1? other) { throw null; }

        public override bool Equals(object? obj) { throw null; }

        public override int GetHashCode() { throw null; }
    }
}

namespace OrleansCodeGen.Orleans.Persistence.TestKit
{
    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_TestState1 : global::Orleans.Serialization.Codecs.IFieldCodec<global::Orleans.Persistence.TestKit.TestState1>, global::Orleans.Serialization.Codecs.IFieldCodec, global::Orleans.Serialization.Serializers.IBaseCodec<global::Orleans.Persistence.TestKit.TestState1>, global::Orleans.Serialization.Serializers.IBaseCodec
    {
        public void Deserialize<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.Persistence.TestKit.TestState1 instance) { }

        public global::Orleans.Persistence.TestKit.TestState1 ReadValue<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, global::Orleans.Persistence.TestKit.TestState1 instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, global::Orleans.Persistence.TestKit.TestState1 value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_TestState1 : global::Orleans.Serialization.Cloning.IDeepCopier<global::Orleans.Persistence.TestKit.TestState1>, global::Orleans.Serialization.Cloning.IDeepCopier, global::Orleans.Serialization.Cloning.IBaseCopier<global::Orleans.Persistence.TestKit.TestState1>, global::Orleans.Serialization.Cloning.IBaseCopier
    {
        public void DeepCopy(global::Orleans.Persistence.TestKit.TestState1 input, global::Orleans.Persistence.TestKit.TestState1 output, global::Orleans.Serialization.Cloning.CopyContext context) { }

        public global::Orleans.Persistence.TestKit.TestState1 DeepCopy(global::Orleans.Persistence.TestKit.TestState1 original, global::Orleans.Serialization.Cloning.CopyContext context) { throw null; }
    }
}