<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Microsoft.Orleans.GrainDirectory.Firestore</PackageId>
    <Title>Microsoft Orleans Google Cloud Firestore Grain Directory Provider</Title>
    <Description>Microsoft Orleans grain directory provider backed by Google Cloud Firestore</Description>
    <PackageTags>$(PackageTags) Google Cloud GCP Firestore</PackageTags>
    <TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>
    <AssemblyName>Orleans.GrainDirectory.Firestore</AssemblyName>
    <RootNamespace>Orleans.GrainDirectory.Firestore</RootNamespace>
    <OrleansBuildTimeCodeGen>true</OrleansBuildTimeCodeGen>
    <DefineConstants>$(DefineConstants);ORLEANS_DIRECTORY</DefineConstants>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Shared\Storage\FirestoreDataManager.cs" Link="Storage\FirestoreDataManager.cs" />
    <Compile Include="..\Shared\Storage\FirestoreEntity.cs" Link="Storage\FirestoreEntity.cs" />
    <Compile Include="..\Shared\Storage\FirestoreOptions.cs" Link="Storage\FirestoreOptions.cs" />
    <Compile Include="..\Shared\Utils\Utils.cs" Link="Utils\Utils.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)src\Orleans.Runtime\Orleans.Runtime.csproj" />
    <PackageReference Include="Google.Cloud.Firestore" />
  </ItemGroup>
</Project>
