<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Aspire.Hosting.AppHost" Version="13.2.4" />
    <PackageVersion Include="Aspire.Hosting.Orleans" Version="13.2.4" />
    <PackageVersion Include="Aspire.Hosting.Redis" Version="13.2.4" />
    <PackageVersion Include="Aspire.StackExchange.Redis" Version="13.2.4" />
    <PackageVersion Include="MessagePack" Version="3.1.7" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Orleans.Clustering.Redis" Version="10.2.2" />
    <PackageVersion Include="Microsoft.Orleans.Server" Version="10.2.2" />
  </ItemGroup>
</Project>
