<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(TestTargetFrameworks)</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <OrleansBuildTimeCodeGen>true</OrleansBuildTimeCodeGen>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Orleans.Reminders.TestKit\Orleans.Reminders.TestKit.csproj" PrivateAssets="all" />
    <ProjectReference Include="..\Orleans.Testing.Reminders\Orleans.Testing.Reminders.csproj" />
    <ProjectReference Include="..\TestInfrastructure\TestExtensions\TestExtensions.csproj" />
  </ItemGroup>

</Project>
