#nullable enable

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CodeActions;
using Microsoft.CodeAnalysis.CodeFixes;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Composition;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace Orleans.Analyzers;

/// <summary>
/// A code fix provider that adds grain interfaces to OrleansContracts.txt or updates their version.
/// </summary>
[ExportCodeFixProvider(LanguageNames.CSharp, Name = nameof(GrainInterfaceVersionCodeFix)), Shared]
public class GrainInterfaceVersionCodeFix : CodeFixProvider
{
    private const string DefaultNewLine = "\n";
    private const string OrleansContractsFileExistsMetadata =
        "build_metadata.AdditionalFiles.OrleansContractsFileExists";
    private const string OrleansCoreAbstractionsAssemblyName = "Orleans.Core.Abstractions";
    private const int MaxConcurrentProjectRegenerations = 2;
    private const string RegenerateCodeActionTitle = "Regenerate OrleansContracts.txt";
    private const string RegenerateCodeActionEquivalenceKey = nameof(RegenerateOrleansContractsFileAsync);
    private static readonly StringComparison FilePathComparison =
        Path.DirectorySeparatorChar == '\\' ? StringComparison.OrdinalIgnoreCase : StringComparison.Ordinal;
    private static readonly Encoding Utf8NoBom = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false);
    private const string RegenerationCommand =
        "dotnet format PATH_TO_PROJECT_OR_SOLUTION analyzers --severity info --diagnostics ORLEANS0016 ORLEANS0017 ORLEANS0018 ORLEANS0019 ORLEANS0020 ORLEANS0022 ORLEANS0023 ORLEANS0024";
    private static readonly string[] GeneratedHeader =
    [
        "# This file is generated by the Orleans contract analyzer.",
        "# To regenerate, run this command from the repository root after replacing",
        "# PATH_TO_PROJECT_OR_SOLUTION with the owning .csproj, .sln, or .slnx path:",
        $"# {RegenerationCommand}",
        "# Verify with: dotnet build PATH_TO_PROJECT_OR_SOLUTION",
        "# The regeneration command edits this manifest only; it does not change source attributes.",
        "# OrleansContracts format: 2",
        "# Method lines use: wire-identity: CLR-signature.",
        "# The identity is the identifier Orleans uses at runtime, whether generated or declared in source.",
        "# Review every diff: identity or signature changes can break wire compatibility during rolling upgrades.",
        "# Details: https://aka.ms/orleans/OrleansContracts.txt"
    ];

    public sealed override ImmutableArray<string> FixableDiagnosticIds => ImmutableArray.Create(
        GrainInterfaceVersionAnalyzer.RuleId0016,  // Interface not declared
        GrainInterfaceVersionAnalyzer.RuleId0017,  // Version mismatch
        GrainInterfaceVersionAnalyzer.RuleId0018,  // Member not declared
        GrainInterfaceVersionAnalyzer.RuleId0019,  // Removed interface not retired
        GrainInterfaceVersionAnalyzer.RuleId0020,  // Contracts file missing
        GrainInterfaceVersionAnalyzer.RuleId0022,  // Grain class not declared
        GrainInterfaceVersionAnalyzer.RuleId0023,  // Grain class alias mismatch
        GrainInterfaceVersionAnalyzer.RuleId0024); // Removed grain class not retired

    public sealed override FixAllProvider GetFixAllProvider() => OrleansContractsFixAllProvider.Instance;

    public sealed override Task RegisterCodeFixesAsync(CodeFixContext context)
    {
        var validDiagnostics = context.Diagnostics.Where(HasRequiredProperties).ToImmutableArray();
        if (!validDiagnostics.IsEmpty)
        {
            context.RegisterCodeFix(
                CodeAction.Create(
                    title: RegenerateCodeActionTitle,
                    createChangedSolution: cancellationToken => RegenerateOrleansContractsFileAsync(context.Document.Project, cancellationToken),
                    equivalenceKey: RegenerateCodeActionEquivalenceKey),
                validDiagnostics);
        }

        foreach (var diagnostic in context.Diagnostics)
        {
            switch (diagnostic.Id)
            {
                case GrainInterfaceVersionAnalyzer.RuleId0016:
                    RegisterAddInterfaceCodeFix(context, diagnostic);
                    break;
                case GrainInterfaceVersionAnalyzer.RuleId0017:
                    RegisterUpdateVersionCodeFix(context, diagnostic);
                    break;
                case GrainInterfaceVersionAnalyzer.RuleId0018:
                    RegisterAddMemberCodeFix(context, diagnostic);
                    break;
                case GrainInterfaceVersionAnalyzer.RuleId0019:
                    RegisterRetireInterfaceCodeFix(context, diagnostic);
                    break;
                case GrainInterfaceVersionAnalyzer.RuleId0022:
                    RegisterAddGrainClassCodeFix(context, diagnostic);
                    break;
                case GrainInterfaceVersionAnalyzer.RuleId0023:
                    RegisterUpdateGrainClassAliasCodeFix(context, diagnostic);
                    break;
                case GrainInterfaceVersionAnalyzer.RuleId0024:
                    RegisterRetireGrainClassCodeFix(context, diagnostic);
                    break;
            }
        }

        return Task.CompletedTask;
    }

    private static bool HasRequiredProperties(Diagnostic diagnostic)
        => diagnostic.Id switch
        {
            GrainInterfaceVersionAnalyzer.RuleId0016
                => HasProperty(diagnostic, GrainInterfaceVersionAnalyzer.InterfaceNamePropertyKey),
            GrainInterfaceVersionAnalyzer.RuleId0017
                => HasProperty(diagnostic, GrainInterfaceVersionAnalyzer.InterfaceNamePropertyKey)
                    && HasProperty(diagnostic, GrainInterfaceVersionAnalyzer.ActualVersionPropertyKey),
            GrainInterfaceVersionAnalyzer.RuleId0018
                => HasProperty(diagnostic, GrainInterfaceVersionAnalyzer.InterfaceNamePropertyKey)
                    && HasProperty(diagnostic, GrainInterfaceVersionAnalyzer.MemberNamePropertyKey)
                    && HasProperty(diagnostic, GrainInterfaceVersionAnalyzer.MemberWireIdentityPropertyKey),
            GrainInterfaceVersionAnalyzer.RuleId0019
                => HasProperty(diagnostic, GrainInterfaceVersionAnalyzer.InterfaceNamePropertyKey),
            GrainInterfaceVersionAnalyzer.RuleId0020 => true,
            GrainInterfaceVersionAnalyzer.RuleId0022
                or GrainInterfaceVersionAnalyzer.RuleId0023
                or GrainInterfaceVersionAnalyzer.RuleId0024
                => HasProperty(diagnostic, GrainInterfaceVersionAnalyzer.ClassNamePropertyKey),
            _ => false
        };

    private static bool HasProperty(Diagnostic diagnostic, string propertyName)
        => diagnostic.Properties.TryGetValue(propertyName, out var value)
            && !string.IsNullOrEmpty(value);

    private static async Task<Solution> RegenerateOrleansContractsFileAsync(
        Project project,
        CancellationToken cancellationToken)
    {
        var result = await CreateProjectRegenerationAsync(project, cancellationToken).ConfigureAwait(false);
        return result is null
            ? project.Solution
            : ApplyProjectRegeneration(project.Solution, result);
    }

    private static async Task<ProjectRegeneration?> CreateProjectRegenerationAsync(
        Project project,
        CancellationToken cancellationToken)
    {
        var compilation = await project.GetCompilationAsync(cancellationToken).ConfigureAwait(false);
        if (compilation is null)
        {
            return null;
        }

        var contractsFile = FindContractsDocument(project);
        var existingText = contractsFile is null
            ? null
            : await contractsFile.GetTextAsync(cancellationToken).ConfigureAwait(false);
        var newLine = existingText is null ? DefaultNewLine : GetNewLine(existingText);
        var lines = new List<string>();
        var activeInterfaceIdentities = new HashSet<string>(StringComparer.Ordinal);
        var activeConventionInterfaceNames = new HashSet<string>(StringComparer.Ordinal);
        var activeInterfaces = new Dictionary<string, INamedTypeSymbol>(StringComparer.Ordinal);
        var activeInterfacesByName = new Dictionary<string, INamedTypeSymbol>(StringComparer.Ordinal);
        var activeClassIdentities = new HashSet<string>(StringComparer.Ordinal);
        var activeConventionClassNames = new HashSet<string>(StringComparer.Ordinal);
        var iAddressableType = compilation.GetTypeByMetadataName(Constants.IAddressibleFullyQualifiedName);
        var generatedCodeTrees = new Dictionary<SyntaxTree, bool>();
        var semanticModels = new Dictionary<SyntaxTree, SemanticModel>();
        var hasActiveContracts = false;

        foreach (var type in GetAllSourceTypes(
            compilation.Assembly.GlobalNamespace,
            compilation,
            generatedCodeTrees,
            semanticModels)
            .Where(type =>
                type.TypeKind == TypeKind.Interface
                    && iAddressableType is not null
                    && !SymbolEqualityComparer.Default.Equals(type, iAddressableType)
                    && type.AllInterfaces.Any(candidate => SymbolEqualityComparer.Default.Equals(candidate, iAddressableType))
                || type.TypeKind == TypeKind.Class
                    && !type.IsAbstract
                    && type.IsGrainClass())
            .OrderBy(GetFullyQualifiedName, StringComparer.Ordinal))
        {
            if (type.TypeKind == TypeKind.Interface
                && iAddressableType is not null
                && !SymbolEqualityComparer.Default.Equals(type, iAddressableType)
                && type.AllInterfaces.Any(candidate => SymbolEqualityComparer.Default.Equals(candidate, iAddressableType)))
            {
                hasActiveContracts = true;
                AppendInterface(
                    lines,
                    type,
                    activeInterfaceIdentities,
                    activeConventionInterfaceNames,
                    activeInterfaces,
                    activeInterfacesByName);
            }
            else if (type.TypeKind == TypeKind.Class && !type.IsAbstract && type.IsGrainClass())
            {
                hasActiveContracts = true;
                AppendGrainClass(lines, type, activeClassIdentities, activeConventionClassNames);
            }
        }

        var hasExistingManifest = existingText is { Length: > 0 };
        if (!hasActiveContracts && !hasExistingManifest)
        {
            return null;
        }

        if (existingText is { Length: > 0 })
        {
            AppendHistoricalContracts(
                lines,
                existingText.ToString(),
                activeInterfaceIdentities,
                activeConventionInterfaceNames,
                activeInterfaces,
                activeInterfacesByName,
                activeClassIdentities,
                activeConventionClassNames);
        }

        var content = SortContractEntries(string.Join(newLine, lines), newLine);
        var newText = SourceText.From(content, Utf8NoBom);
        var filePath = GetConfiguredContractsPath(project);
        return new ProjectRegeneration(
            project.Id,
            contractsFile?.Id,
            Path.GetFileName(filePath),
            filePath,
            newText);
    }

    private static Solution ApplyProjectRegeneration(Solution solution, ProjectRegeneration result)
    {
        if (result.DocumentId is { } documentId
            && solution.GetAdditionalDocument(documentId) is not null)
        {
            return solution.WithAdditionalDocumentText(documentId, result.Text);
        }

        return solution.AddAdditionalDocument(
            DocumentId.CreateNewId(result.ProjectId),
            result.DocumentName,
            result.Text,
            filePath: result.FilePath);
    }

    private static TextDocument? FindContractsDocument(Project project)
    {
        var configuredPath = GetConfiguredContractsPath(project);
        var configuredDocument = project.AdditionalDocuments.FirstOrDefault(document =>
            PathsEqual(document.FilePath ?? document.Name, configuredPath));
        if (configuredDocument is not null)
        {
            return configuredDocument;
        }

        foreach (var additionalFile in project.AnalyzerOptions.AdditionalFiles)
        {
            if (!Path.GetFileName(additionalFile.Path)
                    .Equals(Constants.OrleansContractsFileName, StringComparison.OrdinalIgnoreCase)
                && (!project.AnalyzerOptions.AnalyzerConfigOptionsProvider.GetOptions(additionalFile)
                    .TryGetValue("build_metadata.AdditionalFiles.OrleansContractsFile", out var value)
                    || !string.Equals(value, "true", StringComparison.OrdinalIgnoreCase)))
            {
                continue;
            }

            var document = project.AdditionalDocuments.FirstOrDefault(candidate =>
                candidate.FilePath is { } candidatePath
                    && PathsEqual(candidatePath, additionalFile.Path));
            if (document is not null)
            {
                return document;
            }
        }

        return project.AdditionalDocuments.FirstOrDefault(document =>
            Path.GetFileName(document.FilePath ?? document.Name)
                .Equals(Constants.OrleansContractsFileName, StringComparison.OrdinalIgnoreCase));
    }

    private static bool PathsEqual(string left, string right)
    {
        left = NormalizePathSeparators(left);
        right = NormalizePathSeparators(right);
        if (Path.IsPathRooted(left) && Path.IsPathRooted(right))
        {
            left = Path.GetFullPath(left);
            right = Path.GetFullPath(right);
        }

        return string.Equals(left, right, FilePathComparison);
    }

    private static string GetConfiguredContractsPath(Project project)
    {
        if (project.AnalyzerOptions.AnalyzerConfigOptionsProvider.GlobalOptions.TryGetValue(
                "build_property.OrleansContractsPath",
                out var configuredPath)
            && !string.IsNullOrWhiteSpace(configuredPath))
        {
            configuredPath = NormalizePathSeparators(configuredPath);
            if (Path.IsPathRooted(configuredPath))
            {
                return configuredPath;
            }

            if (Path.GetDirectoryName(project.FilePath) is { } projectDirectory)
            {
                return Path.Combine(projectDirectory, configuredPath);
            }

            return configuredPath;
        }

        return Path.GetDirectoryName(project.FilePath) is { } directory
            ? Path.Combine(directory, Constants.OrleansContractsFileName)
            : Constants.OrleansContractsFileName;
    }

    private static string NormalizePathSeparators(string path)
        => path.Replace('\\', Path.DirectorySeparatorChar).Replace('/', Path.DirectorySeparatorChar);

    private static IEnumerable<INamedTypeSymbol> GetAllSourceTypes(
        INamespaceSymbol @namespace,
        Compilation compilation,
        Dictionary<SyntaxTree, bool> generatedCodeTrees,
        Dictionary<SyntaxTree, SemanticModel> semanticModels)
    {
        foreach (var type in @namespace.GetTypeMembers())
        {
            foreach (var result in GetSourceTypeAndNestedTypes(
                type,
                compilation,
                generatedCodeTrees,
                semanticModels))
            {
                yield return result;
            }
        }

        foreach (var childNamespace in @namespace.GetNamespaceMembers())
        {
            foreach (var result in GetAllSourceTypes(
                childNamespace,
                compilation,
                generatedCodeTrees,
                semanticModels))
            {
                yield return result;
            }
        }
    }

    private static IEnumerable<INamedTypeSymbol> GetSourceTypeAndNestedTypes(
        INamedTypeSymbol type,
        Compilation compilation,
        Dictionary<SyntaxTree, bool> generatedCodeTrees,
        Dictionary<SyntaxTree, SemanticModel> semanticModels)
    {
        if (!type.IsImplicitlyDeclared
            && !IsGeneratedCode(type, compilation, generatedCodeTrees, semanticModels)
            && type.Locations.Any(location => location.IsInSource))
        {
            yield return type;
        }

        foreach (var nestedType in type.GetTypeMembers())
        {
            foreach (var result in GetSourceTypeAndNestedTypes(
                nestedType,
                compilation,
                generatedCodeTrees,
                semanticModels))
            {
                yield return result;
            }
        }
    }

    private static bool IsGeneratedCode(
        INamedTypeSymbol type,
        Compilation compilation,
        Dictionary<SyntaxTree, bool> generatedCodeTrees,
        Dictionary<SyntaxTree, SemanticModel> semanticModels)
    {
        var declarations = type.DeclaringSyntaxReferences;
        return !declarations.IsEmpty
            && declarations.All(declaration =>
                IsGeneratedCode(declaration.SyntaxTree, generatedCodeTrees)
                || HasGeneratedCodeAttribute(declaration.GetSyntax(), compilation, semanticModels));
    }

    private static bool HasGeneratedCodeAttribute(
        SyntaxNode declaration,
        Compilation compilation,
        Dictionary<SyntaxTree, SemanticModel> semanticModels)
    {
        if (!semanticModels.TryGetValue(declaration.SyntaxTree, out var semanticModel))
        {
            semanticModel = compilation.GetSemanticModel(declaration.SyntaxTree);
            semanticModels[declaration.SyntaxTree] = semanticModel;
        }

        return declaration.AncestorsAndSelf()
            .OfType<TypeDeclarationSyntax>()
            .SelectMany(type => type.AttributeLists)
            .SelectMany(list => list.Attributes)
            .Select(attribute => semanticModel.GetSymbolInfo(attribute).Symbol as IMethodSymbol)
            .Select(constructor => constructor?.ContainingType.ToDisplayString())
            .Any(attributeType => attributeType is
                "System.CodeDom.Compiler.GeneratedCodeAttribute"
                or "System.Runtime.CompilerServices.CompilerGeneratedAttribute");
    }

    private static bool IsGeneratedCode(
        SyntaxTree syntaxTree,
        Dictionary<SyntaxTree, bool> generatedCodeTrees)
    {
        if (generatedCodeTrees.TryGetValue(syntaxTree, out var result))
        {
            return result;
        }

        var fileName = Path.GetFileName(syntaxTree.FilePath);
        result = fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase);
        if (!result)
        {
            var text = syntaxTree.GetText();
            var prefixLength = Math.Min(text.Length, 2048);
            result = text.ToString(new TextSpan(0, prefixLength))
                .IndexOf("<auto-generated", StringComparison.OrdinalIgnoreCase) >= 0;
        }

        generatedCodeTrees[syntaxTree] = result;
        return result;
    }

    private static void AppendInterface(
        List<string> lines,
        INamedTypeSymbol type,
        HashSet<string> activeInterfaceIdentities,
        HashSet<string> activeConventionInterfaceNames,
        Dictionary<string, INamedTypeSymbol> activeInterfaces,
        Dictionary<string, INamedTypeSymbol> activeInterfacesByName)
    {
        AppendBlockSeparator(lines);
        var interfaceName = GetFullyQualifiedName(type);
        var explicitInterfaceType = GetGrainInterfaceTypeFromAttributes(type);
        var interfaceType = GrainInterfaceVersionAnalyzer.GetGrainInterfaceType(type);
        activeInterfaceIdentities.Add(interfaceType);
        activeInterfaces[interfaceType] = type;
        activeInterfacesByName[interfaceName] = type;
        if (explicitInterfaceType is null
            || string.Equals(
                explicitInterfaceType,
                GrainInterfaceVersionAnalyzer.GetDefaultGrainInterfaceType(type),
                StringComparison.Ordinal))
        {
            activeConventionInterfaceNames.Add(interfaceName);
        }
        if (GrainInterfaceVersionAnalyzer.IdentityDiffersFromClrName(explicitInterfaceType, type))
        {
            lines.Add($"# {interfaceName}");
        }

        lines.Add($"interface [GrainInterfaceType(\"{interfaceType}\")] {interfaceName} [Version({GetVersionFromAttributes(type)})]");
        foreach (var member in type.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(member => member.MethodKind == MethodKind.Ordinary && !member.IsStatic)
            .OrderBy(GrainInterfaceVersionAnalyzer.GetManifestMethodSignature, StringComparer.Ordinal))
        {
            lines.Add($"  {GrainInterfaceFileParser.FormatMemberDeclaration(
                GrainInterfaceVersionAnalyzer.GetManifestMethodSignature(member),
                GrainInterfaceVersionAnalyzer.GetMethodWireIdentity(member))}");
        }
    }

    private static void AppendGrainClass(
        List<string> lines,
        INamedTypeSymbol type,
        HashSet<string> activeClassIdentities,
        HashSet<string> activeConventionClassNames)
    {
        AppendBlockSeparator(lines);
        var className = GetFullyQualifiedName(type);
        var explicitGrainType = GetGrainTypeFromAttributes(type);
        var grainType = GrainInterfaceVersionAnalyzer.GetGrainType(type);
        activeClassIdentities.Add(grainType);
        if (explicitGrainType is null
            || string.Equals(
                explicitGrainType,
                GrainInterfaceVersionAnalyzer.GetDefaultGrainType(type),
                StringComparison.Ordinal))
        {
            activeConventionClassNames.Add(className);
        }
        if (GrainInterfaceVersionAnalyzer.IdentityDiffersFromClrName(explicitGrainType, type))
        {
            lines.Add($"# {className}");
        }

        lines.Add($"class [GrainType(\"{grainType}\")] {className}");
    }

    private static void AppendHistoricalContracts(
        List<string> result,
        string existingContent,
        HashSet<string> activeInterfaceIdentities,
        HashSet<string> activeConventionInterfaceNames,
        Dictionary<string, INamedTypeSymbol> activeInterfaces,
        Dictionary<string, INamedTypeSymbol> activeInterfacesByName,
        HashSet<string> activeClassIdentities,
        HashSet<string> activeConventionClassNames)
    {
        var lines = existingContent.Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.None);
        for (var index = 0; index < lines.Length; index++)
        {
            var declaration = lines[index].Trim();
            var isInterface = GrainInterfaceFileParser.TryGetInterfaceName(declaration, out var contractName);
            var isClass = !isInterface && GrainInterfaceFileParser.TryGetGrainClassName(declaration, out contractName);
            if (!isInterface && !isClass)
            {
                continue;
            }

            string? explicitIdentity = null;
            if (isInterface && GrainInterfaceFileParser.TryGetGrainInterfaceType(declaration, out var interfaceType))
            {
                explicitIdentity = interfaceType;
            }
            else if (isClass && GrainInterfaceFileParser.TryGetGrainClassType(declaration, out var grainType))
            {
                explicitIdentity = grainType;
            }

            var isActive = isInterface
                ? explicitIdentity is null
                    ? activeInterfaceIdentities.Contains(
                        GrainInterfaceVersionAnalyzer.GetDefaultGrainInterfaceType(contractName))
                        || activeConventionInterfaceNames.Contains(contractName)
                    : activeInterfaceIdentities.Contains(explicitIdentity)
                : explicitIdentity is null
                    ? activeClassIdentities.Contains(GrainInterfaceVersionAnalyzer.GetDefaultGrainType(contractName))
                        || activeConventionClassNames.Contains(contractName)
                    : activeClassIdentities.Contains(explicitIdentity);
            var blockEnd = index + 1;
            while (blockEnd < lines.Length)
            {
                if (GrainInterfaceFileParser.TryGetContractName(lines[blockEnd], out _))
                {
                    break;
                }

                if (lines[blockEnd].TrimStart().StartsWith("# ", StringComparison.Ordinal)
                    && blockEnd + 1 < lines.Length
                    && GrainInterfaceFileParser.TryGetContractName(lines[blockEnd + 1], out _))
                {
                    break;
                }

                blockEnd++;
            }

            if (!isActive)
            {
                AppendBlockSeparator(result);
                if (index > 0
                    && lines[index - 1].TrimStart().StartsWith("# ", StringComparison.Ordinal)
                    && !IsGeneratedHeaderLine(lines[index - 1].TrimStart()))
                {
                    result.Add(lines[index - 1].Trim());
                }

                for (var blockIndex = index; blockIndex < blockEnd; blockIndex++)
                {
                    result.Add(blockIndex == index
                        && !declaration.StartsWith(GrainInterfaceVersionAnalyzer.RetiredPrefix, StringComparison.Ordinal)
                            ? $"{GrainInterfaceVersionAnalyzer.RetiredPrefix} {declaration}"
                            : lines[blockIndex]);
                }
            }
            else if (isInterface)
            {
                var interfaceIdentity = explicitIdentity
                    ?? GrainInterfaceVersionAnalyzer.GetDefaultGrainInterfaceType(contractName);
                if (activeInterfaces.TryGetValue(interfaceIdentity, out var activeInterface)
                    || activeConventionInterfaceNames.Contains(contractName)
                    && activeInterfacesByName.TryGetValue(contractName, out activeInterface))
                {
                    MergeHistoricalMembers(
                        result,
                        lines,
                        index,
                        blockEnd,
                        contractName,
                        activeInterface);
                }
            }

            index = blockEnd - 1;
        }
    }

    private static void MergeHistoricalMembers(
        List<string> result,
        string[] historicalLines,
        int historicalDeclarationIndex,
        int historicalBlockEnd,
        string historicalInterfaceName,
        INamedTypeSymbol activeInterface)
    {
        var generatedDeclarationIndex = -1;
        var activeInterfaceIdentity = GrainInterfaceVersionAnalyzer.GetGrainInterfaceType(activeInterface);
        var activeInterfaceName = GetFullyQualifiedName(activeInterface);
        for (var index = 0; index < result.Count; index++)
        {
            if (!GrainInterfaceFileParser.TryGetInterfaceName(result[index], out var generatedInterfaceName))
            {
                continue;
            }

            var generatedIdentity = GrainInterfaceFileParser.TryGetGrainInterfaceType(
                result[index],
                out var generatedInterfaceType)
                    ? generatedInterfaceType
                    : GrainInterfaceVersionAnalyzer.GetDefaultGrainInterfaceType(generatedInterfaceName);
            if (string.Equals(generatedIdentity, activeInterfaceIdentity, StringComparison.Ordinal)
                || string.Equals(generatedInterfaceName, activeInterfaceName, StringComparison.Ordinal))
            {
                generatedDeclarationIndex = index;
                break;
            }
        }

        if (generatedDeclarationIndex < 0)
        {
            return;
        }

        var generatedBlockEnd = generatedDeclarationIndex + 1;
        var generatedMembers = new HashSet<string>(StringComparer.Ordinal);
        while (generatedBlockEnd < result.Count)
        {
            if (GrainInterfaceFileParser.TryGetContractName(result[generatedBlockEnd], out _)
                || result[generatedBlockEnd].TrimStart().StartsWith("# ", StringComparison.Ordinal)
                && generatedBlockEnd + 1 < result.Count
                && GrainInterfaceFileParser.TryGetContractName(result[generatedBlockEnd + 1], out _))
            {
                break;
            }

            if (GrainInterfaceFileParser.TryGetMemberDeclaration(
                result[generatedBlockEnd],
                out var memberSignature,
                out var memberWireIdentity))
            {
                generatedMembers.Add(GetHistoricalMemberKey(
                    memberSignature,
                    memberWireIdentity,
                    historicalInterfaceName));
            }

            generatedBlockEnd++;
        }

        string? pendingComment = null;
        for (var index = historicalDeclarationIndex + 1; index < historicalBlockEnd; index++)
        {
            var line = historicalLines[index];
            if (line.TrimStart().StartsWith("# ", StringComparison.Ordinal))
            {
                pendingComment = line.Trim();
                continue;
            }

            if (!GrainInterfaceFileParser.TryGetMemberDeclaration(
                line,
                out var memberSignature,
                out var memberWireIdentity))
            {
                pendingComment = null;
                continue;
            }

            if (activeInterface.GetMembers()
                .OfType<IMethodSymbol>()
                .Any(member => member.MethodKind == MethodKind.Ordinary
                    && !member.IsStatic
                    && GrainInterfaceVersionAnalyzer.IsMatchingHistoricalMember(
                        historicalInterfaceName,
                        memberSignature,
                        memberWireIdentity,
                        member)))
            {
                pendingComment = null;
                continue;
            }

            var normalizedSignature = GrainInterfaceVersionAnalyzer.NormalizeStoredMemberSignature(
                memberSignature,
                historicalInterfaceName);
            var historicalMemberKey = GetHistoricalMemberKey(
                memberSignature,
                memberWireIdentity,
                historicalInterfaceName);
            if (generatedMembers.Add(historicalMemberKey))
            {
                if (pendingComment is not null)
                {
                    result.Insert(generatedBlockEnd++, $"  {pendingComment}");
                }

                result.Insert(generatedBlockEnd++, $"  {GrainInterfaceFileParser.FormatMemberDeclaration(
                    normalizedSignature,
                    memberWireIdentity)}");
            }

            pendingComment = null;
        }
    }

    private static string GetHistoricalMemberKey(
        string signature,
        MethodWireIdentity wireIdentity,
        string interfaceName)
        => GrainInterfaceVersionAnalyzer.NormalizeStoredMemberSignature(
            GrainInterfaceFileParser.GetCanonicalMemberSignature(signature, wireIdentity),
            interfaceName);

    private static void AppendBlockSeparator(List<string> lines)
    {
        while (lines.Count > 0 && string.IsNullOrWhiteSpace(lines[lines.Count - 1]))
        {
            lines.RemoveAt(lines.Count - 1);
        }

        if (lines.Count > 0)
        {
            lines.Add(string.Empty);
        }
    }

    private static string GetFullyQualifiedName(INamedTypeSymbol type)
        => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", "");

    private sealed class OrleansContractsFixAllProvider : FixAllProvider
    {
        public static OrleansContractsFixAllProvider Instance { get; } = new();

        public override Task<CodeAction?> GetFixAsync(FixAllContext fixAllContext)
        {
            if (!string.Equals(
                fixAllContext.CodeActionEquivalenceKey,
                RegenerateCodeActionEquivalenceKey,
                StringComparison.Ordinal))
            {
                return Task.FromResult<CodeAction?>(null);
            }

            var title = fixAllContext.Scope == FixAllScope.Solution
                ? "Regenerate OrleansContracts.txt in solution"
                : "Regenerate OrleansContracts.txt in project";
            return Task.FromResult<CodeAction?>(CodeAction.Create(
                title,
                cancellationToken => RegenerateFixAllAsync(fixAllContext, cancellationToken),
                RegenerateCodeActionEquivalenceKey));
        }

        private static async Task<Solution> RegenerateFixAllAsync(
            FixAllContext fixAllContext,
            CancellationToken cancellationToken)
        {
            var solution = fixAllContext.Solution;
            if (fixAllContext.Scope != FixAllScope.Solution)
            {
                return await RegenerateOrleansContractsFileAsync(
                    fixAllContext.Project,
                    cancellationToken).ConfigureAwait(false);
            }

            var projects = GetProjectsToRegenerate(solution)
                .Where(project => project.Language == LanguageNames.CSharp
                    && IsContractsAnalyzerEnabled(project))
                .OrderBy(project => project.FilePath ?? project.Name, StringComparer.Ordinal)
                .ToArray();
            if (projects.Length == 0)
            {
                return solution;
            }

            var results = new ProjectRegeneration?[projects.Length];
            var nextProjectIndex = -1;
            var workerCount = Math.Min(MaxConcurrentProjectRegenerations, projects.Length);

            async Task RegenerateProjectsAsync()
            {
                while (true)
                {
                    var projectIndex = Interlocked.Increment(ref nextProjectIndex);
                    if (projectIndex >= projects.Length)
                    {
                        return;
                    }

                    cancellationToken.ThrowIfCancellationRequested();
                    results[projectIndex] = await CreateProjectRegenerationAsync(
                        projects[projectIndex],
                        cancellationToken).ConfigureAwait(false);
                }
            }

            var workers = new Task[workerCount];
            for (var workerIndex = 0; workerIndex < workers.Length; workerIndex++)
            {
                workers[workerIndex] = RegenerateProjectsAsync();
            }

            await Task.WhenAll(workers).ConfigureAwait(false);
            foreach (var result in results)
            {
                if (result is not null)
                {
                    solution = ApplyProjectRegeneration(solution, result);
                }
            }

            return solution;
        }
    }

    private static bool IsContractsAnalyzerEnabled(Project project)
        => project.AnalyzerOptions.AnalyzerConfigOptionsProvider.GlobalOptions.TryGetValue(
            $"build_property.{GrainInterfaceVersionAnalyzer.EnableAnalyzerPropertyName}",
            out var value)
            && string.Equals(value, "true", StringComparison.OrdinalIgnoreCase);

    private static IEnumerable<Project> GetProjectsToRegenerate(Solution solution)
    {
        var projects = solution.Projects.ToArray();
        var dependents = new Dictionary<ProjectId, List<ProjectId>>();
        var orleansReachableProjects = new HashSet<ProjectId>();
        var pendingProjects = new Queue<ProjectId>();
        foreach (var project in projects)
        {
            if (string.Equals(
                    project.AssemblyName,
                    OrleansCoreAbstractionsAssemblyName,
                    StringComparison.OrdinalIgnoreCase)
                || project.MetadataReferences.Any(IsOrleansCoreAbstractionsReference))
            {
                orleansReachableProjects.Add(project.Id);
                pendingProjects.Enqueue(project.Id);
            }

            foreach (var projectReference in project.ProjectReferences)
            {
                if (!dependents.TryGetValue(projectReference.ProjectId, out var projectDependents))
                {
                    dependents.Add(projectReference.ProjectId, projectDependents = []);
                }

                projectDependents.Add(project.Id);
            }
        }

        while (pendingProjects.Count > 0)
        {
            var projectId = pendingProjects.Dequeue();
            if (!dependents.TryGetValue(projectId, out var projectDependents))
            {
                continue;
            }

            foreach (var dependentProjectId in projectDependents)
            {
                if (orleansReachableProjects.Add(dependentProjectId))
                {
                    pendingProjects.Enqueue(dependentProjectId);
                }
            }
        }

        foreach (var project in projects)
        {
            if (orleansReachableProjects.Contains(project.Id)
                || HasExistingContractsManifest(project))
            {
                yield return project;
            }
        }
    }

    private static bool HasExistingContractsManifest(Project project)
    {
        if (FindContractsDocument(project) is { } document
            && document.TryGetText(out var text)
            && text.Length > 0)
        {
            return true;
        }

        var configuredPath = GetConfiguredContractsPath(project);
        foreach (var additionalFile in project.AnalyzerOptions.AdditionalFiles)
        {
            if (PathsEqual(additionalFile.Path, configuredPath)
                && project.AnalyzerOptions.AnalyzerConfigOptionsProvider.GetOptions(additionalFile)
                    .TryGetValue(OrleansContractsFileExistsMetadata, out var value)
                && string.Equals(value, "true", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }

    private static bool IsOrleansCoreAbstractionsReference(MetadataReference reference)
        => reference.Display is { } display
            && string.Equals(
                Path.GetFileNameWithoutExtension(display),
                OrleansCoreAbstractionsAssemblyName,
                StringComparison.OrdinalIgnoreCase);

    private sealed class ProjectRegeneration(
        ProjectId projectId,
        DocumentId? documentId,
        string documentName,
        string filePath,
        SourceText text)
    {
        public ProjectId ProjectId { get; } = projectId;

        public DocumentId? DocumentId { get; } = documentId;

        public string DocumentName { get; } = documentName;

        public string FilePath { get; } = filePath;

        public SourceText Text { get; } = text;
    }

    private static void RegisterAddInterfaceCodeFix(CodeFixContext context, Diagnostic diagnostic)
    {
        if (!diagnostic.Properties.TryGetValue(GrainInterfaceVersionAnalyzer.InterfaceNamePropertyKey, out var interfaceName) ||
            string.IsNullOrEmpty(interfaceName))
        {
            return;
        }

        diagnostic.Properties.TryGetValue(GrainInterfaceVersionAnalyzer.GrainInterfaceTypePropertyKey, out var grainInterfaceType);
        context.RegisterCodeFix(
            CodeAction.Create(
                title: Resources.AddToOrleansContractsFileTitle,
                createChangedSolution: ct => AddInterfaceToFileAsync(context.Document, interfaceName!, grainInterfaceType, ct),
                equivalenceKey: GrainInterfaceVersionAnalyzer.RuleId0016),
            diagnostic);
    }

    private static void RegisterUpdateVersionCodeFix(CodeFixContext context, Diagnostic diagnostic)
    {
        if (!diagnostic.Properties.TryGetValue(GrainInterfaceVersionAnalyzer.InterfaceNamePropertyKey, out var interfaceName) ||
            string.IsNullOrEmpty(interfaceName))
        {
            return;
        }

        if (!diagnostic.Properties.TryGetValue(GrainInterfaceVersionAnalyzer.ActualVersionPropertyKey, out var actualVersion) ||
            string.IsNullOrEmpty(actualVersion))
        {
            return;
        }

        diagnostic.Properties.TryGetValue(GrainInterfaceVersionAnalyzer.GrainInterfaceTypePropertyKey, out var grainInterfaceType);
        context.RegisterCodeFix(
            CodeAction.Create(
                title: Resources.UpdateGrainInterfaceVersionTitle,
                createChangedSolution: ct => UpdateVersionInFileAsync(context.Document, interfaceName!, grainInterfaceType, actualVersion!, ct),
                equivalenceKey: GrainInterfaceVersionAnalyzer.RuleId0017),
            diagnostic);
    }

    private static void RegisterAddMemberCodeFix(CodeFixContext context, Diagnostic diagnostic)
    {
        if (!diagnostic.Properties.TryGetValue(GrainInterfaceVersionAnalyzer.InterfaceNamePropertyKey, out var interfaceName) ||
            string.IsNullOrEmpty(interfaceName))
        {
            return;
        }

        if (!diagnostic.Properties.TryGetValue(GrainInterfaceVersionAnalyzer.MemberNamePropertyKey, out var memberSignature) ||
            string.IsNullOrEmpty(memberSignature))
        {
            return;
        }

        diagnostic.Properties.TryGetValue(
            GrainInterfaceVersionAnalyzer.MemberWireIdentityPropertyKey,
            out var memberWireIdentity);
        diagnostic.Properties.TryGetValue(GrainInterfaceVersionAnalyzer.GrainInterfaceTypePropertyKey, out var grainInterfaceType);

        context.RegisterCodeFix(
            CodeAction.Create(
                title: Resources.AddToOrleansContractsFileTitle,
                createChangedSolution: ct => AddMemberToFileAsync(
                    context.Document,
                    interfaceName!,
                    grainInterfaceType,
                    memberSignature!,
                    memberWireIdentity!,
                    ct),
                equivalenceKey: GrainInterfaceVersionAnalyzer.RuleId0018),
            diagnostic);
    }

    private static void RegisterRetireInterfaceCodeFix(CodeFixContext context, Diagnostic diagnostic)
    {
        if (!diagnostic.Properties.TryGetValue(GrainInterfaceVersionAnalyzer.InterfaceNamePropertyKey, out var interfaceName) ||
            string.IsNullOrEmpty(interfaceName))
        {
            return;
        }

        diagnostic.Properties.TryGetValue(GrainInterfaceVersionAnalyzer.GrainInterfaceTypePropertyKey, out var grainInterfaceType);
        context.RegisterCodeFix(
            CodeAction.Create(
                title: Resources.RetireGrainInterfaceTitle,
                createChangedSolution: ct => RetireInterfaceInFileAsync(context.Document, interfaceName!, grainInterfaceType, ct),
                equivalenceKey: GrainInterfaceVersionAnalyzer.RuleId0019),
            diagnostic);
    }

    private static void RegisterAddGrainClassCodeFix(CodeFixContext context, Diagnostic diagnostic)
    {
        if (!diagnostic.Properties.TryGetValue(GrainInterfaceVersionAnalyzer.ClassNamePropertyKey, out var className) ||
            string.IsNullOrEmpty(className))
        {
            return;
        }

        context.RegisterCodeFix(
            CodeAction.Create(
                title: Resources.AddToOrleansContractsFileTitle,
                createChangedSolution: ct => AddGrainClassToFileAsync(context.Document, className!, ct),
                equivalenceKey: GrainInterfaceVersionAnalyzer.RuleId0022),
            diagnostic);
    }

    private static void RegisterUpdateGrainClassAliasCodeFix(CodeFixContext context, Diagnostic diagnostic)
    {
        if (!diagnostic.Properties.TryGetValue(GrainInterfaceVersionAnalyzer.ClassNamePropertyKey, out var className) ||
            string.IsNullOrEmpty(className))
        {
            return;
        }

        diagnostic.Properties.TryGetValue(GrainInterfaceVersionAnalyzer.ActualAliasPropertyKey, out var alias);
        context.RegisterCodeFix(
            CodeAction.Create(
                title: Resources.UpdateGrainClassAliasTitle,
                createChangedSolution: ct => UpdateGrainClassAliasInFileAsync(context.Document, className!, alias, ct),
                equivalenceKey: GrainInterfaceVersionAnalyzer.RuleId0023),
            diagnostic);
    }

    private static void RegisterRetireGrainClassCodeFix(CodeFixContext context, Diagnostic diagnostic)
    {
        if (!diagnostic.Properties.TryGetValue(GrainInterfaceVersionAnalyzer.ClassNamePropertyKey, out var className) ||
            string.IsNullOrEmpty(className))
        {
            return;
        }

        diagnostic.Properties.TryGetValue(GrainInterfaceVersionAnalyzer.ActualAliasPropertyKey, out var grainType);
        context.RegisterCodeFix(
            CodeAction.Create(
                title: Resources.RetireGrainClassTitle,
                createChangedSolution: ct => RetireGrainClassInFileAsync(context.Document, className!, grainType, ct),
                equivalenceKey: GrainInterfaceVersionAnalyzer.RuleId0024),
            diagnostic);
    }

    private static async Task<Solution> AddGrainClassToFileAsync(
        Document document,
        string className,
        CancellationToken cancellationToken)
    {
        var project = document.Project;
        var solution = project.Solution;
        var semanticModel = await document.GetSemanticModelAsync(cancellationToken).ConfigureAwait(false);
        var root = await document.GetSyntaxRootAsync(cancellationToken).ConfigureAwait(false);
        if (semanticModel is null || root is null)
        {
            return solution;
        }

        var declaration = root.DescendantNodes()
            .OfType<TypeDeclarationSyntax>()
            .FirstOrDefault(candidate =>
            {
                var symbol = semanticModel.GetDeclaredSymbol(candidate, cancellationToken) as INamedTypeSymbol;
                var fullName = symbol?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", "");
                return symbol?.TypeKind == TypeKind.Class && string.Equals(fullName, className, StringComparison.Ordinal);
            });
        if (declaration is null || semanticModel.GetDeclaredSymbol(declaration, cancellationToken) is not INamedTypeSymbol classSymbol)
        {
            return solution;
        }

        var explicitGrainType = GetGrainTypeFromAttributes(classSymbol);
        var grainType = GrainInterfaceVersionAnalyzer.GetGrainType(classSymbol);
        var classClrComment = GrainInterfaceVersionAnalyzer.IdentityDiffersFromClrName(explicitGrainType, classSymbol) ? className : null;
        var classLine = $"class [GrainType(\"{grainType}\")] {className}";
        var contractsFile = FindContractsDocument(project);
        if (contractsFile is null)
        {
            return solution;
        }

        var text = await contractsFile.GetTextAsync(cancellationToken).ConfigureAwait(false);
        if (text is null)
        {
            return solution;
        }

        var newLine = GetNewLine(text);
        var lines = text.ToString().Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.None);
        for (var i = 0; i < lines.Length; i++)
        {
            if (GrainInterfaceFileParser.TryGetGrainClassName(lines[i], out var declaredName)
                && string.Equals(declaredName, className, StringComparison.Ordinal))
            {
                var updatedLines = lines.ToList();
                i = SetClrCommentBefore(updatedLines, i, classClrComment);
                updatedLines[i] = classLine;
                var reactivatedContent = SortContractEntries(string.Join(newLine, updatedLines), newLine);
                return solution.WithAdditionalDocumentText(
                    contractsFile.Id,
                    Microsoft.CodeAnalysis.Text.SourceText.From(reactivatedContent, Utf8NoBom));
            }
        }

        var content = text.ToString().TrimEnd();
        if (content.Length > 0)
        {
            content += newLine + newLine;
        }

        if (classClrComment is not null)
        {
            content += $"# {classClrComment}{newLine}";
        }
        content = SortContractEntries(content + classLine, newLine);
        return solution.WithAdditionalDocumentText(
            contractsFile.Id,
            Microsoft.CodeAnalysis.Text.SourceText.From(content, Utf8NoBom));
    }

    private static async Task<Solution> UpdateGrainClassAliasInFileAsync(
        Document document,
        string className,
        string? alias,
        CancellationToken cancellationToken)
    {
        var project = document.Project;
        var contractsFile = FindContractsDocument(project);
        if (contractsFile is null)
        {
            return project.Solution;
        }

        var text = await contractsFile.GetTextAsync(cancellationToken).ConfigureAwait(false);
        if (text is null)
        {
            return project.Solution;
        }

        var newLine = GetNewLine(text);
        var replacement = string.IsNullOrEmpty(alias)
            ? $"class {className}"
            : $"class [GrainType(\"{alias}\")] {className}";
        var lines = text.ToString().Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.None).ToList();
        for (var i = 0; i < lines.Count; i++)
        {
            if (GrainInterfaceFileParser.TryGetGrainClassName(lines[i], out var declaredName)
                && string.Equals(declaredName, className, StringComparison.Ordinal))
            {
                var clrComment = IdentityDiffersFromClrName(alias, className) ? className : null;
                i = SetClrCommentBefore(lines, i, clrComment);
                lines[i] = replacement;
                break;
            }
        }

        var content = SortContractEntries(string.Join(newLine, lines), newLine);
        return project.Solution.WithAdditionalDocumentText(
            contractsFile.Id,
            Microsoft.CodeAnalysis.Text.SourceText.From(content, Utf8NoBom));
    }

    private static async Task<Solution> RetireGrainClassInFileAsync(
        Document document,
        string className,
        string? grainType,
        CancellationToken cancellationToken)
    {
        var project = document.Project;
        var contractsFile = FindContractsDocument(project);
        if (contractsFile is null)
        {
            return project.Solution;
        }

        var text = await contractsFile.GetTextAsync(cancellationToken).ConfigureAwait(false);
        if (text is null)
        {
            return project.Solution;
        }

        var newLine = GetNewLine(text);
        var lines = text.ToString().Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.None);
        for (var i = 0; i < lines.Length; i++)
        {
            var trimmedLine = lines[i].Trim();
            if (IsMatchingGrainClass(trimmedLine, className, grainType)
                && !trimmedLine.StartsWith(GrainInterfaceVersionAnalyzer.RetiredPrefix, StringComparison.Ordinal))
            {
                lines[i] = $"{GrainInterfaceVersionAnalyzer.RetiredPrefix} {trimmedLine}";
                break;
            }
        }

        var content = SortContractEntries(string.Join(newLine, lines), newLine);
        return project.Solution.WithAdditionalDocumentText(
            contractsFile.Id,
            Microsoft.CodeAnalysis.Text.SourceText.From(content, Utf8NoBom));
    }

    private static async Task<Solution> AddInterfaceToFileAsync(
        Document document,
        string interfaceName,
        string? grainInterfaceType,
        CancellationToken cancellationToken)
    {
        var project = document.Project;
        var solution = project.Solution;

        // Get version and alias from the source code
        var semanticModel = await document.GetSemanticModelAsync(cancellationToken).ConfigureAwait(false);
        var root = await document.GetSyntaxRootAsync(cancellationToken).ConfigureAwait(false);

        if (semanticModel is null || root is null)
        {
            return solution;
        }

        var interfaceDecl = root.DescendantNodes()
            .OfType<InterfaceDeclarationSyntax>()
            .FirstOrDefault(i =>
            {
                var symbol = semanticModel.GetDeclaredSymbol(i, cancellationToken);
                if (symbol is null) return false;
                var fullName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", "");
                return string.Equals(fullName, interfaceName, StringComparison.Ordinal);
            });

        if (interfaceDecl is null)
        {
            return solution;
        }

        var symbol = semanticModel.GetDeclaredSymbol(interfaceDecl, cancellationToken) as INamedTypeSymbol;
        if (symbol is null)
        {
            return solution;
        }

        var version = GetVersionFromAttributes(symbol);
        var explicitGrainInterfaceType = GetGrainInterfaceTypeFromAttributes(symbol);
        grainInterfaceType ??= GrainInterfaceVersionAnalyzer.GetGrainInterfaceType(symbol);
        var interfaceClrComment = GrainInterfaceVersionAnalyzer.IdentityDiffersFromClrName(explicitGrainInterfaceType, symbol)
            ? interfaceName
            : null;

        // Build the interface declaration line
        var sb = new StringBuilder();
        sb.Append("interface ");
        if (!string.IsNullOrEmpty(grainInterfaceType))
        {
            sb.Append($"[GrainInterfaceType(\"{grainInterfaceType}\")] ");
        }
        sb.Append(interfaceName);
        sb.Append($" [Version({version})]");
        var interfaceLine = sb.ToString();

        // Build member lines
        var memberLines = new List<(string Signature, MethodWireIdentity WireIdentity)>();
        foreach (var member in symbol.GetMembers().OfType<IMethodSymbol>())
        {
            if (member.MethodKind != MethodKind.Ordinary || member.IsStatic)
            {
                continue;
            }

            var memberSignature = GrainInterfaceVersionAnalyzer.GetManifestMethodSignature(member);
            memberLines.Add((
                memberSignature,
                GrainInterfaceVersionAnalyzer.GetMethodWireIdentity(member)));
        }

        // Find or create the OrleansContracts.txt file
        var grainInterfacesFile = FindContractsDocument(project);

        if (grainInterfacesFile is not null)
        {
            // Append to existing file
            var text = await grainInterfacesFile.GetTextAsync(cancellationToken).ConfigureAwait(false);
            var existingContent = text?.ToString() ?? "";
            var newLine = text is null ? DefaultNewLine : GetNewLine(text);
            var lines = existingContent.Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.None);
            for (var i = 0; i < lines.Length; i++)
            {
                if (IsMatchingInterface(lines[i], interfaceName, grainInterfaceType))
                {
                    var updatedLines = lines.ToList();
                    i = SetClrCommentBefore(updatedLines, i, interfaceClrComment);
                    updatedLines[i] = interfaceLine;
                    var reactivatedContent = SortContractEntries(string.Join(newLine, updatedLines), newLine);
                    var reactivatedText = Microsoft.CodeAnalysis.Text.SourceText.From(reactivatedContent, Utf8NoBom);
                    return solution.WithAdditionalDocumentText(grainInterfacesFile.Id, reactivatedText);
                }
            }

            var newContent = existingContent.TrimEnd();
            if (!string.IsNullOrEmpty(newContent))
            {
                newContent += newLine + newLine;
            }
            if (interfaceClrComment is not null)
            {
                newContent += $"# {interfaceClrComment}{newLine}";
            }
            newContent += interfaceLine;
            foreach (var member in memberLines)
            {
                newContent += $"{newLine}  {GrainInterfaceFileParser.FormatMemberDeclaration(
                    member.Signature,
                    member.WireIdentity)}";
            }
            newContent = SortContractEntries(newContent, newLine);

            var newText = Microsoft.CodeAnalysis.Text.SourceText.From(newContent, Utf8NoBom);
            solution = solution.WithAdditionalDocumentText(grainInterfacesFile.Id, newText);
        }
        else
        {
            var content = new StringBuilder();
            if (interfaceClrComment is not null)
            {
                AppendLine(content, $"# {interfaceClrComment}", DefaultNewLine);
            }
            AppendLine(content, interfaceLine, DefaultNewLine);
            foreach (var member in memberLines)
            {
                AppendLine(
                    content,
                    $"  {GrainInterfaceFileParser.FormatMemberDeclaration(member.Signature, member.WireIdentity)}",
                    DefaultNewLine);
            }

            var newText = Microsoft.CodeAnalysis.Text.SourceText.From(SortContractEntries(content.ToString(), DefaultNewLine), Utf8NoBom);
            var filePath = GetConfiguredContractsPath(project);

            solution = solution.AddAdditionalDocument(
                DocumentId.CreateNewId(project.Id),
                Path.GetFileName(filePath),
                newText,
                filePath: filePath);
        }

        return solution;
    }

    private static async Task<Solution> UpdateVersionInFileAsync(
        Document document,
        string interfaceName,
        string? grainInterfaceType,
        string newVersion,
        CancellationToken cancellationToken)
    {
        var project = document.Project;
        var solution = project.Solution;

        var grainInterfacesFile = FindContractsDocument(project);

        if (grainInterfacesFile is null)
        {
            return solution;
        }

        var text = await grainInterfacesFile.GetTextAsync(cancellationToken).ConfigureAwait(false);
        if (text is null)
        {
            return solution;
        }

        var newLine = GetNewLine(text);
        var lines = text.ToString().Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.None);
        var newLines = new StringBuilder();

        foreach (var line in lines)
        {
            var trimmedLine = line.Trim();

            // Check if this line contains the interface declaration
            if (IsMatchingInterface(trimmedLine, interfaceName, grainInterfaceType))
            {
                // Replace the version number
                var versionStart = trimmedLine.IndexOf("[Version(", StringComparison.Ordinal);
                var versionEnd = trimmedLine.IndexOf(")]", versionStart, StringComparison.Ordinal);

                if (versionStart >= 0 && versionEnd > versionStart)
                {
                    var before = trimmedLine.Substring(0, versionStart);
                    var after = trimmedLine.Substring(versionEnd + 2);
                    AppendLine(newLines, $"{before}[Version({newVersion})]{after}", newLine);
                    continue;
                }
            }

            AppendLine(newLines, line, newLine);
        }

        // Remove trailing newline added by AppendLine
        var newContent = newLines.ToString();
        if (newContent.EndsWith(newLine, StringComparison.Ordinal))
        {
            newContent = newContent.Substring(0, newContent.Length - newLine.Length);
        }
        newContent = SortContractEntries(newContent, newLine);

        var newText = Microsoft.CodeAnalysis.Text.SourceText.From(newContent, Utf8NoBom);
        return solution.WithAdditionalDocumentText(grainInterfacesFile.Id, newText);
    }

    private static async Task<Solution> AddMemberToFileAsync(
        Document document,
        string interfaceName,
        string? grainInterfaceType,
        string memberSignature,
        string memberWireIdentity,
        CancellationToken cancellationToken)
    {
        var project = document.Project;
        var solution = project.Solution;

        var grainInterfacesFile = FindContractsDocument(project);

        if (grainInterfacesFile is null)
        {
            return solution;
        }

        var text = await grainInterfacesFile.GetTextAsync(cancellationToken).ConfigureAwait(false);
        if (text is null)
        {
            return solution;
        }

        var newLine = GetNewLine(text);
        var lines = text.ToString().Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.None);
        var newLines = new StringBuilder();
        var foundInterface = false;
        var insertedMember = false;

        for (int i = 0; i < lines.Length; i++)
        {
            var line = lines[i];
            var trimmedLine = line.Trim();

            if (foundInterface
                && !insertedMember
                && (string.IsNullOrEmpty(trimmedLine)
                    || trimmedLine.StartsWith("#", StringComparison.Ordinal)
                    || GrainInterfaceFileParser.TryGetContractName(trimmedLine, out _)))
            {
                AppendMember(newLines, memberSignature, memberWireIdentity, newLine);
                insertedMember = true;
            }

            // Check if this line contains the interface declaration
            if (!foundInterface && IsMatchingInterface(trimmedLine, interfaceName, grainInterfaceType))
            {
                foundInterface = true;
            }

            AppendLine(newLines, line, newLine);
        }

        // If we didn't insert the member yet, append it at the end
        if (foundInterface && !insertedMember)
        {
            AppendMember(newLines, memberSignature, memberWireIdentity, newLine);
        }

        // Remove trailing newline added by AppendLine
        var newContent = newLines.ToString();
        if (newContent.EndsWith(newLine, StringComparison.Ordinal))
        {
            newContent = newContent.Substring(0, newContent.Length - newLine.Length);
        }
        newContent = SortContractEntries(newContent, newLine);

        var newText = Microsoft.CodeAnalysis.Text.SourceText.From(newContent, Utf8NoBom);
        return solution.WithAdditionalDocumentText(grainInterfacesFile.Id, newText);
    }

    private static async Task<Solution> RetireInterfaceInFileAsync(
        Document document,
        string interfaceName,
        string? grainInterfaceType,
        CancellationToken cancellationToken)
    {
        var project = document.Project;
        var solution = project.Solution;

        var grainInterfacesFile = FindContractsDocument(project);

        if (grainInterfacesFile is null)
        {
            return solution;
        }

        var text = await grainInterfacesFile.GetTextAsync(cancellationToken).ConfigureAwait(false);
        if (text is null)
        {
            return solution;
        }

        var newLine = GetNewLine(text);
        var lines = text.ToString().Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.None);
        var newLines = new StringBuilder();

        foreach (var line in lines)
        {
            var trimmedLine = line.Trim();

            // Check if this line contains the interface declaration
            if (IsMatchingInterface(trimmedLine, interfaceName, grainInterfaceType) &&
                !trimmedLine.StartsWith(GrainInterfaceVersionAnalyzer.RetiredPrefix, StringComparison.Ordinal))
            {
                // Add *RETIRED* prefix
                AppendLine(newLines, $"{GrainInterfaceVersionAnalyzer.RetiredPrefix} {trimmedLine}", newLine);
                continue;
            }

            AppendLine(newLines, line, newLine);
        }

        // Remove trailing newline added by AppendLine
        var newContent = newLines.ToString();
        if (newContent.EndsWith(newLine, StringComparison.Ordinal))
        {
            newContent = newContent.Substring(0, newContent.Length - newLine.Length);
        }
        newContent = SortContractEntries(newContent, newLine);

        var newText = Microsoft.CodeAnalysis.Text.SourceText.From(newContent, Utf8NoBom);
        return solution.WithAdditionalDocumentText(grainInterfacesFile.Id, newText);
    }

    private static string GetNewLine(SourceText text)
    {
        foreach (var line in text.Lines)
        {
            if (line.EndIncludingLineBreak > line.End)
            {
                return text.ToString(TextSpan.FromBounds(line.End, line.EndIncludingLineBreak));
            }
        }

        return DefaultNewLine;
    }

    private static bool IsMatchingInterface(string line, string interfaceName, string? grainInterfaceType)
    {
        if (!GrainInterfaceFileParser.TryGetInterfaceName(line, out var declaredInterfaceName))
        {
            return false;
        }

        if (grainInterfaceType is not null)
        {
            return GrainInterfaceFileParser.TryGetGrainInterfaceType(line, out var declaredGrainInterfaceType)
                ? string.Equals(declaredGrainInterfaceType, grainInterfaceType, StringComparison.Ordinal)
                : string.Equals(
                    grainInterfaceType,
                    GrainInterfaceVersionAnalyzer.GetDefaultGrainInterfaceType(interfaceName),
                    StringComparison.Ordinal)
                    && string.Equals(declaredInterfaceName, interfaceName, StringComparison.Ordinal);
        }

        return string.Equals(declaredInterfaceName, interfaceName, StringComparison.Ordinal);
    }

    private static bool IsMatchingGrainClass(string line, string className, string? grainType)
    {
        if (!GrainInterfaceFileParser.TryGetGrainClassName(line, out var declaredClassName)
            || !string.Equals(declaredClassName, className, StringComparison.Ordinal))
        {
            return false;
        }

        return grainType is null
            ? !GrainInterfaceFileParser.TryGetGrainClassType(line, out _)
            : GrainInterfaceFileParser.TryGetGrainClassType(line, out var declaredGrainType)
                && string.Equals(declaredGrainType, grainType, StringComparison.Ordinal);
    }

    private static bool IdentityDiffersFromClrName(string? identity, string fullName)
    {
        if (identity is null)
        {
            return false;
        }

        var simpleName = fullName.Substring(fullName.LastIndexOf('.') + 1);
        return !string.Equals(identity, fullName, StringComparison.Ordinal)
            && !string.Equals(identity, simpleName, StringComparison.Ordinal);
    }

    private static int SetClrCommentBefore(List<string> lines, int entryIndex, string? clrName)
    {
        if (entryIndex > 0 && lines[entryIndex - 1].TrimStart().StartsWith("# ", StringComparison.Ordinal))
        {
            if (clrName is null)
            {
                lines.RemoveAt(entryIndex - 1);
                return entryIndex - 1;
            }

            lines[entryIndex - 1] = $"# {clrName}";
            return entryIndex;
        }

        if (clrName is null)
        {
            return entryIndex;
        }

        lines.Insert(entryIndex, $"# {clrName}");
        return entryIndex + 1;
    }

    private static string SortContractEntries(string content, string newLine)
    {
        var preamble = new List<string>();
        var blocks = new List<ContractBlock>();
        ContractBlock? currentBlock = null;
        string? pendingComment = null;
        var lines = content.Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.None);

        for (var lineIndex = 0; lineIndex < lines.Length; lineIndex++)
        {
            var line = lines[lineIndex];
            var trimmedLine = line.TrimStart();
            if (IsGeneratedHeaderLine(trimmedLine))
            {
                continue;
            }

            if (trimmedLine.StartsWith("# ", StringComparison.Ordinal)
                && !trimmedLine.StartsWith("# This file ", StringComparison.Ordinal)
                && !trimmedLine.StartsWith("# Format:", StringComparison.Ordinal)
                && !trimmedLine.StartsWith("#   ", StringComparison.Ordinal)
                && lineIndex + 1 < lines.Length
                && (GrainInterfaceFileParser.TryGetContractName(lines[lineIndex + 1], out _)
                    || GrainInterfaceFileParser.TryGetMemberSignature(lines[lineIndex + 1], out _)))
            {
                pendingComment = NormalizeComment(line);
                continue;
            }

            if (GrainInterfaceFileParser.TryGetContractName(line, out var contractName))
            {
                var inlineComment = GrainInterfaceFileParser.GetClrComment(line);
                currentBlock = new ContractBlock(
                    contractName,
                    NormalizeContractDeclaration(line),
                    pendingComment ?? (inlineComment.Length > 0 ? NormalizeComment(inlineComment) : null));
                blocks.Add(currentBlock);
                pendingComment = null;
            }
            else if (currentBlock is null)
            {
                if (pendingComment is not null)
                {
                    preamble.Add(pendingComment);
                    pendingComment = null;
                }
                preamble.Add(line);
            }
            else if (GrainInterfaceFileParser.TryGetMemberDeclaration(
                line,
                out var storedMemberSignature,
                out var memberWireIdentity))
            {
                var inlineComment = GrainInterfaceFileParser.GetClrComment(line);
                var memberComment = pendingComment
                    ?? (inlineComment.Length > 0 ? NormalizeComment(inlineComment) : null);
                var normalizedMemberLine = NormalizeMemberLine(storedMemberSignature, currentBlock.Name);
                currentBlock.Members.Add((
                    normalizedMemberLine,
                    normalizedMemberLine,
                    memberWireIdentity,
                    memberComment));
                pendingComment = null;
            }
            else if (!string.IsNullOrWhiteSpace(line))
            {
                if (pendingComment is not null)
                {
                    currentBlock.OtherLines.Add(pendingComment);
                    pendingComment = null;
                }
                currentBlock.OtherLines.Add(line);
            }
        }

        while (preamble.Count > 0 && string.IsNullOrWhiteSpace(preamble[preamble.Count - 1]))
        {
            preamble.RemoveAt(preamble.Count - 1);
        }

        var result = new List<string>(GeneratedHeader);
        if (preamble.Count > 0)
        {
            result.Add("");
            result.AddRange(preamble);
        }
        if (blocks.Count > 0)
        {
            result.Add("");
        }

        var orderedBlocks = blocks.OrderBy(block => block.Name, StringComparer.Ordinal).ToArray();
        for (var i = 0; i < orderedBlocks.Length; i++)
        {
            if (i > 0)
            {
                result.Add("");
            }

            var block = orderedBlocks[i];
            if (block.ClrComment is not null)
            {
                result.Add(block.ClrComment);
            }
            result.Add(block.Declaration);
            foreach (var member in block.Members
                .OrderBy(member => member.Signature, StringComparer.Ordinal)
                .ThenBy(member => member.WireIdentity.Value, StringComparer.Ordinal))
            {
                if (member.ClrComment is not null)
                {
                    result.Add($"  {member.ClrComment}");
                }
                result.Add($"  {GrainInterfaceFileParser.FormatMemberDeclaration(
                    member.Line,
                    member.WireIdentity)}");
            }
            result.AddRange(block.OtherLines);
        }

        return string.Join(newLine, result) + newLine;
    }

    private static bool IsGeneratedHeaderLine(string line)
        => GeneratedHeader.Contains(line, StringComparer.Ordinal)
            || line is "# OrleansContracts.txt"
            or "# Regenerate it by applying \"Regenerate OrleansContracts.txt\" at project or solution scope."
            or "# This file is auto-generated by the Orleans contract analyzer."
            or "# Update source contracts, then regenerate this file by following:"
            or "# https://aka.ms/orleans/OrleansContracts.txt"
            or "# Methods without [Id] or [Alias] use the Orleans code generator's existing wire ID hash."
            or "# This file tracks grain interface versions for compatibility during rolling upgrades."
            or "# Format:"
            or "#   # Namespace.GrainClass"
            or "#   class [GrainType(\"identity\")] Namespace.GrainClass"
            or "#   # Namespace.IInterface"
            or "#   interface [GrainInterfaceType(\"identity\")] Namespace.IInterface [Version(N)]"
            or "#   # Namespace.IInterface.Method(params) -> ReturnType"
            or "#   contract-signature";

    private static string NormalizeComment(string comment)
    {
        var result = comment.Trim();
        return result.StartsWith("# CLR: ", StringComparison.Ordinal)
            ? $"# {result.Substring("# CLR: ".Length)}"
            : result;
    }

    private static string NormalizeMemberLine(string signature, string contractName)
        => GrainInterfaceVersionAnalyzer.NormalizeStoredMemberSignature(signature, contractName);

    private static string NormalizeContractDeclaration(string line)
    {
        var result = GrainInterfaceFileParser.StripClrComment(line);
        if (GrainInterfaceFileParser.TryGetGrainClassName(result, out _))
        {
            return result;
        }

        if (result.StartsWith(GrainInterfaceVersionAnalyzer.RetiredPrefix, StringComparison.Ordinal))
        {
            var declaration = result.Substring(GrainInterfaceVersionAnalyzer.RetiredPrefix.Length).TrimStart();
            return declaration.StartsWith("interface ", StringComparison.Ordinal)
                ? result
                : $"{GrainInterfaceVersionAnalyzer.RetiredPrefix} interface {declaration}";
        }

        return result.StartsWith("interface ", StringComparison.Ordinal) ? result : $"interface {result}";
    }

    private static void AppendLine(StringBuilder builder, string value, string newLine)
    {
        builder.Append(value);
        builder.Append(newLine);
    }

    private static void AppendMember(
        StringBuilder builder,
        string memberSignature,
        string memberWireIdentity,
        string newLine)
        => AppendLine(
            builder,
            $"  {memberWireIdentity}: {memberSignature}",
            newLine);

    private static ushort GetVersionFromAttributes(ISymbol symbol)
    {
        foreach (var attribute in symbol.GetAttributes())
        {
            if (string.Equals(attribute.AttributeClass?.ToDisplayString(), Constants.VersionAttributeFullyQualifiedName, StringComparison.Ordinal))
            {
                if (attribute.ConstructorArguments.Length > 0 &&
                    attribute.ConstructorArguments[0].Value is ushort version)
                {
                    return version;
                }
            }
        }

        return 0;
    }

    private static string? GetGrainTypeFromAttributes(ISymbol symbol)
    {
        foreach (var attribute in symbol.GetAttributes())
        {
            if (string.Equals(attribute.AttributeClass?.ToDisplayString(), Constants.GrainTypeAttributeFullyQualifiedName, StringComparison.Ordinal)
                && attribute.ConstructorArguments.Length > 0
                && attribute.ConstructorArguments[0].Value is string alias)
            {
                return alias;
            }
        }

        return null;
    }

    private static string? GetGrainInterfaceTypeFromAttributes(ISymbol symbol)
    {
        foreach (var attribute in symbol.GetAttributes())
        {
            if (string.Equals(attribute.AttributeClass?.ToDisplayString(), Constants.GrainInterfaceTypeAttributeFullyQualifiedName, StringComparison.Ordinal)
                && attribute.ConstructorArguments.Length > 0
                && attribute.ConstructorArguments[0].Value is string value)
            {
                return value;
            }
        }

        return null;
    }

    private sealed class ContractBlock
    {
        public ContractBlock(string name, string declaration, string? clrComment)
        {
            Name = name;
            Declaration = declaration;
            ClrComment = clrComment;
        }

        public string Name { get; }

        public string Declaration { get; }

        public string? ClrComment { get; }

        public List<(string Signature, string Line, MethodWireIdentity WireIdentity, string? ClrComment)> Members { get; } = new();

        public List<string> OtherLines { get; } = new();
    }
}
