<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Microsoft.Orleans.GrainDirectory.EntityFrameworkCore.PostgreSQL</PackageId>
    <Title>Microsoft Orleans Entity Framework Core (PostgreSQL) Grain Directory Provider</Title>
    <Description>Microsoft Orleans grain directory provider backed by Entity Framework Core for PostgreSQL</Description>
    <PackageTags>$(PackageTags) Entity Framework Core SQL PostgreSQL</PackageTags>
    <Nullable>enable</Nullable>
    <TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>
    <AssemblyName>Orleans.GrainDirectory.EntityFrameworkCore.PostgreSQL</AssemblyName>
    <RootNamespace>Orleans.GrainDirectory.EntityFrameworkCore.PostgreSQL</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)src\EFCore\Orleans.GrainDirectory.EntityFrameworkCore\Orleans.GrainDirectory.EntityFrameworkCore.csproj"/>
  </ItemGroup>
</Project>
