#nullable enable
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.CompilerServices;
using System.Runtime.Loader;
using System.Threading;
using System.Threading.Tasks;
using Orleans;
using Orleans.Serialization.Configuration;
using Xunit;

namespace NonSilo.Tests
{
    /// <summary>
    /// Tests for provider discovery performed by <see cref="ProviderRegistrationResolver"/>, the shared seam used by
    /// both client (<c>DefaultClientServices</c>) and silo (<c>DefaultSiloServices</c>) configuration.
    /// These verify that generated provider metadata is consumed, that assemblies produced by older code generators
    /// (which lack <see cref="IProviderMetadataProvider"/>) still work via the <see cref="RegisterProviderAttribute"/>
    /// fallback, and that custom type manifest providers are never activated during discovery outside of DI.
    /// </summary>
    [TestCategory("BVT")]
    [TestCategory("Providers")]
    public class ProviderRegistrationResolverTests
    {
        /// <summary>
        /// Verifies that generated provider metadata (a type marked as generated by OrleansCodeGen which implements
        /// <see cref="IProviderMetadataProvider"/>) is consumed by discovery for both the client and silo targets,
        /// with each target only receiving the registrations declared for it.
        /// </summary>
        [Fact]
        public void GeneratedProviderMetadata_IsConsumedByClientAndSiloConfiguration()
        {
            var assembly = CreateAssemblyWithAttributes(
                TypeManifestProviderAttribute(typeof(GeneratedMetadataProvider)));

            var clientProviders = ProviderRegistrationResolver.GetRegisteredProviders(new[] { assembly }, "Client");
            var siloProviders = ProviderRegistrationResolver.GetRegisteredProviders(new[] { assembly }, "Silo");

            // Client discovery receives only the client-targeted registration from the generated metadata.
            Assert.Equal(typeof(ClientClusteringProviderBuilder), clientProviders[("Clustering", "UnitTestClustering")]);
            Assert.False(clientProviders.ContainsKey(("GrainStorage", "UnitTestStorage")));

            // Silo discovery receives only the silo-targeted registration from the same generated metadata.
            Assert.Equal(typeof(SiloStorageProviderBuilder), siloProviders[("GrainStorage", "UnitTestStorage")]);
            Assert.False(siloProviders.ContainsKey(("Clustering", "UnitTestClustering")));
        }

        /// <summary>
        /// Verifies that an assembly produced by an older code generator - one whose generated type manifest provider
        /// does not implement <see cref="IProviderMetadataProvider"/> - still contributes its provider registrations
        /// through the legacy <see cref="RegisterProviderAttribute"/> fallback for both client and silo targets.
        /// </summary>
        [Fact]
        public void LegacyAssemblyWithoutProviderMetadata_UsesRegisterProviderAttributeFallback()
        {
            OldGeneratorMetadataProvider.InstantiationCount = 0;

            var assembly = CreateAssemblyWithAttributes(
                // An older generator still emits a generated type manifest provider, but it predates
                // IProviderMetadataProvider so it does not implement it.
                TypeManifestProviderAttribute(typeof(OldGeneratorMetadataProvider)),
                RegisterProviderAttribute("LegacyClustering", "Clustering", "Client", typeof(LegacyClientProviderBuilder)),
                RegisterProviderAttribute("LegacyStorage", "GrainStorage", "Silo", typeof(LegacySiloProviderBuilder)));

            var clientProviders = ProviderRegistrationResolver.GetRegisteredProviders(new[] { assembly }, "Client");
            var siloProviders = ProviderRegistrationResolver.GetRegisteredProviders(new[] { assembly }, "Silo");

            // The client-targeted legacy registration is discovered via the RegisterProviderAttribute fallback.
            Assert.Equal(typeof(LegacyClientProviderBuilder), clientProviders[("Clustering", "LegacyClustering")]);
            Assert.False(clientProviders.ContainsKey(("GrainStorage", "LegacyStorage")));

            // The silo-targeted legacy registration is discovered via the same fallback path.
            Assert.Equal(typeof(LegacySiloProviderBuilder), siloProviders[("GrainStorage", "LegacyStorage")]);
            Assert.False(siloProviders.ContainsKey(("Clustering", "LegacyClustering")));
            Assert.Equal(0, OldGeneratorMetadataProvider.InstantiationCount);
        }

        /// <summary>
        /// Verifies that a custom type manifest provider - one which is not marked as generated by OrleansCodeGen - is
        /// never instantiated by provider discovery. Only OrleansCodeGen-generated providers are activated outside of
        /// dependency injection; custom providers are activated by the serialization configuration pipeline via DI.
        /// </summary>
        [Fact]
        public void CustomTypeManifestProvider_IsNotActivatedByProviderDiscovery()
        {
            CustomManifestProvider.InstantiationCount = 0;

            var assembly = CreateAssemblyWithAttributes(
                TypeManifestProviderAttribute(typeof(CustomManifestProvider)));

            var clientProviders = ProviderRegistrationResolver.GetRegisteredProviders(new[] { assembly }, "Client");
            var siloProviders = ProviderRegistrationResolver.GetRegisteredProviders(new[] { assembly }, "Silo");

            // The custom provider is not OrleansCodeGen-generated, so discovery must not activate it.
            Assert.Equal(0, CustomManifestProvider.InstantiationCount);

            // And because it was never activated, it contributes no registrations to either target.
            Assert.Empty(clientProviders);
            Assert.Empty(siloProviders);
        }

        /// <summary>
        /// Verifies that when an assembly carries both modern generated provider metadata (implementing
        /// <see cref="IProviderMetadataProvider"/>) and a legacy <see cref="RegisterProviderAttribute"/>, the generated
        /// metadata takes precedence and the legacy fallback is suppressed. This guards the behavior that the fallback
        /// is only applied for assemblies built by older generators.
        /// </summary>
        [Fact]
        public void GeneratedProviderMetadata_SuppressesRegisterProviderAttributeFallback()
        {
            var assembly = CreateAssemblyWithAttributes(
                TypeManifestProviderAttribute(typeof(GeneratedMetadataProvider)),
                // A stale RegisterProviderAttribute that must be ignored because generated metadata is present.
                RegisterProviderAttribute("StaleClustering", "Clustering", "Client", typeof(LegacyClientProviderBuilder)));

            var clientProviders = ProviderRegistrationResolver.GetRegisteredProviders(new[] { assembly }, "Client");

            // Only the generated metadata registration is present.
            Assert.Equal(typeof(ClientClusteringProviderBuilder), clientProviders[("Clustering", "UnitTestClustering")]);

            // The legacy RegisterProviderAttribute registration is suppressed and never contributes.
            Assert.False(clientProviders.ContainsKey(("Clustering", "StaleClustering")));
            Assert.Single(clientProviders);
        }

        [Fact]
        public void GeneratedRegistryProvider_DoesNotInitializeLegacyFallback()
        {
            ProviderMetadataRegistry.Register(new RegistryMetadataProvider());
            var fallbackCount = 0;
            var resolver = new ProviderRegistrationResolver(
                typeof(ProviderRegistrationResolver).Assembly,
                () =>
                {
                    Interlocked.Increment(ref fallbackCount);
                    return [];
                });

            var providers = resolver.GetRegisteredProviders("Client");

            Assert.True(resolver.TryGetRegisteredProvider(
                providers,
                "Client",
                "Clustering",
                "RegistryClustering",
                out var providerType));
            Assert.Equal(typeof(RegistryClientProviderBuilder), providerType);
            Assert.Equal(0, fallbackCount);
        }

        [Fact]
        public void MissingGeneratedProvider_InitializesLegacyFallbackOnceForAllTargets()
        {
            var fallbackCount = 0;
            var assembly = CreateAssemblyWithAttributes(
                RegisterProviderAttribute("LazyClient", "Clustering", "Client", typeof(LegacyClientProviderBuilder)),
                RegisterProviderAttribute("LazySilo", "GrainStorage", "Silo", typeof(LegacySiloProviderBuilder)));
            var resolver = new ProviderRegistrationResolver(
                typeof(ProviderRegistrationResolver).Assembly,
                () =>
                {
                    Interlocked.Increment(ref fallbackCount);
                    return [assembly];
                });

            var clientProviders = resolver.GetRegisteredProviders("Client");
            Assert.True(resolver.TryGetRegisteredProvider(
                clientProviders,
                "Client",
                "Clustering",
                "LazyClient",
                out var clientProviderType));
            Assert.Equal(typeof(LegacyClientProviderBuilder), clientProviderType);

            var siloProviders = resolver.GetRegisteredProviders("Silo");
            Assert.True(resolver.TryGetRegisteredProvider(
                siloProviders,
                "Silo",
                "GrainStorage",
                "LazySilo",
                out var siloProviderType));
            Assert.Equal(typeof(LegacySiloProviderBuilder), siloProviderType);

            Assert.False(resolver.TryGetRegisteredProvider(
                clientProviders,
                "Client",
                "Clustering",
                "Missing",
                out _));
            Assert.Equal(1, fallbackCount);
            Assert.Equal(typeof(LegacyClientProviderBuilder), clientProviders[("Clustering", "LazyClient")]);
        }

        [Fact]
        public void GeneratedRegistry_DuplicateRegistrationIsDeterministicUnderConcurrency()
        {
            Parallel.Invoke(
                static () => ProviderMetadataRegistry.Register(new ZDuplicateMetadataProvider()),
                static () => ProviderMetadataRegistry.Register(new ADuplicateMetadataProvider()),
                static () => ProviderMetadataRegistry.Register(new ZDuplicateMetadataProvider()));

            var resolver = new ProviderRegistrationResolver(
                typeof(ProviderRegistrationResolver).Assembly,
                static () => []);
            var providers = resolver.GetRegisteredProviders("Client");

            Assert.Equal(typeof(ZDuplicateProviderBuilder), providers[("Clustering", "DeterministicDuplicate")]);
        }

        [Fact]
        public void GeneratedRegistry_DoesNotRootCollectibleAssemblyLoadContext()
        {
            var loadContextReference = RegisterProviderInCollectibleContext();

            for (var attempt = 0; attempt < 10 && loadContextReference.IsAlive; attempt++)
            {
                GC.Collect();
                GC.WaitForPendingFinalizers();
                GC.Collect();
            }

            Assert.False(loadContextReference.IsAlive);
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        private static WeakReference RegisterProviderInCollectibleContext()
        {
            var loadContext = new CollectibleProviderLoadContext();
            var assembly = loadContext.LoadFromAssemblyPath(typeof(ProviderRegistrationResolverTests).Assembly.Location);
            var providerType = assembly.GetType(typeof(CollectibleMetadataProvider).FullName!, throwOnError: true)!;
            var provider = (IProviderMetadataProvider)Activator.CreateInstance(providerType)!;
            ProviderMetadataRegistry.Register(provider);

            var result = new WeakReference(loadContext);
            loadContext.Unload();
            return result;
        }

        private static CustomAttributeBuilder TypeManifestProviderAttribute(Type providerType)
        {
            var ctor = typeof(TypeManifestProviderAttribute).GetConstructor(new[] { typeof(Type) })!;
            return new CustomAttributeBuilder(ctor, new object[] { providerType });
        }

        private static CustomAttributeBuilder RegisterProviderAttribute(string name, string kind, string target, Type type)
        {
            var ctor = typeof(RegisterProviderAttribute).GetConstructor(
                new[] { typeof(string), typeof(string), typeof(string), typeof(Type) })!;
            return new CustomAttributeBuilder(ctor, new object[] { name, kind, target, type });
        }

        private static Assembly CreateAssemblyWithAttributes(params CustomAttributeBuilder[] attributes)
        {
            var name = new AssemblyName("ProviderDiscoveryTest_" + Guid.NewGuid().ToString("N"));
            var assemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(name, AssemblyBuilderAccess.Run);
            foreach (var attribute in attributes)
            {
                assemblyBuilder.SetCustomAttribute(attribute);
            }

            assemblyBuilder.DefineDynamicModule("Main");
            return assemblyBuilder;
        }

        // Simulates a generated metadata provider: marked as generated by OrleansCodeGen and implementing
        // IProviderMetadataProvider, so discovery activates it and reads its registrations.
        [GeneratedCode("OrleansCodeGen", "1.0.0")]
        public sealed class GeneratedMetadataProvider : TypeManifestProviderBase, IProviderMetadataProvider
        {
            public void ConfigureProviders(IDictionary<(string Target, string Kind, string Name), Type> providers)
            {
                providers[("Client", "Clustering", "UnitTestClustering")] = typeof(ClientClusteringProviderBuilder);
                providers[("Silo", "GrainStorage", "UnitTestStorage")] = typeof(SiloStorageProviderBuilder);
            }

            protected override void ConfigureInner(TypeManifestOptions options)
            {
            }
        }

        // Simulates a generated metadata provider from an older generator: marked as generated by OrleansCodeGen but
        // predating IProviderMetadataProvider, so discovery must fall back to RegisterProviderAttribute.
        [GeneratedCode("OrleansCodeGen", "1.0.0")]
        public sealed class OldGeneratorMetadataProvider : TypeManifestProviderBase
        {
            public static int InstantiationCount;

            public OldGeneratorMetadataProvider()
            {
                Interlocked.Increment(ref InstantiationCount);
            }

            protected override void ConfigureInner(TypeManifestOptions options)
            {
            }
        }

        // Simulates a user-authored custom type manifest provider. It is a valid ITypeManifestProvider (so it can be
        // referenced by TypeManifestProviderAttribute) but is not OrleansCodeGen-generated, so provider discovery must
        // never construct it. The instantiation counter proves whether the constructor ran.
        public sealed class CustomManifestProvider : TypeManifestProviderBase
        {
            public static int InstantiationCount;

            public CustomManifestProvider()
            {
                Interlocked.Increment(ref InstantiationCount);
            }

            protected override void ConfigureInner(TypeManifestOptions options)
            {
            }
        }

        // Marker types used only as provider registration values; discovery stores the Type without activating it.
        public sealed class ClientClusteringProviderBuilder
        {
        }

        public sealed class SiloStorageProviderBuilder
        {
        }

        public sealed class LegacyClientProviderBuilder
        {
        }

        public sealed class LegacySiloProviderBuilder
        {
        }

        public sealed class RegistryMetadataProvider : IProviderMetadataProvider
        {
            public void ConfigureProviders(IDictionary<(string Target, string Kind, string Name), Type> providers)
                => providers[("Client", "Clustering", "RegistryClustering")] = typeof(RegistryClientProviderBuilder);
        }

        public sealed class ADuplicateMetadataProvider : IProviderMetadataProvider
        {
            public void ConfigureProviders(IDictionary<(string Target, string Kind, string Name), Type> providers)
                => providers[("Client", "Clustering", "DeterministicDuplicate")] = typeof(ADuplicateProviderBuilder);
        }

        public sealed class ZDuplicateMetadataProvider : IProviderMetadataProvider
        {
            public void ConfigureProviders(IDictionary<(string Target, string Kind, string Name), Type> providers)
                => providers[("Client", "Clustering", "DeterministicDuplicate")] = typeof(ZDuplicateProviderBuilder);
        }

        public sealed class RegistryClientProviderBuilder
        {
        }

        public sealed class ADuplicateProviderBuilder
        {
        }

        public sealed class ZDuplicateProviderBuilder
        {
        }

        private sealed class CollectibleProviderLoadContext : AssemblyLoadContext
        {
            public CollectibleProviderLoadContext()
                : base(isCollectible: true)
            {
            }

            protected override Assembly? Load(AssemblyName assemblyName)
                => string.Equals(
                    assemblyName.Name,
                    typeof(IProviderMetadataProvider).Assembly.GetName().Name,
                    StringComparison.Ordinal)
                    ? typeof(IProviderMetadataProvider).Assembly
                    : null;
        }
    }

    public sealed class CollectibleMetadataProvider : IProviderMetadataProvider
    {
        public void ConfigureProviders(IDictionary<(string Target, string Kind, string Name), Type> providers)
            => providers[("Client", "Clustering", "Collectible")] = typeof(CollectibleProviderBuilder);
    }

    public sealed class CollectibleProviderBuilder
    {
    }
}
