// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orleans.GrainDirectory.EntityFrameworkCore.SqlServer.Data;

#nullable disable

namespace Orleans.GrainDirectory.EntityFrameworkCore.SqlServer.Data.Migrations
{
    [DbContext(typeof(SqlServerGrainDirectoryDbContext))]
    partial class SqlServerGrainDirectoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Orleans.GrainDirectory.EntityFrameworkCore.Data.GrainActivationRecord<byte[]>", b =>
                {
                    b.Property<byte[]>("ClusterIdHash")
                        .HasMaxLength(32)
                        .HasColumnType("binary(32)");

                    b.Property<byte[]>("GrainIdHash")
                        .HasMaxLength(32)
                        .HasColumnType("binary(32)");

                    b.Property<string>("ActivationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ClusterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<byte[]>("ETag")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("GrainId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<long>("MembershipVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("SiloAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<byte[]>("SiloAddressHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("binary(32)");

                    b.HasKey("ClusterIdHash", "GrainIdHash")
                        .HasName("PK_Activations");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("ClusterIdHash", "GrainIdHash"), false);

                    b.HasIndex("ClusterIdHash", "SiloAddressHash")
                        .HasDatabaseName("IDX_Activations_ClusterIdHash_SiloAddressHash");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ClusterIdHash", "SiloAddressHash"), false);

                    b.ToTable("Activations");
                });
#pragma warning restore 612, 618
        }
    }
}
