<Project>
  <PropertyGroup>
    <_ParentDirectoryBuildTargetsPath Condition="'$(_DirectoryBuildTargetsFile)' != ''">$([System.IO.Path]::Combine('..', '$(_DirectoryBuildTargetsFile)'))</_ParentDirectoryBuildTargetsPath>
  </PropertyGroup>

  <Import Project="$(_ParentDirectoryBuildTargetsPath)" Condition="Exists('$(_ParentDirectoryBuildTargetsPath)')"/>

  <PropertyGroup>
    <EnableBannedApiAnalyzers
      Condition="'$(EnableBannedApiAnalyzers)' == ''
        and ('$(MSBuildProjectName)' == 'Orleans.Analyzers'
          or '$(MSBuildProjectName)' == 'Orleans.Analyzers.Contracts'
          or '$(MSBuildProjectName)' == 'Orleans.CodeGenerator'
          or '$(MSBuildProjectName)' == 'Orleans.Persistence.TestKit'
          or '$(MSBuildProjectName)' == 'Orleans.Reminders.TestKit'
          or '$(MSBuildProjectName)' == 'Orleans.Sdk'
          or '$(MSBuildProjectName)' == 'Orleans.Serialization.TestKit'
          or '$(MSBuildProjectName)' == 'Orleans.TestingHost'
          or '$(MSBuildProjectName)' == 'Orleans.Transactions.TestKit.Base'
          or '$(MSBuildProjectName)' == 'Orleans.Transactions.TestKit.xUnit')">false</EnableBannedApiAnalyzers>
    <EnableBannedApiAnalyzers
      Condition="'$(EnableBannedApiAnalyzers)' == '' and '$(IsOrleansRepositorySourceProject)' == 'true'">true</EnableBannedApiAnalyzers>
  </PropertyGroup>

  <ItemGroup Condition="'$(EnableBannedApiAnalyzers)' == 'true'">
    <PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers"
                      PrivateAssets="all"
                      IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
    <AdditionalFiles Include="$(MSBuildThisFileDirectory)BannedSymbols.txt" />
    <AdditionalFiles Include="$(MSBuildThisFileDirectory)BannedSymbols.$(MSBuildProjectName).txt"
                     Condition="Exists('$(MSBuildThisFileDirectory)BannedSymbols.$(MSBuildProjectName).txt')" />
    <AdditionalFiles Include="$(MSBuildThisFileDirectory)BannedSymbols.$(MSBuildProjectName).$(TargetFramework).txt"
                     Condition="Exists('$(MSBuildThisFileDirectory)BannedSymbols.$(MSBuildProjectName).$(TargetFramework).txt')" />
  </ItemGroup>

  <ItemGroup>
    <CompilerVisibleProperty Include="EnableOrleansContractsAnalyzer" />
    <CompilerVisibleProperty Include="OrleansContractsPath" />
  </ItemGroup>

  <ItemGroup Condition="'$(EnableOrleansContractsAnalyzer)' == 'true'">
    <Analyzer Include="$(OrleansContractsAnalyzerPath)"
              Condition="'$(OrleansContractsAnalyzerPath)' != ''" />
    <AdditionalFiles Include="$(OrleansContractsPath)"
                     OrleansContractsFile="true"
                     OrleansContractsFileExists="false"
                     Condition="'$(DesignTimeBuild)' == 'true' or Exists('$(OrleansContractsPath)')" />
    <AdditionalFiles Update="$(OrleansContractsPath)"
                     OrleansContractsFileExists="true"
                     Condition="Exists('$(OrleansContractsPath)')" />
    <CompilerVisibleItemMetadata Include="AdditionalFiles" MetadataName="OrleansContractsFile" />
    <CompilerVisibleItemMetadata Include="AdditionalFiles" MetadataName="OrleansContractsFileExists" />
  </ItemGroup>

  <ItemGroup Condition="'$(IsPackable)'=='true' and '$(SourceLinkCreate)'=='true' and '$(IncludeBuildOutput)'=='true'">
    <PackageReference Include="Microsoft.SourceLink.AzureRepos.Git" PrivateAssets="All"/>
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="all" />
  </ItemGroup>

  <PropertyGroup>
    <!-- Set DisableSourceLinkUrlTranslation to true when building a tool for internal use where sources only come from internal URIs -->
    <DisableSourceLinkUrlTranslation Condition="'$(DisableSourceLinkUrlTranslation)' == ''">false</DisableSourceLinkUrlTranslation>
    <_TranslateUrlPattern>(https://.*\.visualstudio\.com/.*/_git/[^/]*)|(https://dev\.azure\.com/.*/_git/[^/]*)</_TranslateUrlPattern>
    <_TranslateUrlReplacement>$(PublicRepositoryUrl)</_TranslateUrlReplacement>
  </PropertyGroup>

  <Target Name="_TranslateAzureDevOpsUrlToGitHubUrl"
          Condition="'$(DisableSourceLinkUrlTranslation)' == 'false'"
          DependsOnTargets="$(SourceControlManagerUrlTranslationTargets)"
          BeforeTargets="SourceControlManagerPublishTranslatedUrls">

    <PropertyGroup>
      <ScmRepositoryUrl>$([System.Text.RegularExpressions.Regex]::Replace($(ScmRepositoryUrl), $(_TranslateUrlPattern), $(_TranslateUrlReplacement)))</ScmRepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
      <SourceRoot Update="@(SourceRoot)">
        <ScmRepositoryUrl>$([System.Text.RegularExpressions.Regex]::Replace(%(SourceRoot.ScmRepositoryUrl), $(_TranslateUrlPattern), $(_TranslateUrlReplacement)))</ScmRepositoryUrl>
      </SourceRoot>
    </ItemGroup>
  </Target>

  <PropertyGroup>
    <!-- If the project is packable, we generate its API surface in a separate file to be used by the API review process. -->
    <GenAPITargetDirectory Condition="'$(IsPackable)' == 'true'">$(MSBuildThisFileDirectory)/api/$([MSBuild]::MakeRelative($(MSBuildThisFileDirectory), $(MSBuildProjectDirectory)))/</GenAPITargetDirectory>
    <GenAPITargetPath Condition="'$(IsPackable)' == 'true'">$(GenAPITargetDirectory)$(AssemblyName).cs</GenAPITargetPath>
  </PropertyGroup>

  <Target Name="CreateGenAPITargetPathFolder" BeforeTargets="GenAPIGenerateReferenceAssemblySource">
    <MakeDir Directories="$(GenAPITargetDirectory)" Condition="!Exists('$(GenAPITargetDirectory)')" />
  </Target>

</Project>
