<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(TestTargetFrameworks)</TargetFrameworks>
    <OrleansBuildTimeCodeGen>true</OrleansBuildTimeCodeGen>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Testcontainers.Consul" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(SourceRoot)src\Orleans.Clustering.Consul\Orleans.Clustering.Consul.csproj" />
    <ProjectReference Include="$(SourceRoot)test\Orleans.Runtime.Internal.Tests\Orleans.Runtime.Internal.Tests.csproj" />
  </ItemGroup>
</Project>
