//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Orleans.GrainDirectory
{
    public static partial class SqlServerHostingExtensions
    {
        public static Hosting.ISiloBuilder AddEntityFrameworkCoreSqlServerGrainDirectory(this Hosting.ISiloBuilder builder, string name, System.Action<Microsoft.EntityFrameworkCore.DbContextOptionsBuilder> configureDatabase) { throw null; }

        public static Hosting.ISiloBuilder AddEntityFrameworkCoreSqlServerGrainDirectory(this Hosting.ISiloBuilder builder, string name) { throw null; }

        public static Hosting.ISiloBuilder UseEntityFrameworkCoreSqlServerGrainDirectoryAsDefault(this Hosting.ISiloBuilder builder, System.Action<Microsoft.EntityFrameworkCore.DbContextOptionsBuilder> configureDatabase) { throw null; }

        public static Hosting.ISiloBuilder UseEntityFrameworkCoreSqlServerGrainDirectoryAsDefault(this Hosting.ISiloBuilder builder) { throw null; }
    }
}

namespace Orleans.GrainDirectory.EntityFrameworkCore.SqlServer.Data
{
    public partial class SqlServerGrainDirectoryDbContext : EntityFrameworkCore.Data.GrainDirectoryDbContext<SqlServerGrainDirectoryDbContext, byte[]>
    {
        public SqlServerGrainDirectoryDbContext(Microsoft.EntityFrameworkCore.DbContextOptions<SqlServerGrainDirectoryDbContext> options) : base(default!) { }

        protected override void OnModelCreating(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder) { }
    }

    public partial class SqlServerGrainDirectoryDbContextFactory : Microsoft.EntityFrameworkCore.Design.IDesignTimeDbContextFactory<SqlServerGrainDirectoryDbContext>
    {
        public SqlServerGrainDirectoryDbContext CreateDbContext(string[] args) { throw null; }
    }
}

namespace Orleans.GrainDirectory.EntityFrameworkCore.SqlServer.Data.Migrations
{
    [Microsoft.EntityFrameworkCore.Infrastructure.DbContext(typeof(SqlServerGrainDirectoryDbContext))]
    [Microsoft.EntityFrameworkCore.Migrations.Migration("20260811210058_InitialGrainDirectorySchema")]
    public partial class InitialGrainDirectorySchema : Microsoft.EntityFrameworkCore.Migrations.Migration
    {
        protected override void BuildTargetModel(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder) { }

        protected override void Down(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder migrationBuilder) { }

        protected override void Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder migrationBuilder) { }
    }
}