//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Orleans
{
    public static partial class TaskIdExtensions
    {
        public static HierarchicalKey? ToHierarchicalKey(this System.Distributed.DurableTasks.TaskId taskId) { throw null; }

        public static System.Distributed.DurableTasks.TaskId ToTaskId(this HierarchicalKey? key) { throw null; }
    }
}

namespace Orleans.Configuration
{
    public sealed partial class DurableTaskOptions
    {
        public System.TimeSpan ResultRetentionPeriod { get { throw null; } set { } }
    }
}

namespace Orleans.DurableTasks
{
    [GenerateSerializer]
    [Alias("DurableTaskDiagnosticState")]
    public partial struct DurableTaskDiagnosticState
    {
        private object _dummy;
        private int _dummyPrimitive;
        [Id(1)]
        public System.DateTimeOffset? CompletedAt { get { throw null; } set { } }

        [Id(0)]
        public System.DateTimeOffset? CreatedAt { get { throw null; } set { } }

        [Id(3)]
        public string? Request { get { throw null; } set { } }

        [Id(4)]
        public string? Response { get { throw null; } set { } }

        [Id(2)]
        public string Status { get { throw null; } set { } }

        [Id(5)]
        public System.Collections.Generic.List<string> Waiters { get { throw null; } set { } }

        public override readonly string ToString() { throw null; }
    }

    [GenerateSerializer]
    [Invocation.ReturnValueProxy("InitializeRequest")]
    [Alias("DurableTaskRequest")]
    public abstract partial class DurableTaskRequest : System.Distributed.DurableTasks.DurableTask, IDurableTaskRequest, Runtime.IRequest, Serialization.Invocation.IInvokable, System.IDisposable, System.Distributed.DurableTasks.ISchedulableTask
    {
        [GeneratedActivatorConstructor]
        protected DurableTaskRequest(DurableTaskRequestShared shared) { }

        [Id(0)]
        public DurableTaskRequestContext? Context { get { throw null; } }

        public CodeGeneration.InvokeMethodOptions Options { get { throw null; } }

        public void AddInvokeMethodOptions(CodeGeneration.InvokeMethodOptions options) { }

        public abstract void Dispose();
        public abstract string GetActivityName();
        public virtual object GetArgument(int index) { throw null; }

        public virtual int GetArgumentCount() { throw null; }

        public virtual System.TimeSpan? GetDefaultResponseTimeout() { throw null; }

        public System.Distributed.DurableTasks.IScheduledTaskHandle GetHandle(System.Distributed.DurableTasks.TaskId taskId) { throw null; }

        public abstract string GetInterfaceName();
        public abstract System.Type GetInterfaceType();
        public abstract System.Reflection.MethodInfo GetMethod();
        public abstract string GetMethodName();
        public abstract object GetTarget();
        public System.Distributed.DurableTasks.DurableTask InitializeRequest(Runtime.GrainReference targetGrainReference) { throw null; }

        protected abstract System.Distributed.DurableTasks.DurableTask InvokeInner();
        System.Distributed.DurableTasks.DurableTask IDurableTaskRequest.CreateTask() { throw null; }

        System.Threading.Tasks.ValueTask<Serialization.Invocation.Response> Serialization.Invocation.IInvokable.Invoke() { throw null; }

        protected override System.Threading.Tasks.ValueTask<System.Distributed.DurableTasks.DurableTaskResponse> RunAsync(System.Distributed.DurableTasks.DurableExecutionContext executionContext) { throw null; }

        public virtual void SetArgument(int index, object value) { }

        public abstract void SetTarget(Serialization.Invocation.ITargetHolder holder);
        System.Threading.Tasks.ValueTask<System.Distributed.DurableTasks.DurableTaskResponse> System.Distributed.DurableTasks.ISchedulableTask.ScheduleAsync(System.Distributed.DurableTasks.TaskId taskId, System.Threading.CancellationToken cancellationToken) { throw null; }

        public override string ToString() { throw null; }
    }

    [GenerateSerializer]
    [Alias("DurableTaskRequestContext")]
    public partial class DurableTaskRequestContext
    {
        [Id(0)]
        public Runtime.GrainId CallerId { get { throw null; } set { } }

        [Id(1)]
        public Runtime.GrainId TargetId { get { throw null; } set { } }

        [Id(2)]
        public System.Collections.Generic.Dictionary<string, byte[]>? Values { get { throw null; } set { } }
    }

    public sealed partial class DurableTaskRequestShared
    {
        public DurableTaskRequestShared(Runtime.IGrainContextAccessor grainContextAccessor, IGrainFactory grainFactory) { }

        public Runtime.IGrainContextAccessor GrainContextAccessor { get { throw null; } }

        public IGrainFactory GrainFactory { get { throw null; } }
    }

    [GenerateSerializer]
    [Invocation.ReturnValueProxy("InitializeRequest")]
    [Alias("DurableTaskRequest`1")]
    public abstract partial class DurableTaskRequest<TResult> : System.Distributed.DurableTasks.DurableTask<TResult>, IDurableTaskRequest, Runtime.IRequest, Serialization.Invocation.IInvokable, System.IDisposable, System.Distributed.DurableTasks.ISchedulableTask
    {
        [GeneratedActivatorConstructor]
        protected DurableTaskRequest(DurableTaskRequestShared shared) { }

        [Id(0)]
        public DurableTaskRequestContext? Context { get { throw null; } }

        public CodeGeneration.InvokeMethodOptions Options { get { throw null; } }

        public void AddInvokeMethodOptions(CodeGeneration.InvokeMethodOptions options) { }

        public abstract void Dispose();
        public abstract string GetActivityName();
        public virtual object GetArgument(int index) { throw null; }

        public virtual int GetArgumentCount() { throw null; }

        public virtual System.TimeSpan? GetDefaultResponseTimeout() { throw null; }

        public System.Distributed.DurableTasks.IScheduledTaskHandle GetHandle(System.Distributed.DurableTasks.TaskId taskId) { throw null; }

        public abstract string GetInterfaceName();
        public abstract System.Type GetInterfaceType();
        public abstract System.Reflection.MethodInfo GetMethod();
        public abstract string GetMethodName();
        public abstract object GetTarget();
        public System.Distributed.DurableTasks.DurableTask<TResult> InitializeRequest(Runtime.GrainReference targetGrainReference) { throw null; }

        protected abstract System.Distributed.DurableTasks.DurableTask<TResult> InvokeInner();
        System.Distributed.DurableTasks.DurableTask IDurableTaskRequest.CreateTask() { throw null; }

        System.Threading.Tasks.ValueTask<Serialization.Invocation.Response> Serialization.Invocation.IInvokable.Invoke() { throw null; }

        protected override System.Threading.Tasks.ValueTask<System.Distributed.DurableTasks.DurableTaskResponse> RunAsync(System.Distributed.DurableTasks.DurableExecutionContext executionContext) { throw null; }

        public System.Threading.Tasks.ValueTask<System.Distributed.DurableTasks.DurableTaskResponse> ScheduleAsync(System.Distributed.DurableTasks.TaskId taskId, System.Threading.CancellationToken cancellationToken = default) { throw null; }

        public virtual void SetArgument(int index, object value) { }

        public abstract void SetTarget(Serialization.Invocation.ITargetHolder holder);
        public override string ToString() { throw null; }
    }

    [Alias("IDurableTaskGrainExtension")]
    public partial interface IDurableTaskGrainExtension : Runtime.IGrainExtension, Runtime.IAddressable, IDurableTaskServer
    {
        [Alias("GetRunningTasksAsync")]
        System.Collections.Generic.IAsyncEnumerable<System.Distributed.DurableTasks.TaskId> GetRunningTasksAsync(System.Threading.CancellationToken cancellationToken = default);
        [Alias("GetTasksAsync")]
        System.Collections.Generic.IAsyncEnumerable<(System.Distributed.DurableTasks.TaskId TaskId, DurableTaskDiagnosticState State)> GetTasksAsync(System.Threading.CancellationToken cancellationToken = default);
    }

    public partial interface IDurableTaskGrainStorage
    {
        System.Collections.Generic.IEnumerable<(System.Distributed.DurableTasks.TaskId Id, IDurableTaskState State)> Tasks { get; }

        void AddCompletionDestination(System.Distributed.DurableTasks.TaskId taskId, IDurableTaskState state, Runtime.GrainId destination);
        void Clear();
        void CreateTombstone(System.Distributed.DurableTasks.TaskId taskId, IDurableTaskState state);
        System.Collections.Generic.IEnumerable<(System.Distributed.DurableTasks.TaskId Id, IDurableTaskState State)> GetChildren(System.Distributed.DurableTasks.TaskId task);
        IDurableTaskState GetOrCreateTask(System.Distributed.DurableTasks.TaskId taskId, IDurableTaskRequest? request);
        System.Threading.Tasks.ValueTask ReadAsync(System.Threading.CancellationToken cancellationToken);
        void RemoveCompletionDestination(System.Distributed.DurableTasks.TaskId taskId, IDurableTaskState state, Runtime.GrainId destination);
        bool RemoveTask(System.Distributed.DurableTasks.TaskId taskId);
        void RequestCancellation(System.Distributed.DurableTasks.TaskId taskId, IDurableTaskState state);
        void SetDelay(System.Distributed.DurableTasks.TaskId taskId, IDurableTaskState state, System.DateTimeOffset dueTime, long generation);
        void SetRequest(System.Distributed.DurableTasks.TaskId taskId, IDurableTaskState state, IDurableTaskRequest request);
        void SetRequestFingerprint(System.Distributed.DurableTasks.TaskId taskId, IDurableTaskState state, string fingerprint);
        void SetResponse(System.Distributed.DurableTasks.TaskId taskId, IDurableTaskState state, System.Distributed.DurableTasks.DurableTaskResponse response);
        bool TryGetTask(System.Distributed.DurableTasks.TaskId taskId, out IDurableTaskState? state);
        System.Threading.Tasks.ValueTask WriteAsync(System.Threading.CancellationToken cancellationToken);
    }

    [Alias("IDurableTaskObserverGrainExtension")]
    public partial interface IDurableTaskObserver : Runtime.IGrainExtension, Runtime.IAddressable
    {
        [Concurrency.AlwaysInterleave]
        [Alias("OnResponse")]
        System.Threading.Tasks.ValueTask OnResponseAsync(System.Distributed.DurableTasks.TaskId taskId, System.Distributed.DurableTasks.DurableTaskResponse response, System.Threading.CancellationToken cancellationToken = default);
    }

    public partial interface IDurableTaskRequest : Runtime.IRequest, Serialization.Invocation.IInvokable, System.IDisposable
    {
        DurableTaskRequestContext? Context { get; }

        System.Distributed.DurableTasks.DurableTask CreateTask();
        string ToMethodCallString();
    }

    [Alias("IDurableTaskServerGrainExtension")]
    public partial interface IDurableTaskServer : Runtime.IGrainExtension, Runtime.IAddressable
    {
        [Concurrency.AlwaysInterleave]
        [Alias("CancelAsync")]
        System.Threading.Tasks.ValueTask CancelAsync(System.Distributed.DurableTasks.TaskId taskId, System.Threading.CancellationToken cancellationToken = default);
        [Alias("ScheduleAsync")]
        [Concurrency.AlwaysInterleave]
        System.Threading.Tasks.ValueTask<System.Distributed.DurableTasks.DurableTaskResponse> ScheduleAsync(System.Distributed.DurableTasks.TaskId taskId, IDurableTaskRequest request, System.Threading.CancellationToken cancellationToken = default);
        [Alias("SubscribeOrPollAsync")]
        [Concurrency.AlwaysInterleave]
        System.Threading.Tasks.ValueTask<System.Distributed.DurableTasks.DurableTaskResponse> SubscribeOrPollAsync(System.Distributed.DurableTasks.TaskId taskId, SubscribeOrPollOptions options, System.Threading.CancellationToken cancellationToken = default);
    }

    public partial interface IDurableTaskState
    {
        System.DateTimeOffset? CancellationRequestedAt { get; }

        System.DateTimeOffset? CompletedAt { get; }

        System.Collections.Generic.IReadOnlySet<Runtime.GrainId> CompletionDestinations { get; }

        System.DateTimeOffset CreatedAt { get; }

        System.DateTimeOffset? DueTime { get; }

        IDurableTaskRequest? Request { get; }

        string? RequestFingerprint { get; }

        System.Distributed.DurableTasks.DurableTaskResponse? Result { get; }

        long ResumeGeneration { get; }

        System.DateTimeOffset? TombstonedAt { get; }
    }

    [GenerateSerializer]
    [Immutable]
    [Alias("SubscribeOrPollOptions")]
    public readonly partial struct SubscribeOrPollOptions
    {
        private readonly int _dummyPrimitive;
        [Id(0)]
        public System.TimeSpan PollTimeout { get { throw null; } init { } }
    }
}

namespace Orleans.Hosting
{
    public static partial class DurableTaskHostingExtensions
    {
        public static IClientBuilder AddDurableTasks(this IClientBuilder clientBuilder) { throw null; }

        public static ISiloBuilder AddDurableTasks(this ISiloBuilder siloBuilder, System.Action<Configuration.DurableTaskOptions>? configureOptions = null) { throw null; }
    }

    public static partial class DurableTaskStorageExtensions
    {
        public static ISiloBuilder AddJournaledDurableTaskStorage(this ISiloBuilder siloBuilder) { throw null; }

        public static ISiloBuilder AddVolatileDurableTaskStorage(this ISiloBuilder siloBuilder) { throw null; }
    }
}

namespace Orleans.Runtime.DurableTasks
{
    [GenerateSerializer]
    [SuppressReferenceTracking]
    [Alias("DurableTaskState")]
    public partial class DurableTaskState : Orleans.DurableTasks.IDurableTaskState
    {
        [Id(5)]
        public System.DateTimeOffset? CancellationRequestedAt { get { throw null; } set { } }

        [Id(3)]
        public System.DateTimeOffset? CompletedAt { get { throw null; } set { } }

        [Id(6)]
        public System.Collections.Generic.HashSet<GrainId> CompletionDestinations { get { throw null; } set { } }

        [Id(4)]
        public System.DateTimeOffset CreatedAt { get { throw null; } set { } }

        [Id(7)]
        public System.DateTimeOffset? DueTime { get { throw null; } set { } }

        [Id(1)]
        public System.Collections.Generic.HashSet<Orleans.DurableTasks.IDurableTaskObserver> LegacyObservers { get { throw null; } set { } }

        System.DateTimeOffset? Orleans.DurableTasks.IDurableTaskState.CompletedAt { get { throw null; } }

        System.Collections.Generic.IReadOnlySet<GrainId> Orleans.DurableTasks.IDurableTaskState.CompletionDestinations { get { throw null; } }

        System.DateTimeOffset Orleans.DurableTasks.IDurableTaskState.CreatedAt { get { throw null; } }

        Orleans.DurableTasks.IDurableTaskRequest? Orleans.DurableTasks.IDurableTaskState.Request { get { throw null; } }

        [Id(2)]
        public Orleans.DurableTasks.IDurableTaskRequest? Request { get { throw null; } set { } }

        [Id(9)]
        public string? RequestFingerprint { get { throw null; } set { } }

        [Id(0)]
        public System.Distributed.DurableTasks.DurableTaskResponse? Result { get { throw null; } set { } }

        [Id(8)]
        public long ResumeGeneration { get { throw null; } set { } }

        [Id(10)]
        public System.DateTimeOffset? TombstonedAt { get { throw null; } set { } }
    }

    public partial class VolatileDurableTaskGrainStorage : Orleans.DurableTasks.IDurableTaskGrainStorage
    {
        public VolatileDurableTaskGrainStorage(Orleans.Serialization.DeepCopier<System.Collections.Generic.Dictionary<System.Distributed.DurableTasks.TaskId, DurableTaskState>> storageCopier, Orleans.Serialization.DeepCopier<DurableTaskState> stateCopier, System.TimeProvider timeProvider) { }

        public System.Collections.Generic.IEnumerable<(System.Distributed.DurableTasks.TaskId Id, Orleans.DurableTasks.IDurableTaskState State)> Tasks { get { throw null; } }

        public void AddCompletionDestination(System.Distributed.DurableTasks.TaskId taskId, Orleans.DurableTasks.IDurableTaskState state, GrainId destination) { }

        public void AddOrUpdateTask(System.Distributed.DurableTasks.TaskId taskId, DurableTaskState state) { }

        public void Clear() { }

        public void CreateTombstone(System.Distributed.DurableTasks.TaskId taskId, Orleans.DurableTasks.IDurableTaskState state) { }

        public System.Collections.Generic.IEnumerable<(System.Distributed.DurableTasks.TaskId Id, Orleans.DurableTasks.IDurableTaskState State)> GetChildren(System.Distributed.DurableTasks.TaskId parentId) { throw null; }

        public Orleans.DurableTasks.IDurableTaskState GetOrCreateTask(System.Distributed.DurableTasks.TaskId taskId, Orleans.DurableTasks.IDurableTaskRequest? request) { throw null; }

        public System.Threading.Tasks.ValueTask ReadAsync(System.Threading.CancellationToken cancellationToken) { throw null; }

        public void RemoveCompletionDestination(System.Distributed.DurableTasks.TaskId taskId, Orleans.DurableTasks.IDurableTaskState state, GrainId destination) { }

        public bool RemoveTask(System.Distributed.DurableTasks.TaskId taskId) { throw null; }

        public void RequestCancellation(System.Distributed.DurableTasks.TaskId taskId, Orleans.DurableTasks.IDurableTaskState state) { }

        public void SetDelay(System.Distributed.DurableTasks.TaskId taskId, Orleans.DurableTasks.IDurableTaskState state, System.DateTimeOffset dueTime, long generation) { }

        public void SetRequest(System.Distributed.DurableTasks.TaskId taskId, Orleans.DurableTasks.IDurableTaskState state, Orleans.DurableTasks.IDurableTaskRequest request) { }

        public void SetRequestFingerprint(System.Distributed.DurableTasks.TaskId taskId, Orleans.DurableTasks.IDurableTaskState state, string fingerprint) { }

        public void SetResponse(System.Distributed.DurableTasks.TaskId taskId, Orleans.DurableTasks.IDurableTaskState state, System.Distributed.DurableTasks.DurableTaskResponse response) { }

        public bool TryGetTask(System.Distributed.DurableTasks.TaskId taskId, out Orleans.DurableTasks.IDurableTaskState? state) { throw null; }

        public System.Threading.Tasks.ValueTask WriteAsync(System.Threading.CancellationToken cancellationToken) { throw null; }
    }
}

namespace OrleansCodeGen.Orleans.DurableTasks
{
    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_DurableTaskDiagnosticState : global::Orleans.Serialization.Codecs.IFieldCodec<global::Orleans.DurableTasks.DurableTaskDiagnosticState>, global::Orleans.Serialization.Codecs.IFieldCodec, global::Orleans.Serialization.Serializers.IValueSerializer<global::Orleans.DurableTasks.DurableTaskDiagnosticState>, global::Orleans.Serialization.Serializers.IValueSerializer
    {
        public Codec_DurableTaskDiagnosticState(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public void Deserialize<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, scoped ref global::Orleans.DurableTasks.DurableTaskDiagnosticState instance) { }

        public global::Orleans.DurableTasks.DurableTaskDiagnosticState ReadValue<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, scoped ref global::Orleans.DurableTasks.DurableTaskDiagnosticState instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, global::Orleans.DurableTasks.DurableTaskDiagnosticState value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_DurableTaskRequest : global::Orleans.Serialization.Serializers.AbstractTypeSerializer<global::Orleans.DurableTasks.DurableTaskRequest>
    {
        public Codec_DurableTaskRequest(global::Orleans.Serialization.Serializers.IBaseCodec<System.Distributed.DurableTasks.DurableTask> _baseTypeSerializer, global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public override void Deserialize<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.DurableTasks.DurableTaskRequest instance) { }

        public override void Serialize<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, global::Orleans.DurableTasks.DurableTaskRequest instance) { }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_DurableTaskRequestContext : global::Orleans.Serialization.Codecs.IFieldCodec<global::Orleans.DurableTasks.DurableTaskRequestContext>, global::Orleans.Serialization.Codecs.IFieldCodec, global::Orleans.Serialization.Serializers.IBaseCodec<global::Orleans.DurableTasks.DurableTaskRequestContext>, global::Orleans.Serialization.Serializers.IBaseCodec
    {
        public Codec_DurableTaskRequestContext(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public void Deserialize<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.DurableTasks.DurableTaskRequestContext instance) { }

        public global::Orleans.DurableTasks.DurableTaskRequestContext ReadValue<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, global::Orleans.DurableTasks.DurableTaskRequestContext instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, global::Orleans.DurableTasks.DurableTaskRequestContext value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_DurableTaskRequest<TResult> : global::Orleans.Serialization.Serializers.AbstractTypeSerializer<global::Orleans.DurableTasks.DurableTaskRequest<TResult>>
    {
        public Codec_DurableTaskRequest(global::Orleans.Serialization.Serializers.IBaseCodec<System.Distributed.DurableTasks.DurableTask<TResult>> _baseTypeSerializer, global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public override void Deserialize<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.DurableTasks.DurableTaskRequest<TResult> instance) { }

        public override void Serialize<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, global::Orleans.DurableTasks.DurableTaskRequest<TResult> instance) { }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_Invokable_IDurableTaskGrainExtension_GrainReference_Ext_28018A01 : global::Orleans.Serialization.Codecs.IFieldCodec<Invokable_IDurableTaskGrainExtension_GrainReference_Ext_28018A01>, global::Orleans.Serialization.Codecs.IFieldCodec
    {
        public Codec_Invokable_IDurableTaskGrainExtension_GrainReference_Ext_28018A01(global::Orleans.Serialization.Serializers.IBaseCodec<global::Orleans.Runtime.AsyncEnumerableRequest<System.Distributed.DurableTasks.TaskId>> _baseTypeSerializer) { }

        public void Deserialize<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, Invokable_IDurableTaskGrainExtension_GrainReference_Ext_28018A01 instance) { }

        public Invokable_IDurableTaskGrainExtension_GrainReference_Ext_28018A01 ReadValue<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, Invokable_IDurableTaskGrainExtension_GrainReference_Ext_28018A01 instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, Invokable_IDurableTaskGrainExtension_GrainReference_Ext_28018A01 value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_Invokable_IDurableTaskGrainExtension_GrainReference_Ext_623DF2E6 : global::Orleans.Serialization.Codecs.IFieldCodec<Invokable_IDurableTaskGrainExtension_GrainReference_Ext_623DF2E6>, global::Orleans.Serialization.Codecs.IFieldCodec
    {
        public Codec_Invokable_IDurableTaskGrainExtension_GrainReference_Ext_623DF2E6(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public void Deserialize<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, Invokable_IDurableTaskGrainExtension_GrainReference_Ext_623DF2E6 instance) { }

        public Invokable_IDurableTaskGrainExtension_GrainReference_Ext_623DF2E6 ReadValue<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, Invokable_IDurableTaskGrainExtension_GrainReference_Ext_623DF2E6 instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, Invokable_IDurableTaskGrainExtension_GrainReference_Ext_623DF2E6 value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_Invokable_IDurableTaskGrainExtension_GrainReference_Ext_69FFF0DD : global::Orleans.Serialization.Codecs.IFieldCodec<Invokable_IDurableTaskGrainExtension_GrainReference_Ext_69FFF0DD>, global::Orleans.Serialization.Codecs.IFieldCodec
    {
        public Codec_Invokable_IDurableTaskGrainExtension_GrainReference_Ext_69FFF0DD(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public void Deserialize<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, Invokable_IDurableTaskGrainExtension_GrainReference_Ext_69FFF0DD instance) { }

        public Invokable_IDurableTaskGrainExtension_GrainReference_Ext_69FFF0DD ReadValue<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, Invokable_IDurableTaskGrainExtension_GrainReference_Ext_69FFF0DD instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, Invokable_IDurableTaskGrainExtension_GrainReference_Ext_69FFF0DD value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_Invokable_IDurableTaskGrainExtension_GrainReference_Ext_BB23D540 : global::Orleans.Serialization.Codecs.IFieldCodec<Invokable_IDurableTaskGrainExtension_GrainReference_Ext_BB23D540>, global::Orleans.Serialization.Codecs.IFieldCodec
    {
        public Codec_Invokable_IDurableTaskGrainExtension_GrainReference_Ext_BB23D540(global::Orleans.Serialization.Serializers.IBaseCodec<global::Orleans.Runtime.AsyncEnumerableRequest<(System.Distributed.DurableTasks.TaskId TaskId, global::Orleans.DurableTasks.DurableTaskDiagnosticState State)>> _baseTypeSerializer) { }

        public void Deserialize<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, Invokable_IDurableTaskGrainExtension_GrainReference_Ext_BB23D540 instance) { }

        public Invokable_IDurableTaskGrainExtension_GrainReference_Ext_BB23D540 ReadValue<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, Invokable_IDurableTaskGrainExtension_GrainReference_Ext_BB23D540 instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, Invokable_IDurableTaskGrainExtension_GrainReference_Ext_BB23D540 value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_Invokable_IDurableTaskGrainExtension_GrainReference_Ext_D5751EC2 : global::Orleans.Serialization.Codecs.IFieldCodec<Invokable_IDurableTaskGrainExtension_GrainReference_Ext_D5751EC2>, global::Orleans.Serialization.Codecs.IFieldCodec
    {
        public Codec_Invokable_IDurableTaskGrainExtension_GrainReference_Ext_D5751EC2(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public void Deserialize<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, Invokable_IDurableTaskGrainExtension_GrainReference_Ext_D5751EC2 instance) { }

        public Invokable_IDurableTaskGrainExtension_GrainReference_Ext_D5751EC2 ReadValue<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, Invokable_IDurableTaskGrainExtension_GrainReference_Ext_D5751EC2 instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, Invokable_IDurableTaskGrainExtension_GrainReference_Ext_D5751EC2 value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_Invokable_IDurableTaskObserver_GrainReference_Ext_55C201CC : global::Orleans.Serialization.Codecs.IFieldCodec<Invokable_IDurableTaskObserver_GrainReference_Ext_55C201CC>, global::Orleans.Serialization.Codecs.IFieldCodec
    {
        public Codec_Invokable_IDurableTaskObserver_GrainReference_Ext_55C201CC(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public void Deserialize<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, Invokable_IDurableTaskObserver_GrainReference_Ext_55C201CC instance) { }

        public Invokable_IDurableTaskObserver_GrainReference_Ext_55C201CC ReadValue<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, Invokable_IDurableTaskObserver_GrainReference_Ext_55C201CC instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, Invokable_IDurableTaskObserver_GrainReference_Ext_55C201CC value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_Invokable_IDurableTaskServer_GrainReference_Ext_623DF2E6 : global::Orleans.Serialization.Codecs.IFieldCodec<Invokable_IDurableTaskServer_GrainReference_Ext_623DF2E6>, global::Orleans.Serialization.Codecs.IFieldCodec
    {
        public Codec_Invokable_IDurableTaskServer_GrainReference_Ext_623DF2E6(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public void Deserialize<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, Invokable_IDurableTaskServer_GrainReference_Ext_623DF2E6 instance) { }

        public Invokable_IDurableTaskServer_GrainReference_Ext_623DF2E6 ReadValue<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, Invokable_IDurableTaskServer_GrainReference_Ext_623DF2E6 instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, Invokable_IDurableTaskServer_GrainReference_Ext_623DF2E6 value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_Invokable_IDurableTaskServer_GrainReference_Ext_69FFF0DD : global::Orleans.Serialization.Codecs.IFieldCodec<Invokable_IDurableTaskServer_GrainReference_Ext_69FFF0DD>, global::Orleans.Serialization.Codecs.IFieldCodec
    {
        public Codec_Invokable_IDurableTaskServer_GrainReference_Ext_69FFF0DD(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public void Deserialize<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, Invokable_IDurableTaskServer_GrainReference_Ext_69FFF0DD instance) { }

        public Invokable_IDurableTaskServer_GrainReference_Ext_69FFF0DD ReadValue<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, Invokable_IDurableTaskServer_GrainReference_Ext_69FFF0DD instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, Invokable_IDurableTaskServer_GrainReference_Ext_69FFF0DD value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_Invokable_IDurableTaskServer_GrainReference_Ext_D5751EC2 : global::Orleans.Serialization.Codecs.IFieldCodec<Invokable_IDurableTaskServer_GrainReference_Ext_D5751EC2>, global::Orleans.Serialization.Codecs.IFieldCodec
    {
        public Codec_Invokable_IDurableTaskServer_GrainReference_Ext_D5751EC2(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public void Deserialize<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, Invokable_IDurableTaskServer_GrainReference_Ext_D5751EC2 instance) { }

        public Invokable_IDurableTaskServer_GrainReference_Ext_D5751EC2 ReadValue<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, Invokable_IDurableTaskServer_GrainReference_Ext_D5751EC2 instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, Invokable_IDurableTaskServer_GrainReference_Ext_D5751EC2 value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_SubscribeOrPollOptions : global::Orleans.Serialization.Codecs.IFieldCodec<global::Orleans.DurableTasks.SubscribeOrPollOptions>, global::Orleans.Serialization.Codecs.IFieldCodec, global::Orleans.Serialization.Serializers.IValueSerializer<global::Orleans.DurableTasks.SubscribeOrPollOptions>, global::Orleans.Serialization.Serializers.IValueSerializer
    {
        public void Deserialize<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, scoped ref global::Orleans.DurableTasks.SubscribeOrPollOptions instance) { }

        public global::Orleans.DurableTasks.SubscribeOrPollOptions ReadValue<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, scoped ref global::Orleans.DurableTasks.SubscribeOrPollOptions instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, global::Orleans.DurableTasks.SubscribeOrPollOptions value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_DurableTaskDiagnosticState : global::Orleans.Serialization.Cloning.IDeepCopier<global::Orleans.DurableTasks.DurableTaskDiagnosticState>, global::Orleans.Serialization.Cloning.IDeepCopier
    {
        public Copier_DurableTaskDiagnosticState(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public global::Orleans.DurableTasks.DurableTaskDiagnosticState DeepCopy(global::Orleans.DurableTasks.DurableTaskDiagnosticState result, global::Orleans.Serialization.Cloning.CopyContext context) { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_DurableTaskRequest : global::Orleans.Serialization.Cloning.IDeepCopier<global::Orleans.DurableTasks.DurableTaskRequest>, global::Orleans.Serialization.Cloning.IDeepCopier, global::Orleans.Serialization.Cloning.IBaseCopier<global::Orleans.DurableTasks.DurableTaskRequest>, global::Orleans.Serialization.Cloning.IBaseCopier
    {
        public Copier_DurableTaskRequest(global::Orleans.Serialization.Cloning.IBaseCopier<System.Distributed.DurableTasks.DurableTask> _baseTypeCopier, global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public void DeepCopy(global::Orleans.DurableTasks.DurableTaskRequest input, global::Orleans.DurableTasks.DurableTaskRequest output, global::Orleans.Serialization.Cloning.CopyContext context) { }

        public global::Orleans.DurableTasks.DurableTaskRequest DeepCopy(global::Orleans.DurableTasks.DurableTaskRequest original, global::Orleans.Serialization.Cloning.CopyContext context) { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_DurableTaskRequestContext : global::Orleans.Serialization.Cloning.IDeepCopier<global::Orleans.DurableTasks.DurableTaskRequestContext>, global::Orleans.Serialization.Cloning.IDeepCopier, global::Orleans.Serialization.Cloning.IBaseCopier<global::Orleans.DurableTasks.DurableTaskRequestContext>, global::Orleans.Serialization.Cloning.IBaseCopier
    {
        public Copier_DurableTaskRequestContext(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public void DeepCopy(global::Orleans.DurableTasks.DurableTaskRequestContext input, global::Orleans.DurableTasks.DurableTaskRequestContext output, global::Orleans.Serialization.Cloning.CopyContext context) { }

        public global::Orleans.DurableTasks.DurableTaskRequestContext DeepCopy(global::Orleans.DurableTasks.DurableTaskRequestContext original, global::Orleans.Serialization.Cloning.CopyContext context) { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_DurableTaskRequest<TResult> : global::Orleans.Serialization.Cloning.IDeepCopier<global::Orleans.DurableTasks.DurableTaskRequest<TResult>>, global::Orleans.Serialization.Cloning.IDeepCopier, global::Orleans.Serialization.Cloning.IBaseCopier<global::Orleans.DurableTasks.DurableTaskRequest<TResult>>, global::Orleans.Serialization.Cloning.IBaseCopier
    {
        public Copier_DurableTaskRequest(global::Orleans.Serialization.Cloning.IBaseCopier<System.Distributed.DurableTasks.DurableTask<TResult>> _baseTypeCopier, global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public void DeepCopy(global::Orleans.DurableTasks.DurableTaskRequest<TResult> input, global::Orleans.DurableTasks.DurableTaskRequest<TResult> output, global::Orleans.Serialization.Cloning.CopyContext context) { }

        public global::Orleans.DurableTasks.DurableTaskRequest<TResult> DeepCopy(global::Orleans.DurableTasks.DurableTaskRequest<TResult> original, global::Orleans.Serialization.Cloning.CopyContext context) { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_Invokable_IDurableTaskGrainExtension_GrainReference_Ext_28018A01 : global::Orleans.Serialization.Cloning.IDeepCopier<Invokable_IDurableTaskGrainExtension_GrainReference_Ext_28018A01>, global::Orleans.Serialization.Cloning.IDeepCopier
    {
        public Copier_Invokable_IDurableTaskGrainExtension_GrainReference_Ext_28018A01(global::Orleans.Serialization.Cloning.IBaseCopier<global::Orleans.Runtime.AsyncEnumerableRequest<System.Distributed.DurableTasks.TaskId>> _baseTypeCopier) { }

        public Invokable_IDurableTaskGrainExtension_GrainReference_Ext_28018A01 DeepCopy(Invokable_IDurableTaskGrainExtension_GrainReference_Ext_28018A01 original, global::Orleans.Serialization.Cloning.CopyContext context) { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_Invokable_IDurableTaskGrainExtension_GrainReference_Ext_623DF2E6 : global::Orleans.Serialization.Cloning.IDeepCopier<Invokable_IDurableTaskGrainExtension_GrainReference_Ext_623DF2E6>, global::Orleans.Serialization.Cloning.IDeepCopier
    {
        public Copier_Invokable_IDurableTaskGrainExtension_GrainReference_Ext_623DF2E6(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public Invokable_IDurableTaskGrainExtension_GrainReference_Ext_623DF2E6 DeepCopy(Invokable_IDurableTaskGrainExtension_GrainReference_Ext_623DF2E6 original, global::Orleans.Serialization.Cloning.CopyContext context) { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_Invokable_IDurableTaskGrainExtension_GrainReference_Ext_69FFF0DD : global::Orleans.Serialization.Cloning.IDeepCopier<Invokable_IDurableTaskGrainExtension_GrainReference_Ext_69FFF0DD>, global::Orleans.Serialization.Cloning.IDeepCopier
    {
        public Copier_Invokable_IDurableTaskGrainExtension_GrainReference_Ext_69FFF0DD(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public Invokable_IDurableTaskGrainExtension_GrainReference_Ext_69FFF0DD DeepCopy(Invokable_IDurableTaskGrainExtension_GrainReference_Ext_69FFF0DD original, global::Orleans.Serialization.Cloning.CopyContext context) { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_Invokable_IDurableTaskGrainExtension_GrainReference_Ext_BB23D540 : global::Orleans.Serialization.Cloning.IDeepCopier<Invokable_IDurableTaskGrainExtension_GrainReference_Ext_BB23D540>, global::Orleans.Serialization.Cloning.IDeepCopier
    {
        public Copier_Invokable_IDurableTaskGrainExtension_GrainReference_Ext_BB23D540(global::Orleans.Serialization.Cloning.IBaseCopier<global::Orleans.Runtime.AsyncEnumerableRequest<(System.Distributed.DurableTasks.TaskId TaskId, global::Orleans.DurableTasks.DurableTaskDiagnosticState State)>> _baseTypeCopier) { }

        public Invokable_IDurableTaskGrainExtension_GrainReference_Ext_BB23D540 DeepCopy(Invokable_IDurableTaskGrainExtension_GrainReference_Ext_BB23D540 original, global::Orleans.Serialization.Cloning.CopyContext context) { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_Invokable_IDurableTaskGrainExtension_GrainReference_Ext_D5751EC2 : global::Orleans.Serialization.Cloning.IDeepCopier<Invokable_IDurableTaskGrainExtension_GrainReference_Ext_D5751EC2>, global::Orleans.Serialization.Cloning.IDeepCopier
    {
        public Copier_Invokable_IDurableTaskGrainExtension_GrainReference_Ext_D5751EC2(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public Invokable_IDurableTaskGrainExtension_GrainReference_Ext_D5751EC2 DeepCopy(Invokable_IDurableTaskGrainExtension_GrainReference_Ext_D5751EC2 original, global::Orleans.Serialization.Cloning.CopyContext context) { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_Invokable_IDurableTaskObserver_GrainReference_Ext_55C201CC : global::Orleans.Serialization.Cloning.IDeepCopier<Invokable_IDurableTaskObserver_GrainReference_Ext_55C201CC>, global::Orleans.Serialization.Cloning.IDeepCopier
    {
        public Copier_Invokable_IDurableTaskObserver_GrainReference_Ext_55C201CC(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public Invokable_IDurableTaskObserver_GrainReference_Ext_55C201CC DeepCopy(Invokable_IDurableTaskObserver_GrainReference_Ext_55C201CC original, global::Orleans.Serialization.Cloning.CopyContext context) { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_Invokable_IDurableTaskServer_GrainReference_Ext_623DF2E6 : global::Orleans.Serialization.Cloning.IDeepCopier<Invokable_IDurableTaskServer_GrainReference_Ext_623DF2E6>, global::Orleans.Serialization.Cloning.IDeepCopier
    {
        public Copier_Invokable_IDurableTaskServer_GrainReference_Ext_623DF2E6(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public Invokable_IDurableTaskServer_GrainReference_Ext_623DF2E6 DeepCopy(Invokable_IDurableTaskServer_GrainReference_Ext_623DF2E6 original, global::Orleans.Serialization.Cloning.CopyContext context) { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_Invokable_IDurableTaskServer_GrainReference_Ext_69FFF0DD : global::Orleans.Serialization.Cloning.IDeepCopier<Invokable_IDurableTaskServer_GrainReference_Ext_69FFF0DD>, global::Orleans.Serialization.Cloning.IDeepCopier
    {
        public Copier_Invokable_IDurableTaskServer_GrainReference_Ext_69FFF0DD(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public Invokable_IDurableTaskServer_GrainReference_Ext_69FFF0DD DeepCopy(Invokable_IDurableTaskServer_GrainReference_Ext_69FFF0DD original, global::Orleans.Serialization.Cloning.CopyContext context) { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_Invokable_IDurableTaskServer_GrainReference_Ext_D5751EC2 : global::Orleans.Serialization.Cloning.IDeepCopier<Invokable_IDurableTaskServer_GrainReference_Ext_D5751EC2>, global::Orleans.Serialization.Cloning.IDeepCopier
    {
        public Copier_Invokable_IDurableTaskServer_GrainReference_Ext_D5751EC2(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public Invokable_IDurableTaskServer_GrainReference_Ext_D5751EC2 DeepCopy(Invokable_IDurableTaskServer_GrainReference_Ext_D5751EC2 original, global::Orleans.Serialization.Cloning.CopyContext context) { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::Orleans.CompoundTypeAlias(new[] { "inv", typeof(global::Orleans.Runtime.GrainReference), "Ext", typeof(global::Orleans.DurableTasks.IDurableTaskGrainExtension), typeof(global::Orleans.DurableTasks.IDurableTaskGrainExtension), "GetRunningTasksAsync" })]
    [global::Orleans.CompoundTypeAlias(new[] { "inv", typeof(global::Orleans.Runtime.GrainReference), "Ext", typeof(global::Orleans.DurableTasks.IDurableTaskGrainExtension), typeof(global::Orleans.DurableTasks.IDurableTaskGrainExtension), "28018A01" })]
    public sealed partial class Invokable_IDurableTaskGrainExtension_GrainReference_Ext_28018A01 : global::Orleans.Runtime.AsyncEnumerableRequest<System.Distributed.DurableTasks.TaskId>
    {
        public System.Threading.CancellationToken arg0;
        public override bool IsCancellable { get { throw null; } }

        public override void Dispose() { }

        public override string GetActivityName() { throw null; }

        public override object GetArgument(int index) { throw null; }

        public override int GetArgumentCount() { throw null; }

        public override System.Threading.CancellationToken GetCancellationToken() { throw null; }

        public override string GetInterfaceName() { throw null; }

        public override System.Type GetInterfaceType() { throw null; }

        public override System.Reflection.MethodInfo GetMethod() { throw null; }

        public override string GetMethodName() { throw null; }

        public override object GetTarget() { throw null; }

        protected override System.Collections.Generic.IAsyncEnumerable<System.Distributed.DurableTasks.TaskId> InvokeInner() { throw null; }

        public override void SetArgument(int index, object value) { }

        public override void SetTarget(global::Orleans.Serialization.Invocation.ITargetHolder holder) { }

        public override bool TryCancel() { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::Orleans.CompoundTypeAlias(new[] { "inv", typeof(global::Orleans.Runtime.GrainReference), "Ext", typeof(global::Orleans.DurableTasks.IDurableTaskGrainExtension), typeof(global::Orleans.DurableTasks.IDurableTaskServer), "SubscribeOrPollAsync" })]
    [global::Orleans.CompoundTypeAlias(new[] { "inv", typeof(global::Orleans.Runtime.GrainReference), "Ext", typeof(global::Orleans.DurableTasks.IDurableTaskGrainExtension), typeof(global::Orleans.DurableTasks.IDurableTaskServer), "623DF2E6" })]
    public sealed partial class Invokable_IDurableTaskGrainExtension_GrainReference_Ext_623DF2E6 : global::Orleans.Runtime.Request<System.Distributed.DurableTasks.DurableTaskResponse>
    {
        public System.Distributed.DurableTasks.TaskId arg0;
        public global::Orleans.DurableTasks.SubscribeOrPollOptions arg1;
        public System.Threading.CancellationToken arg2;
        public override bool IsCancellable { get { throw null; } }

        public override void Dispose() { }

        public override string GetActivityName() { throw null; }

        public override object GetArgument(int index) { throw null; }

        public override int GetArgumentCount() { throw null; }

        public override System.Threading.CancellationToken GetCancellationToken() { throw null; }

        public override string GetInterfaceName() { throw null; }

        public override System.Type GetInterfaceType() { throw null; }

        public override System.Reflection.MethodInfo GetMethod() { throw null; }

        public override string GetMethodName() { throw null; }

        public override object GetTarget() { throw null; }

        protected override System.Threading.Tasks.ValueTask<System.Distributed.DurableTasks.DurableTaskResponse> InvokeInner() { throw null; }

        public override void SetArgument(int index, object value) { }

        public override void SetTarget(global::Orleans.Serialization.Invocation.ITargetHolder holder) { }

        public override bool TryCancel() { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::Orleans.CompoundTypeAlias(new[] { "inv", typeof(global::Orleans.Runtime.GrainReference), "Ext", typeof(global::Orleans.DurableTasks.IDurableTaskGrainExtension), typeof(global::Orleans.DurableTasks.IDurableTaskServer), "CancelAsync" })]
    [global::Orleans.CompoundTypeAlias(new[] { "inv", typeof(global::Orleans.Runtime.GrainReference), "Ext", typeof(global::Orleans.DurableTasks.IDurableTaskGrainExtension), typeof(global::Orleans.DurableTasks.IDurableTaskServer), "69FFF0DD" })]
    public sealed partial class Invokable_IDurableTaskGrainExtension_GrainReference_Ext_69FFF0DD : global::Orleans.Runtime.Request
    {
        public System.Distributed.DurableTasks.TaskId arg0;
        public System.Threading.CancellationToken arg1;
        public override bool IsCancellable { get { throw null; } }

        public override void Dispose() { }

        public override string GetActivityName() { throw null; }

        public override object GetArgument(int index) { throw null; }

        public override int GetArgumentCount() { throw null; }

        public override System.Threading.CancellationToken GetCancellationToken() { throw null; }

        public override string GetInterfaceName() { throw null; }

        public override System.Type GetInterfaceType() { throw null; }

        public override System.Reflection.MethodInfo GetMethod() { throw null; }

        public override string GetMethodName() { throw null; }

        public override object GetTarget() { throw null; }

        protected override System.Threading.Tasks.ValueTask InvokeInner() { throw null; }

        public override void SetArgument(int index, object value) { }

        public override void SetTarget(global::Orleans.Serialization.Invocation.ITargetHolder holder) { }

        public override bool TryCancel() { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::Orleans.CompoundTypeAlias(new[] { "inv", typeof(global::Orleans.Runtime.GrainReference), "Ext", typeof(global::Orleans.DurableTasks.IDurableTaskGrainExtension), typeof(global::Orleans.DurableTasks.IDurableTaskGrainExtension), "GetTasksAsync" })]
    [global::Orleans.CompoundTypeAlias(new[] { "inv", typeof(global::Orleans.Runtime.GrainReference), "Ext", typeof(global::Orleans.DurableTasks.IDurableTaskGrainExtension), typeof(global::Orleans.DurableTasks.IDurableTaskGrainExtension), "BB23D540" })]
    public sealed partial class Invokable_IDurableTaskGrainExtension_GrainReference_Ext_BB23D540 : global::Orleans.Runtime.AsyncEnumerableRequest<(System.Distributed.DurableTasks.TaskId TaskId, global::Orleans.DurableTasks.DurableTaskDiagnosticState State)>
    {
        public System.Threading.CancellationToken arg0;
        public override bool IsCancellable { get { throw null; } }

        public override void Dispose() { }

        public override string GetActivityName() { throw null; }

        public override object GetArgument(int index) { throw null; }

        public override int GetArgumentCount() { throw null; }

        public override System.Threading.CancellationToken GetCancellationToken() { throw null; }

        public override string GetInterfaceName() { throw null; }

        public override System.Type GetInterfaceType() { throw null; }

        public override System.Reflection.MethodInfo GetMethod() { throw null; }

        public override string GetMethodName() { throw null; }

        public override object GetTarget() { throw null; }

        protected override System.Collections.Generic.IAsyncEnumerable<(System.Distributed.DurableTasks.TaskId TaskId, global::Orleans.DurableTasks.DurableTaskDiagnosticState State)> InvokeInner() { throw null; }

        public override void SetArgument(int index, object value) { }

        public override void SetTarget(global::Orleans.Serialization.Invocation.ITargetHolder holder) { }

        public override bool TryCancel() { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::Orleans.CompoundTypeAlias(new[] { "inv", typeof(global::Orleans.Runtime.GrainReference), "Ext", typeof(global::Orleans.DurableTasks.IDurableTaskGrainExtension), typeof(global::Orleans.DurableTasks.IDurableTaskServer), "ScheduleAsync" })]
    [global::Orleans.CompoundTypeAlias(new[] { "inv", typeof(global::Orleans.Runtime.GrainReference), "Ext", typeof(global::Orleans.DurableTasks.IDurableTaskGrainExtension), typeof(global::Orleans.DurableTasks.IDurableTaskServer), "D5751EC2" })]
    public sealed partial class Invokable_IDurableTaskGrainExtension_GrainReference_Ext_D5751EC2 : global::Orleans.Runtime.Request<System.Distributed.DurableTasks.DurableTaskResponse>
    {
        public System.Distributed.DurableTasks.TaskId arg0;
        public global::Orleans.DurableTasks.IDurableTaskRequest arg1;
        public System.Threading.CancellationToken arg2;
        public override bool IsCancellable { get { throw null; } }

        public override void Dispose() { }

        public override string GetActivityName() { throw null; }

        public override object GetArgument(int index) { throw null; }

        public override int GetArgumentCount() { throw null; }

        public override System.Threading.CancellationToken GetCancellationToken() { throw null; }

        public override string GetInterfaceName() { throw null; }

        public override System.Type GetInterfaceType() { throw null; }

        public override System.Reflection.MethodInfo GetMethod() { throw null; }

        public override string GetMethodName() { throw null; }

        public override object GetTarget() { throw null; }

        protected override System.Threading.Tasks.ValueTask<System.Distributed.DurableTasks.DurableTaskResponse> InvokeInner() { throw null; }

        public override void SetArgument(int index, object value) { }

        public override void SetTarget(global::Orleans.Serialization.Invocation.ITargetHolder holder) { }

        public override bool TryCancel() { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::Orleans.CompoundTypeAlias(new[] { "inv", typeof(global::Orleans.Runtime.GrainReference), "Ext", typeof(global::Orleans.DurableTasks.IDurableTaskObserver), typeof(global::Orleans.DurableTasks.IDurableTaskObserver), "OnResponse" })]
    [global::Orleans.CompoundTypeAlias(new[] { "inv", typeof(global::Orleans.Runtime.GrainReference), "Ext", typeof(global::Orleans.DurableTasks.IDurableTaskObserver), typeof(global::Orleans.DurableTasks.IDurableTaskObserver), "55C201CC" })]
    public sealed partial class Invokable_IDurableTaskObserver_GrainReference_Ext_55C201CC : global::Orleans.Runtime.Request
    {
        public System.Distributed.DurableTasks.TaskId arg0;
        public System.Distributed.DurableTasks.DurableTaskResponse arg1;
        public System.Threading.CancellationToken arg2;
        public override bool IsCancellable { get { throw null; } }

        public override void Dispose() { }

        public override string GetActivityName() { throw null; }

        public override object GetArgument(int index) { throw null; }

        public override int GetArgumentCount() { throw null; }

        public override System.Threading.CancellationToken GetCancellationToken() { throw null; }

        public override string GetInterfaceName() { throw null; }

        public override System.Type GetInterfaceType() { throw null; }

        public override System.Reflection.MethodInfo GetMethod() { throw null; }

        public override string GetMethodName() { throw null; }

        public override object GetTarget() { throw null; }

        protected override System.Threading.Tasks.ValueTask InvokeInner() { throw null; }

        public override void SetArgument(int index, object value) { }

        public override void SetTarget(global::Orleans.Serialization.Invocation.ITargetHolder holder) { }

        public override bool TryCancel() { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::Orleans.CompoundTypeAlias(new[] { "inv", typeof(global::Orleans.Runtime.GrainReference), "Ext", typeof(global::Orleans.DurableTasks.IDurableTaskServer), typeof(global::Orleans.DurableTasks.IDurableTaskServer), "SubscribeOrPollAsync" })]
    [global::Orleans.CompoundTypeAlias(new[] { "inv", typeof(global::Orleans.Runtime.GrainReference), "Ext", typeof(global::Orleans.DurableTasks.IDurableTaskServer), typeof(global::Orleans.DurableTasks.IDurableTaskServer), "623DF2E6" })]
    public sealed partial class Invokable_IDurableTaskServer_GrainReference_Ext_623DF2E6 : global::Orleans.Runtime.Request<System.Distributed.DurableTasks.DurableTaskResponse>
    {
        public System.Distributed.DurableTasks.TaskId arg0;
        public global::Orleans.DurableTasks.SubscribeOrPollOptions arg1;
        public System.Threading.CancellationToken arg2;
        public override bool IsCancellable { get { throw null; } }

        public override void Dispose() { }

        public override string GetActivityName() { throw null; }

        public override object GetArgument(int index) { throw null; }

        public override int GetArgumentCount() { throw null; }

        public override System.Threading.CancellationToken GetCancellationToken() { throw null; }

        public override string GetInterfaceName() { throw null; }

        public override System.Type GetInterfaceType() { throw null; }

        public override System.Reflection.MethodInfo GetMethod() { throw null; }

        public override string GetMethodName() { throw null; }

        public override object GetTarget() { throw null; }

        protected override System.Threading.Tasks.ValueTask<System.Distributed.DurableTasks.DurableTaskResponse> InvokeInner() { throw null; }

        public override void SetArgument(int index, object value) { }

        public override void SetTarget(global::Orleans.Serialization.Invocation.ITargetHolder holder) { }

        public override bool TryCancel() { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::Orleans.CompoundTypeAlias(new[] { "inv", typeof(global::Orleans.Runtime.GrainReference), "Ext", typeof(global::Orleans.DurableTasks.IDurableTaskServer), typeof(global::Orleans.DurableTasks.IDurableTaskServer), "CancelAsync" })]
    [global::Orleans.CompoundTypeAlias(new[] { "inv", typeof(global::Orleans.Runtime.GrainReference), "Ext", typeof(global::Orleans.DurableTasks.IDurableTaskServer), typeof(global::Orleans.DurableTasks.IDurableTaskServer), "69FFF0DD" })]
    public sealed partial class Invokable_IDurableTaskServer_GrainReference_Ext_69FFF0DD : global::Orleans.Runtime.Request
    {
        public System.Distributed.DurableTasks.TaskId arg0;
        public System.Threading.CancellationToken arg1;
        public override bool IsCancellable { get { throw null; } }

        public override void Dispose() { }

        public override string GetActivityName() { throw null; }

        public override object GetArgument(int index) { throw null; }

        public override int GetArgumentCount() { throw null; }

        public override System.Threading.CancellationToken GetCancellationToken() { throw null; }

        public override string GetInterfaceName() { throw null; }

        public override System.Type GetInterfaceType() { throw null; }

        public override System.Reflection.MethodInfo GetMethod() { throw null; }

        public override string GetMethodName() { throw null; }

        public override object GetTarget() { throw null; }

        protected override System.Threading.Tasks.ValueTask InvokeInner() { throw null; }

        public override void SetArgument(int index, object value) { }

        public override void SetTarget(global::Orleans.Serialization.Invocation.ITargetHolder holder) { }

        public override bool TryCancel() { throw null; }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::Orleans.CompoundTypeAlias(new[] { "inv", typeof(global::Orleans.Runtime.GrainReference), "Ext", typeof(global::Orleans.DurableTasks.IDurableTaskServer), typeof(global::Orleans.DurableTasks.IDurableTaskServer), "ScheduleAsync" })]
    [global::Orleans.CompoundTypeAlias(new[] { "inv", typeof(global::Orleans.Runtime.GrainReference), "Ext", typeof(global::Orleans.DurableTasks.IDurableTaskServer), typeof(global::Orleans.DurableTasks.IDurableTaskServer), "D5751EC2" })]
    public sealed partial class Invokable_IDurableTaskServer_GrainReference_Ext_D5751EC2 : global::Orleans.Runtime.Request<System.Distributed.DurableTasks.DurableTaskResponse>
    {
        public System.Distributed.DurableTasks.TaskId arg0;
        public global::Orleans.DurableTasks.IDurableTaskRequest arg1;
        public System.Threading.CancellationToken arg2;
        public override bool IsCancellable { get { throw null; } }

        public override void Dispose() { }

        public override string GetActivityName() { throw null; }

        public override object GetArgument(int index) { throw null; }

        public override int GetArgumentCount() { throw null; }

        public override System.Threading.CancellationToken GetCancellationToken() { throw null; }

        public override string GetInterfaceName() { throw null; }

        public override System.Type GetInterfaceType() { throw null; }

        public override System.Reflection.MethodInfo GetMethod() { throw null; }

        public override string GetMethodName() { throw null; }

        public override object GetTarget() { throw null; }

        protected override System.Threading.Tasks.ValueTask<System.Distributed.DurableTasks.DurableTaskResponse> InvokeInner() { throw null; }

        public override void SetArgument(int index, object value) { }

        public override void SetTarget(global::Orleans.Serialization.Invocation.ITargetHolder holder) { }

        public override bool TryCancel() { throw null; }
    }
}

namespace OrleansCodeGen.Orleans.Runtime.DurableTasks
{
    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_DurableTaskState : global::Orleans.Serialization.Codecs.IFieldCodec<global::Orleans.Runtime.DurableTasks.DurableTaskState>, global::Orleans.Serialization.Codecs.IFieldCodec, global::Orleans.Serialization.Serializers.IBaseCodec<global::Orleans.Runtime.DurableTasks.DurableTaskState>, global::Orleans.Serialization.Serializers.IBaseCodec
    {
        public Codec_DurableTaskState(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public void Deserialize<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.Runtime.DurableTasks.DurableTaskState instance) { }

        public global::Orleans.Runtime.DurableTasks.DurableTaskState ReadValue<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, global::Orleans.Runtime.DurableTasks.DurableTaskState instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, global::Orleans.Runtime.DurableTasks.DurableTaskState value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_DurableTaskState : global::Orleans.Serialization.Cloning.IDeepCopier<global::Orleans.Runtime.DurableTasks.DurableTaskState>, global::Orleans.Serialization.Cloning.IDeepCopier, global::Orleans.Serialization.Cloning.IBaseCopier<global::Orleans.Runtime.DurableTasks.DurableTaskState>, global::Orleans.Serialization.Cloning.IBaseCopier
    {
        public Copier_DurableTaskState(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) { }

        public void DeepCopy(global::Orleans.Runtime.DurableTasks.DurableTaskState input, global::Orleans.Runtime.DurableTasks.DurableTaskState output, global::Orleans.Serialization.Cloning.CopyContext context) { }

        public global::Orleans.Runtime.DurableTasks.DurableTaskState DeepCopy(global::Orleans.Runtime.DurableTasks.DurableTaskState original, global::Orleans.Serialization.Cloning.CopyContext context) { throw null; }
    }
}