//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Orleans.Configuration
{
    public partial class RedisReminderTableOptions
    {
        public StackExchange.Redis.ConfigurationOptions ConfigurationOptions { get { throw null; } set { } }

        public System.Func<RedisReminderTableOptions, System.Threading.Tasks.Task<StackExchange.Redis.IConnectionMultiplexer>> CreateMultiplexer { get { throw null; } set { } }

        public System.TimeSpan? EntryExpiry { get { throw null; } set { } }

        public static System.Threading.Tasks.Task<StackExchange.Redis.IConnectionMultiplexer> DefaultCreateMultiplexer(RedisReminderTableOptions options) { throw null; }
    }

    public partial class RedisReminderTableOptionsValidator : IConfigurationValidator
    {
        public RedisReminderTableOptionsValidator(Microsoft.Extensions.Options.IOptions<RedisReminderTableOptions> options) { }

        public void ValidateConfiguration() { }
    }
}

namespace Orleans.Hosting
{
    public static partial class SiloBuilderReminderExtensions
    {
        public static Microsoft.Extensions.DependencyInjection.IServiceCollection UseRedisReminderService(this Microsoft.Extensions.DependencyInjection.IServiceCollection services, System.Action<Configuration.RedisReminderTableOptions> configure) { throw null; }

        public static ISiloBuilder UseRedisReminderService(this ISiloBuilder builder, System.Action<Configuration.RedisReminderTableOptions> configure) { throw null; }
    }
}

namespace Orleans.Reminders.Redis
{
    [GenerateSerializer]
    public partial class RedisRemindersException : System.Exception
    {
        public RedisRemindersException() { }

        [System.Obsolete]
        protected RedisRemindersException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) { }

        public RedisRemindersException(string message, System.Exception inner) { }

        public RedisRemindersException(string message) { }
    }
}

namespace OrleansCodeGen.Orleans.Reminders.Redis
{
    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Codec_RedisRemindersException : global::Orleans.Serialization.Codecs.IFieldCodec<global::Orleans.Reminders.Redis.RedisRemindersException>, global::Orleans.Serialization.Codecs.IFieldCodec, global::Orleans.Serialization.Serializers.IBaseCodec<global::Orleans.Reminders.Redis.RedisRemindersException>, global::Orleans.Serialization.Serializers.IBaseCodec
    {
        public Codec_RedisRemindersException(global::Orleans.Serialization.Serializers.IBaseCodec<System.Exception> _baseTypeSerializer) { }

        public void Deserialize<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.Reminders.Redis.RedisRemindersException instance) { }

        public global::Orleans.Reminders.Redis.RedisRemindersException ReadValue<TReaderInput>(ref global::Orleans.Serialization.Buffers.Reader<TReaderInput> reader, global::Orleans.Serialization.WireProtocol.Field field) { throw null; }

        public void Serialize<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, global::Orleans.Reminders.Redis.RedisRemindersException instance)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }

        public void WriteField<TBufferWriter>(ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, System.Type expectedType, global::Orleans.Reminders.Redis.RedisRemindersException value)
            where TBufferWriter : System.Buffers.IBufferWriter<byte> { }
    }

    [System.CodeDom.Compiler.GeneratedCode("OrleansCodeGen", "10.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class Copier_RedisRemindersException : global::Orleans.Serialization.GeneratedCodeHelpers.OrleansGeneratedCodeHelper.ExceptionCopier<global::Orleans.Reminders.Redis.RedisRemindersException, System.Exception>
    {
        public Copier_RedisRemindersException(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider) : base(default(Serialization.Serializers.ICodecProvider)!) { }
    }
}