<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Orleans.Client" Version="10.2.2" />
    <PackageVersion Include="Microsoft.Orleans.Sdk" Version="10.2.2" />
    <PackageVersion Include="Microsoft.Orleans.Server" Version="10.2.2" />
    <PackageVersion Include="MsgPack.Cli" Version="1.0.1" />
  </ItemGroup>
</Project>
