## Service definition ##
application:
  schemaVersion: 1.0.0-preview1
  name: VotingApp
  properties:
    services:
      - name: VotingWeb
        properties:
          description: VotingWeb description.
          osType: Windows
          codePackages:
            - name: VotingWeb
              image: votingweb:dev
              endpoints:
                - name: VotingWebListener
                  port: 20005
              environmentVariables:
                - name: ASPNETCORE_URLS
                  value: http://+:20005
                - name: CLUSTERING_CONNECTION_STRING
                  value: "Replace this with an Azure Storage Connection String"
              resources:
                requests:
                  cpu: 0.5
                  memoryInGB: 1
          replicaCount: 1
          networkRefs:
            - name: VotingAppNetwork