<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(TestTargetFrameworks)</TargetFrameworks>
    <Nullable>enable</Nullable>
    <OrleansBuildTimeCodeGen>true</OrleansBuildTimeCodeGen>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Dashboard\Orleans.Dashboard\Orleans.Dashboard.csproj" />
    <ProjectReference Include="..\..\..\src\Orleans.TestingHost\Orleans.TestingHost.csproj" />
    <ProjectReference Include="..\..\TestInfrastructure\TestExtensions\TestExtensions.csproj" />
    <ProjectReference Include="..\Orleans.Dashboard.TestGrains\Orleans.Dashboard.TestGrains.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>

</Project>
